/*
 * Card:
 *   ID Name Description Event Border Stars Place Place2 Prototype Shape Attribute HP MP ATK DEF AGI WIS 
 *   Skills Recommends RecommendsRB
 */
Card.addAll([
    ["00001", "Will-o'-the-Wisp", "A floating ball of fire that appears near water at night to lead travelers astray with the glow of its flames.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.orbs, Attribute.fire,
     424, 500, 420, 468, 470, 477,
     [Skill.fire1, Skill.atk10, Skill.fire2],
     [Skill.fire1, Skill.atk10, Skill.fire2],
     []],
    ["00002", "Ukobach", "A lesser demon that feeds oil into the boilers and cauldrons of hell with an enormous, blazing ladle.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.fire,
     490, 439, 478, 415, 472, 451,
     [Skill.fire1, Skill.physical1, Skill.physical2],
     [Skill.fire1, Skill.physical1, Skill.physical2],
     []],
    ["00003", "Salamander", "An elemental with fire at its command that grows ever more powerful by consuming flames.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.wolf, Attribute.fire,
     481, 462, 516, 493, 472, 478,
     [Skill.def10, Skill.physical1, Skill.fire2],
     [Skill.def10, Skill.physical1, Skill.fire2],
     []],
    ["00004", "Hellhound", "Wreathed in hellfire, this hound prowls in the dark of night, slaying any mortal that crosses its path.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.wolf, Attribute.fire,
     503, 446, 508, 511, 488, 469,
     [Skill.fire1, Skill.physical1, Skill.fire2],
     [Skill.fire1, Skill.physical1, Skill.fire2],
     []],
    ["00005", "Undine", "A water elemental that appears as a maiden. Humans oft succumb to its beauty, falling deeply in love.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.water,
     458, 490, 462, 480, 468, 513,
     [Skill.water1, Skill.datk20, Skill.water2],
     [Skill.water1, Skill.datk20, Skill.water2],
     []],
    ["00006", "Siren", "A creature of the sea that uses its enchanting voice to cause shipwrecks by luring seafarers off course.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.orbs, Attribute.water,
     464, 532, 448, 488, 474, 500,
     [Skill.water1, Skill.physical1, Skill.water2],
     [],
     []],
    ["00007", "Mermaid", "An intelligent creature of parts both human and fish that lives in great kingdoms on the oceans' floors", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.water,
     479, 480, 470, 493, 502, 532,
     [Skill.water1, Skill.wis10, Skill.water2],
     [Skill.water1, Skill.wis10, Skill.water2],
     []],
    ["00008", "Lizardman", "Though generally peaceful, the culture of these reptilian humanoids hones them into deadly warriors.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.water,
     523, 460, 532, 520, 526, 463,
     [Skill.slash1, Skill.water1, Skill.slash2],
     [Skill.slash1, Skill.water1, Skill.slash2],
     []],
    ["00009", "Kobold", "A cruel, cowardly creature that lives in packs underground or in caves, where it laces silver with poison.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.humanoid, Attribute.earth,
     479, 424, 470, 455, 498, 426,
     [Skill.slash1, Skill.ddef20, Skill.slash2],
     [Skill.slash1, Skill.ddef20, Skill.slash2],
     []],
    ["00010", "Dryad", "This warden spirit of the trees punishes all who harm the forest, but dies if the tree it inhabits withers.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.earth,
     490, 497, 465, 483, 480, 500,
     [Skill.earth1, Skill.def10, Skill.earth2],
     [],
     []],
    ["00011", "Dwarf", "Strong and stout of body, these short humanoids are known for their long beards and prowess in battle.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.earth,
     525, 464, 511, 519, 410, 446,
     [Skill.slash1, Skill.atk10, Skill.slash2],
     [Skill.slash1, Skill.atk10, Skill.slash2],
     []],
    ["00012", "Gnome", "This elemental of the earth creates wares of fine craftsmanship and guards its treasure below ground.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.earth,
     462, 499, 480, 485, 502, 500,
     [Skill.earth1, Skill.slash1, Skill.earth2],
     [Skill.earth1, Skill.slash1, Skill.earth2],
     []],
    ["00013", "Chonchon", "This avian monster sucks the life force from its mortal victims and flies with its huge ear-shaped wings.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.orbs, Attribute.lightning,
     430, 417, 472, 476, 505, 456,
     [Skill.life, Skill.lightning1, Skill.mana],
     [Skill.life, Skill.lightning1, Skill.mana],
     []],
    ["00014", "Raiju", "A small being that descends to earth during storms upon bolts of lightning, visiting woe upon mortal man.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.wolf, Attribute.lightning,
     446, 471, 521, 483, 528, 475,
     [Skill.lightning1, Skill.physical1, Skill.lightning2],
     [Skill.lightning1, Skill.physical1, Skill.lightning2],
     []],
    ["00015", "Amazon", "From a tribe comprising only females, this huntress's skill with bow and spear puts any man to shame.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.wind,
     488, 446, 503, 485, 470, 463,
     [Skill.slash1, Skill.atk10, Skill.slash2],
     [Skill.slash1, Skill.atk10, Skill.slash2],
     []],
    ["00016", "Kamaitachi", "Riding upon whirlwinds, this beast slashes mercilessly at its prey with the sharp blades of its legs.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.orbs, Attribute.wind,
     481, 494, 511, 442, 524, 456,
     [Skill.agi10, Skill.physical1, Skill.wind2],
     [Skill.agi10, Skill.physical1, Skill.wind2],
     []],
    ["00017", "Gremlin", "A small, winged demon with a penchant for sabotaging machinery, flying vessels in particular.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.wind,
     497, 466, 478, 462, 498, 469,
     [Skill.datk20, Skill.physical1, Skill.physical2],
     [Skill.datk20, Skill.physical1, Skill.physical2],
     []],
    ["00018", "Sylph", "Though graceful to look upon, this air elemental is possessed of great power and can summon storms.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.humanoid, Attribute.wind,
     473, 506, 388, 451, 496, 525,
     [Skill.wind1, Skill.agi10, Skill.wind2],
     [Skill.wind1, Skill.agi10, Skill.wind2],
     []],
    ["00019", "Arachne", "This monstrous spideress spines fine silk with which she weaves intricate webs to capture her prey.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.wolf, Attribute.poison,
     479, 460, 520, 522, 518, 522,
     [Skill.physical1, Skill.dagi20, Skill.physical3],
     [Skill.physical1, Skill.dagi20, Skill.physical3],
     []],
    ["00020", "Slime", "A mass of gelatinous ooze that crawls through caves and ruins in search of prey to absorb and digest.", 
     Event.none, Border.none, 1, Place.grounds, 0, null, Shape.slime, Attribute.poison,
     460, 453, 456, 500, 453, 422,
     [Skill.dagi20, Skill.ddef20, Skill.datk20],
     [Skill.dagi20, Skill.ddef20, Skill.datk20],
     []],
    ["00021", "Mothman", "With its piercing red eyes and moth-like wings, this humanoid descends on its unwary prey from above.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.bird, Attribute.poison,
     492, 439, 448, 483, 478, 490,
     [Skill.agi10, Skill.physical1, Skill.physical2],
     [Skill.agi10, Skill.physical1, Skill.physical2],
     []],
    ["00022", "Ghoul", "Rising when an evil spirit possesses mortal remains, the ghoul is damned to feed on graveyard corpses.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.death,
     512, 460, 504, 442, 439, 460,
     [Skill.physical1, Skill.ddef20, Skill.poison2],
     [Skill.physical1, Skill.ddef20, Skill.poison2],
     []],
    ["00023", "Skeleton", "This mindless, magically reanimated collection of bones does nothing beyond what it is commanded.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.death,
     457, 452, 522, 464, 470, 447,
     [Skill.slash1, Skill.dagi20, Skill.slash2],
     [Skill.slash1, Skill.dagi20, Skill.slash2],
     []],
    ["00024", "Zombie", "Pried from death's grasp by sorcery, this minion now serves only to carry out the will of its master.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.humanoid, Attribute.death,
     522, 438, 478, 442, 432, 438,
     [Skill.slash1, Skill.poison1, Skill.revival],
     [Skill.slash1, Skill.poison1, Skill.revival],
     []],
    ["00026", "Elf", "A beautiful faerie resembling a human that is skilled in archery and dedicated to the defense of all nature.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.light,
     486, 501, 501, 440, 502, 512,
     [Skill.light1, Skill.slash1, Skill.light2],
     [Skill.light1, Skill.slash1, Skill.light2],
     []],
    ["00027", "Carbuncle", "Those who prize the jewel from this small creature's brow are said to gain great riches and glory.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.orbs, Attribute.light,
     470, 483, 516, 470, 522, 451,
     [Skill.light1, Skill.slash1, Skill.light2],
     [Skill.light1, Skill.slash1, Skill.light2],
     []],
    ["00028", "Pixie", "This small faerie lives among ancient barrows and at times helps mortals for something small in return.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.bird, Attribute.light,
     440, 469, 440, 448, 516, 513,
     [Skill.light1, Skill.heal, Skill.light2],
     [Skill.light1, Skill.heal, Skill.light2],
     []],
    ["00029", "Imp", "This small demon is fond of evil mischief, yet its foolish nature often causes its attempts to end in failure.", 
     Event.none, Border.none, 1, Place.plains, 0, null, Shape.bird, Attribute.darkness,
     499, 470, 465, 454, 482, 468,
     [Skill.darkness1, Skill.physical1, Skill.darkness2],
     [],
     []],
    ["00030", "Gargoyle", "This stone monstrosity stands still as a statue, taking its prey unawares when it draws near.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.bird, Attribute.darkness,
     532, 410, 529, 532, 522, 485,
     [Skill.def10, Skill.slash1, Skill.slash2],
     [Skill.def10, Skill.slash1, Skill.slash2],
     []],
    ["00031", "Goblin", "These greedy creatures live in clans within caves, venturing forth to raid the settlements of other races.", 
     Event.none, Border.none, 1, Place.volcano, 0, null, Shape.humanoid, Attribute.darkness,
     484, 462, 526, 462, 458, 440,
     [Skill.physical1, Skill.atk10, Skill.physical2],
     [Skill.physical1, Skill.atk10, Skill.physical2],
     []],
    ["00032", "Magenta Dragonling", "One of the six dragonlings, this creature's movements confuse foes as it stabs true with its shortsword.", 
     Event.dragon, Border.none, 1, Place.plains, 0, null, Shape.dragon, Attribute.death,
     496, 475, 529, 483, 499, 460,
     [Skill.darkness1, Skill.ddef20, Skill.darkness2],
     [Skill.darkness1, Skill.ddef20, Skill.darkness2],
     []],
    ["00033", "Cyan Dragonling", "One of the six dragonlings, this creature boasts a speed incongruous with its portly form.", 
     Event.dragon, Border.none, 1, Place.plains, 0, null, Shape.dragon, Attribute.water,
     450, 470, 492, 505, 539, 485,
     [Skill.water1, Skill.agi10, Skill.water2],
     [Skill.water1, Skill.agi10, Skill.water2],
     []],
    ["00034", "Mighty Magenta Dragonling", "?", 
     Event.dragon, Border.none, 1, Place.volcano, 0, null, Shape.dragon, Attribute.death,
     520, 504, 555, 507, 523, 483,
     [Skill.darkness1, Skill.ddef20, Skill.darkness2],
     [Skill.darkness1, Skill.ddef20, Skill.darkness2],
     []],
    ["00035", "Mighty Cyan Dragonling", "?", 
     Event.dragon, Border.none, 1, Place.volcano, 0, null, Shape.dragon, Attribute.water,
     472, 504, 516, 530, 565, 509,
     [Skill.water1, Skill.agi10, Skill.water2],
     [Skill.water1, Skill.agi10, Skill.water2],
     []],
    ["00036", "Apaosha", "When this demon of droughts races through the sky, all below dries, cracks, wilts, and dies.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.wolf, Attribute.fire,
     523, 437, 518, 523, 528, 437,
     [Skill.fire1, Skill.def10, Skill.slash2],
     [Skill.fire1, Skill.def10, Skill.slash2],
     []],
    ["00037", "Afanc", "This deceptively fierce and powerful monster dwells near water and has a weakness for young maidens.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.wolf, Attribute.water,
     438, 440, 557, 459, 444, 449,
     [Skill.slash1, Skill.water1, Skill.slash2],
     [Skill.slash1, Skill.water1, Skill.slash2],
     []],
    ["00038", "Ice Lizardman", "This reptilian lives among fields of ice and snow, and is larger than its kin found in warmer regions.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.wolf, Attribute.water,
     523, 437, 518, 513, 447, 518,
     [Skill.slash1, Skill.water1, Skill.dagi20],
     [Skill.slash1, Skill.water1, Skill.dagi20],
     []],
    ["00039", "Frost Worm", "This giant beast crawls through wintry plains, taking in snow and rime with which to blast its prey.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.dragon, Attribute.water,
     556, 444, 542, 547, 408, 440,
     [Skill.slash1, Skill.dagi20, Skill.water2],
     [Skill.slash1, Skill.dagi20, Skill.water2],
     []],
    ["00040", "Parandus", "Much like a chameleon, this beast is able to change colors to blend into in surroundings.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.wolf, Attribute.earth,
     440, 438, 480, 540, 454, 438,
     [Skill.dagi20, Skill.dwis20, Skill.slash2],
     [Skill.dagi20, Skill.dwis20, Skill.slash2],
     []],
    ["00041", "Stonka", "Dark in the sky, this taurine incarnation of a storm cloud bellows thunder that shakes the earth.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.wolf, Attribute.lightning,
     537, 437, 499, 518, 461, 466,
     [Skill.lightning1, Skill.physical1, Skill.lightning2],
     [Skill.lightning1, Skill.physical1, Skill.lightning2],
     []],
    ["00042", "Hippogriff", "Half bird and half horse, this proud creature flies gracefully through the skies on its beautiful wings.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.bird, Attribute.wind,
     527, 455, 510, 501, 580, 495,
     [Skill.wind1, Skill.agi10, Skill.agi20],
     [Skill.wind1, Skill.agi10, Skill.agi20],
     []],
    ["00043", "Vapak", "This elemental lives in poisonous mushrooms, which she entices man to eat to bring under her control.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.humanoid, Attribute.poison,
     437, 556, 440, 452, 456, 552,
     [Skill.poison1, Skill.dwis20, Skill.poison2],
     [Skill.poison1, Skill.dwis20, Skill.poison2],
     []],
    ["00044", "Manticore", "Full of guile and greed, this cruel beast has a tail of venomous barbs and reveals in trapping its prey.", 
     Event.none, Border.none, 1, Place.snowfield, 0, null, Shape.wolf, Attribute.poison,
     528, 499, 518, 456, 442, 504,
     [Skill.slash1, Skill.wis10, Skill.poison2],
     [Skill.slash1, Skill.wis10, Skill.poison2],
     []],
    ["00045", "Green Pixie", "One of the seven pixies of good fortune. It gives its all in any endeavor, but is perhaps a bit too serious.", 
     Event.pixie, Border.none, 1, Place.plains, 0, null, Shape.orbs, Attribute.wind,
     519, 487, 468, 534, 514, 460,
     [Skill.wind1, Skill.atk10, Skill.physical2],
     [Skill.wind1, Skill.atk10, Skill.physical2],
     []],
    ["00046", "Orange Pixie", "One of the seven pixies of good fortune. It is the rational elder who watches lovingly over the others.", 
     Event.pixie, Border.none, 1, Place.volcano, 0, null, Shape.orbs, Attribute.earth,
     496, 525, 475, 493, 445, 559,
     [Skill.earth1, Skill.wis10, Skill.earth2],
     [Skill.earth1, Skill.wis10, Skill.earth2],
     []],
    ["00047", "Blue Pixie", "One of the seven pixies of good fortune. Ever the calm cynic, it oft acts as mediator among its siblings.", 
     Event.pixie, Border.none, 1, Place.snowfield, 0, null, Shape.orbs, Attribute.water,
     470, 506, 499, 473, 519, 535, 
     [Skill.physical1, Skill.agi10, Skill.water2],
     [Skill.physical1, Skill.agi10, Skill.water2],
     []],
    ["00048", "Anansi", "This shapeshifter revels in mischief, but at times acts out of good as well as evil, such is its caprice.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.wolf, Attribute.earth,
     451, 485, 489, 455, 483, 513,
     [Skill.ddef20, Skill.dwis20, Skill.dagi20],
     [Skill.ddef20, Skill.dwis20, Skill.dagi20],
     []],
    ["00049", "Borak", "This divine being soars the skies, beautifule to behold and possessed of a speed that transcends time.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.female, Attribute.lightning,
     495, 452, 485, 453, 591, 475,
     [Skill.qs, Skill.agi10, Skill.lightning2],
     [Skill.qs, Skill.agi10, Skill.lightning2],
     []],
    ["00050", "Anzu", "By stealing the Tablet of Destinies, this stormbird gained power enough to rival the gods themselves.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.bird, Attribute.wind,
     465, 513, 549, 515, 481, 557,
     [Skill.wis10, Skill.agi10, Skill.wind2],
     [Skill.wis10, Skill.agi10, Skill.wind2],
     []],
    ["00051", "Catoblepas", "This beast spews toxic breath, and its massive head houses eyes whose gaze turn the living to stone.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.wolf, Attribute.poison,
     513, 472, 512, 492, 451, 529,
     [Skill.poison1, Skill.dagi20, Skill.poison2],
     [Skill.poison1, Skill.dagi20, Skill.poison2],
     []],
    ["00052", "Zhen", "Wheresoever this avian terror roosts, the vile poisons coursing through its body bring death and decay.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.bird, Attribute.poison,
     503, 490, 462, 491, 539, 484,
     [Skill.poison1, Skill.slash1, Skill.agi10],
     [Skill.poison1, Skill.slash1, Skill.agi10],
     []],
    ["00053", "Bonnacon", "When pursued, this beast of the deep wild expels a blast of ungodly dung which burns all that it touches.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.wolf, Attribute.poison,
     495, 456, 489, 501, 476, 459,
     [Skill.poison1, Skill.fire1, Skill.ls],
     [Skill.poison1, Skill.fire1, Skill.ls],
     []],
    ["00054", "Shade", "This being is the very form of darkness itself, hiding among the shadows as it hunts all who cast them.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.orbs, Attribute.death,
     469, 537, 459, 476, 467, 555,
     [Skill.death1, Skill.slash1, Skill.revival],
     [Skill.death1, Skill.slash1, Skill.revival],
     []],
    ["00055", "Apis", "Mortals worship this sacred bull as avatar of both the god of craftsmen and the god of the underworld.", 
     Event.none, Border.none, 1, Place.desert, 0, null, Shape.wolf, Attribute.light,
     547, 495, 460, 539, 479, 499,
     [Skill.light1, Skill.heal, Skill.ls],
     [Skill.light1, Skill.heal, Skill.ls],
     []],
    ["00056", "Amethyst Serpent", "Symbol of the duality of hope and despair, this beast guards a violet gem told to house the power of inspiration.", 
     Event.serpents, Border.none, 1, Place.snowfield, 0, null, Shape.dragon, Attribute.poison,
     540, 506, 510, 485, 450, 560,
     [Skill.poison1, Skill.dwis20, Skill.poison2],
     [Skill.poison1, Skill.dwis20, Skill.poison2],
     []],
    ["00057", "Topaz Serpent", "The yellow stone over which this snake holds vigil shines brightly even in the deep of night, lighting the paths of fate.", 
     Event.serpents, Border.none, 1, Place.volcano, 0, null, Shape.dragon, Attribute.lightning,
     470, 510, 525, 473, 556, 463,
     [Skill.lightning2, Skill.agi10, Skill.qs],
     [Skill.lightning2, Skill.agi10, Skill.qs],
     []],
    ["00058", "Water Leaper", "The shrill, rending cries of this creature paralyze its prey, which it then drags beneath the murk and mire to devour.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.shark, Attribute.water,
     472, 508, 478, 458, 536, 477,
     [Skill.water1, Skill.dagi20, Skill.datk20],
     [Skill.water1, Skill.dagi20, Skill.datk20],
     []],
    ["00059", "Echeneis", "This serpent swims in the cold seas to the north freezing the water with wintry hisses to ensnare hapless ships.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.shark, Attribute.water,
     532, 472, 487, 504, 513, 468,
     [Skill.physical1, Skill.water1, Skill.wis10],
     [Skill.physical1, Skill.water1, Skill.wis10],
     []],
    ["00060", "Gurangatch", "The powers of this lord of fish are such that his name is feared even upon land, far beyond his watery realm.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.serpent, Attribute.water,
     548, 488, 508, 506, 476, 483,
     [Skill.physical1, Skill.water1, Skill.physical2],
     [Skill.physical1, Skill.water1, Skill.physical2],
     []],
    ["00061", "Cetus", "When man's hubris woke the wrath of the gods, this ocean terror was sent to lay waste to the heart of an empire.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.shark, Attribute.water,
     562, 467, 548, 531, 469, 472,
     [Skill.water1, Skill.physical2, Skill.ls],
     [Skill.water1, Skill.physical2, Skill.ls],
     []],
    ["00062", "Sea Wyvern", "Gliding through water rather than sky, this drake of the seas is one of many menaces found beneath the waves.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.shark, Attribute.water,
     481, 463, 551, 478, 563, 478,
     [Skill.water1, Skill.physical1, Skill.physical2],
     [Skill.water1, Skill.physical1, Skill.physical2],
     []],
    ["00063", "Nuckelavee", "Skinless and black of blood, this elf of the sea spouts poison which spreads disease and wreaks ruin upon the land.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.merman, Attribute.poison,
     477, 532, 521, 473, 509, 534,
     [Skill.poison1, Skill.physical2, Skill.poison2],
     [Skill.poison1, Skill.physical2, Skill.poison2],
     []],
    ["00064", "Phantom Pirate", "This ghost of a heartless pirate sails cursed waters, chasing down its quarry with the fury of squall and storm.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.orbs, Attribute.death,
     527, 486, 518, 469, 485, 526,
     [Skill.death1, Skill.slash2, Skill.dwis20],
     [Skill.death1, Skill.slash2, Skill.dwis20],
     []],
    ["00065", "Peluda", "Dreaded for its breath of fire and acid, this dragon's vast vitality saw it through the great flood that ended nigh all life.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.serpent, Attribute.poison,
     558, 476, 531, 509, 473, 495,
     [Skill.poison1, Skill.physical2, Skill.atk10],
     [Skill.poison1, Skill.physical2, Skill.atk10],
     []],
    ["00066", "Suiko", "Though it harbors no hatred of man, this irascible denizen of lakes and rivers will sink its teeth into any who anger it.", 
     Event.none, Border.none, 1, Place.ocean, 0, null, Shape.shark, Attribute.darkness,
     482, 546, 482, 465, 492, 511,
     [Skill.physical1, Skill.darkness2, Skill.water2],
     [Skill.physical1, Skill.darkness2, Skill.water2],
     []],
    ["00067", "Visita Gun", "The final work of a crazed gunsmith, this firearm unleashes a wild barrage of bullets, but rarely finds its target.", 
     Event.weapons, Border.none, 1, Place.plains, 0, null, Shape.orbs, Attribute.none,
     510, 510, 570, 455, 530, 475,
     [Skill.physical1, Skill.physical2, Skill.sd],
     [Skill.physical1, Skill.physical2, Skill.sd],
     []],
    ["00068", "Interiora Claw", "The black soul of the killer who wore this cursed glove still resides within it, reveling in the screams of its victims.", 
     Event.weapons, Border.none, 1, Place.volcano, 0, null, Shape.orbs, Attribute.none,
     500, 520, 557, 488, 538, 445,
     [Skill.qs, Skill.slash1, Skill.slash2],
     [Skill.qs, Skill.slash1, Skill.slash2],
     []],
    ["00072", "Seductive Vapak", "", 
     Event.none, Border.none, 1, Place.quests, 0, null, Shape.humanoid, Attribute.poison,
     0, 0, 0, 0, 0, 0,
     [],
     [],
     []],
    ["00073", "Emerald Carbuncle", "", 
     Event.none, Border.none, 1, Place.quests, 0, null, Shape.orbs, Attribute.light,
     0, 0, 0, 0, 0, 0,
     [],
     [],
     []],
    ["00074", "Jabberwock", "Figments of the imagination sparked by an enigmatic poem are the magic that bring this eerie beast into being.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.dragon, Attribute.darkness,
     548, 515, 536, 502, 462, 491,
     [Skill.slash1, Skill.atk10, Skill.slash2],
     [Skill.slash1, Skill.atk10, Skill.slash2],
     []],
    ["00075", "Argus", "Dubbed the All-Seeing, this primordial giant has one hundred eyes and a gaze that permeates all of creation.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.orbs, Attribute.earth,
     560, 501, 496, 511, 498, 512,
     [Skill.dwis20, Skill.datk20, Skill.earth2],
     [Skill.dwis20, Skill.datk20, Skill.earth2],
     []],
    ["00076", "Gamigin", "Appearing as a spectral horse, this marquis of hell imparts the knowledge of the dead to the world's summoners.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.wolf, Attribute.death,
     491, 539, 501, 495, 496, 511,
     [Skill.wis10, Skill.darkness1, Skill.wis20],
     [Skill.wis10, Skill.darkness1, Skill.wis20],
     []],
    ["00077", "Vuokho", "Larger in size than the largest galley, this avian familiar pillages treasures from afar at its master's command.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.bird, Attribute.lightning,
     482, 536, 508, 496, 555, 528,
     [Skill.lightning1, Skill.agi10, Skill.lightning2],
     [Skill.lightning1, Skill.agi10, Skill.lightning2],
     []],
    ["00078", "Redcap", "This evil spirit soaks its hat in the fresh blood of any traveler fool enough to seek refuge within its cursed ruins.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.humanoid, Attribute.darkness,
     501, 488, 527, 489, 514, 487,
     [Skill.slash1, Skill.slash2, Skill.atk20],
     [Skill.slash1, Skill.slash2, Skill.atk20],
     []],
    ["00079", "Bodach", "Descending chimneys in the dark of night, this hideous faerie enters the dreams of children and haunts them.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.humanoid, Attribute.fire,
     519, 542, 498, 487, 480, 540,
     [Skill.dwis20, Skill.fire1, Skill.fire2],
     [Skill.dwis20, Skill.fire1, Skill.fire2],
     []],
    ["00080", "Al-mi'raj", "With its spiraling black horn, this lapine terror disembowels far larger beasts and consumes their flesh.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.wolf, Attribute.earth,
     544, 495, 541, 534, 528, 508,
     [Skill.slash1, Skill.agi10, Skill.slash2],
     [Skill.slash1, Skill.agi10, Skill.slash2],
     []],
    ["00081", "Sessho-seki", "The petrified corpse of a bewitching nine-tailed fox, this stone now emits a poison gas that kills any and all life.", 
     Event.none, Border.none, 1, Place.plains_night, 0, null, Shape.orbs, Attribute.poison,
     472, 563, 481, 530, 476, 514,
     [Skill.poison1, Skill.sd, Skill.mana],
     [Skill.poison1, Skill.sd, Skill.mana],
     []],
    ["00082", "Ravishing Elf", "", 
     Event.none, Border.none, 1, Place.quests, 0, null, Shape.humanoid, Attribute.light,
     0, 0, 0, 0, 0, 0,
     [],
     [],
     []],
    ["00083", "White Pawn", "Spurred on by the belief in a miracle across the battlefield, this minion lives only for the relentless charge forward.", 
     Event.chess, Border.none, 1, Place.plains, 0, null, Shape.humanoid, Attribute.death,
     458, 541, 492, 455, 478, 482,
     [Skill.death1, Skill.physical1, Skill.revival],
     [Skill.death1, Skill.physical1, Skill.revival],
     []],
    ["00084", "Chonchon", "", 
     Event.none, Border.none, 1, Place.quests, 0, null, Shape.orbs, Attribute.lightning,
     0, 0, 0, 0, 0, 0,
     [],
     [],
     []],
    ["00086", "Mushussu", "Serving only those worthy of its might, this mottled wyrm chose a new master at the dawning of the second age.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.bird, Attribute.poison,
     556, 518, 570, 543, 505, 524,
     [Skill.ddef20, Skill.slash1, Skill.slash2],
     [Skill.ddef20, Skill.slash1, Skill.slash2],
     []],
    ["00087", "Bunyip", "Awakened by the first raindrop of spring, this aqueous imp drags prey into rivers with its jagged claws.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.humanoid, Attribute.water,
     511, 520, 530, 584, 491, 508,
     [Skill.def20, Skill.physical1, Skill.physical2],
     [Skill.def20, Skill.physical1, Skill.physical2],
     []],
    ["00088", "Aspis", "This slight wyrm conceals a venom downed by ancient queens worsted in battle to pass beyond the veil.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.dragon, Attribute.poison,
     521, 521, 534, 523, 510, 519,
     [Skill.dwis20, Skill.dagi20, Skill.poison2],
     [Skill.dwis20, Skill.dagi20, Skill.poison2],
     []],
    ["00089", "Cath Palug", "Born to an ebony swine, this foul feline is said to terrorize kingdoms by decimating legions of knights.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.wolf, Attribute.lightning,
     479, 410, 489, 480, 595, 490,
     [Skill.slash1, Skill.ds, Skill.qs],
     [Skill.slash1, Skill.ds, Skill.qs],
     []],
    ["00090", "Knocker", "Shying away from the eyes of man, this shrewd spirit raps upon cavern walls to lead miners to rich veins of ore.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.humanoid, Attribute.earth,
     561, 476, 555, 543, 469, 480,
     [Skill.physical1, Skill.atk10, Skill.atk20],
     [Skill.physical1, Skill.atk10, Skill.atk20],
     []],
    ["00091", "Hizama", "Dreaded for setting men ablaze, this cursed fowl conceals itself in bottles and buckets strewn about the house.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.bird, Attribute.fire,
     496, 564, 484, 498, 545, 518,
     [Skill.fire1, Skill.fire2, Skill.wis20],
     [Skill.fire1, Skill.fire2, Skill.wis20],
     []],
    ["00092", "Cu Sith", "Dwelling deep in mountain fissures, this ghostly hound viciously guards the gates of the faerie court.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.wolf, Attribute.earth,
     543, 510, 518, 520, 531, 514,
     [Skill.physical1, Skill.agi10, Skill.physical2],
     [Skill.physical1, Skill.agi10, Skill.physical2],
     []],
    ["00093", "Xiuhtecuhtli", "The most ancient god, this fire-bringer lives on through the morsels of food ignited by villagers in his praise.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.orbs, Attribute.fire,
     561, 579, 528, 521, 479, 556,
     [Skill.fire1, Skill.wis20, Skill.ls],
     [Skill.fire1, Skill.wis20, Skill.ls],
     []],
    ["00094", "Boitata", "This fiery serpent dwells in ancient forests, eyes piercing the pall of night to keep watch over its ancestral home.", 
     Event.none, Border.none, 1, Place.volcano_night, 0, null, Shape.dragon, Attribute.fire,
     495, 534, 512, 499, 580, 534,
     [Skill.agi10, Skill.fire1, Skill.fire2],
     [Skill.agi10, Skill.fire1, Skill.fire2],
     []],
    ["00095", "Amber Jelly", "Deadliest of its kin, this fearsome predator captivates unsuspecting prey with a luminescent third eye.", 
     Event.stinging, Border.none, 1, Place.ocean, 0, null, Shape.jellyfish, Attribute.poison,
     499, 412, 511, 442, 454, 482,
     [Skill.dagi20, Skill.poison1, Skill.ddef20],
     [Skill.dagi20, Skill.poison1, Skill.ddef20],
     []],
    ["00096", "Furi", "This aerial creature climbs between treetops and crags, ensnaring birds from the canopy with curious grasses.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.wolf, Attribute.wind,
     481, 519, 503, 501, 519, 510,
     [Skill.physical1, Skill.physical2, Skill.revival],
     [Skill.physical1, Skill.physical2, Skill.revival],
     []],
    ["00097", "Al Rakim", "Mighty enough to repel a king's host, this canine kept watch over seven sleeping souls for two hundred years.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.wolf, Attribute.lightning,
     519, 530, 546, 520, 551, 524,
     [Skill.agi20, Skill.physical1, Skill.physical2],
     [Skill.agi20, Skill.physical1, Skill.physical2],
     []],
    ["00098", "Troll", "The sun's rays petrify these colossal brutes, and so strewn about their native lands are rocks resembling their kind.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.giant, Attribute.earth,
     564, 509, 566, 538, 520, 523,
     [Skill.physical1],
     [],
     []],
    ["00099", "Chamrosh", "Perched high within the tree of life, this divine bird shakes free the seeds which bring forth flora and fauna to the world.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.bird, Attribute.wind,
     550, 567, 501, 512, 520, 543,
     [Skill.dr, Skill.wind1, Skill.wind2],
     [Skill.dr, Skill.wind1, Skill.wind2],
     []],
    ["00100", "Taxim", "A husk driven by rancor alone, this vengeful zombie wanders the moonlit world searching for warm flesh.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.death,
     572, 540, 570, 554, 501, 507,
     [Skill.physical1, Skill.physical2, Skill.atk10],
     [Skill.physical1, Skill.physical2, Skill.atk10],
     []],
    ["00101", "Sluagh", "Rejected even by hell, this abominable phantasm flies with its brethren, descending on homes of the moribund.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.orbs, Attribute.death,
     519, 544, 517, 518, 550, 531,
     [Skill.darkness1, Skill.death1, Skill.darkness2],
     [Skill.darkness1, Skill.death1, Skill.darkness2],
     []],
    ["00102", "Stewa Rutu", "This vampiric monstrosity can drain victims' blood merely by caressing their shadows with its grotesque tentacles.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.orbs, Attribute.poison,
     531, 532, 538, 519, 512, 518,
     [Skill.life, Skill.poison2, Skill.mana],
     [Skill.life, Skill.poison2, Skill.mana],
     []],
    ["00103", "Lucifuge", "This dark servant of the gods despises light and cacophony, and abhors humans who disturb the still of night.", 
     Event.none, Border.none, 1, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.darkness,
     560, 528, 554, 549, 538, 550,
     [Skill.physical1, Skill.darkness2, Skill.atkwis10],
     [Skill.physical1, Skill.darkness2, Skill.atkwis10],
     []],
    /*
      ["00104", "Cocollona", "", // Main Quest 0003
      Event.none, Border.none, 1, Place.ocean, 0, null, Shape.orbs, Attribute.death,
      570, 517, 568, 574, 505, 511,
      [Skill.physical1],
      [],
      []],
      ["", "Mimetic Parandus", "", 
      Event.none, Border.none, 1, Place.quests, 0, null, Shape.wolf, Attribute.earth,
      440, 438, 480, 540, 454, 437,
      [Skill.dagi20],
      [],
      []],
      // wisdom not confirmed, skillset missing, profile missing
      */
    ["00105", "Zilant", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.zdragon, Attribute.poison,
     592, 531, 578, 542, 581, 572,
     [Skill.poison1, Skill.atkwis10, Skill.slash2],
     [Skill.poison1, Skill.atkwis10, Skill.slash2],
     []],
    ["00106", "Menehune", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.zhumanoid, Attribute.earth,
     533, 529, 611, 572, 538, 521,
     [Skill.physical1, Skill.atk20, Skill.physical2],
     [Skill.physical1, Skill.atk20, Skill.physical2],
     []],
    ["00107", "Ronove", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.zhumanoid, Attribute.darkness,
     590, 521, 553, 541, 572, 578,
     [Skill.dwis20, Skill.wis10, Skill.darkness2],
     [Skill.dwis20, Skill.wis10, Skill.darkness2],
     []],
    ["00108", "Muscaliet", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.pegasus, Attribute.fire,
     514, 552, 526, 516, 612, 543,
     [Skill.fire1, Skill.fire2, Skill.agi20],
     [Skill.fire1, Skill.fire2, Skill.agi20],
     []],
    ["00109", "Papinijuwari", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.zhumanoid, Attribute.darkness,
     617, 520, 588, 586, 513, 511,
     [Skill.physical1, Skill.physical2, Skill.atk20],
     [Skill.physical1, Skill.physical2, Skill.atk20],
     []],
    ["00110", "Xolotl", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.zdragon, Attribute.fire,
     535, 547, 544, 521, 568, 530,
     [Skill.fire1, Skill.physical1, Skill.fire2],
     [Skill.fire1, Skill.physical1, Skill.fire2],
     []],
    ["00111", "Ekek", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.zorbs, Attribute.wind,
     525, 534, 582, 524, 594, 525,
     [Skill.slash1, Skill.mana, Skill.life],
     [Skill.slash1, Skill.mana, Skill.life],
     []],
    ["00112", "Asag", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.zhumanoid, Attribute.earth,
     551, 533, 572, 596, 526, 548,
     [Skill.def20, Skill.slash1, Skill.ls],
     [Skill.def20, Skill.slash1, Skill.ls],
     []],
    ["00113", "Kanaloa", "", 
     Event.none, Border.none, 1, Place.zeus, 0, null, Shape.pegasus, Attribute.poison,
     609, 554, 523, 530, 499, 591,
     [Skill.poison1, Skill.wis10, Skill.poison2],
     [Skill.poison1, Skill.wis10, Skill.poison2],
     []],
    ["00116", "Rakshasa", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.humanoid, Attribute.lightning,
     590, 542, 576, 546, 561, 539,
     [Skill.lightning1, Skill.atk10, Skill.slash2],
     [Skill.lightning1, Skill.atk10, Skill.slash2],
     []],
    ["00117", "Xing Tian", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.giant, Attribute.death,
     604, 544, 530, 601, 562, 551,
     [Skill.earth1, Skill.agi10, Skill.physical1],
     [Skill.earth1, Skill.agi10, Skill.physical1],
     []],
    ["00118", "Night Sun Jaguar", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.wolf, Attribute.mecha,
     538, 554, 581, 553, 566, 511,
     [Skill.physical1, Skill.agi10, Skill.physical2],
     [Skill.physical1, Skill.agi10, Skill.physical2],
     []],
    ["00119", "Yaksha", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.humanoid, Attribute.earth,
     570, 544, 532, 564, 551, 555,
     [Skill.earth1, Skill.slash1, Skill.def10],
     [Skill.earth1, Skill.slash1, Skill.def10],
     []],
    ["00120", "Fandrefiala", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.dragon, Attribute.poison,
     562, 552, 542, 552, 571, 531,
     [Skill.slash1, Skill.agi10, Skill.slash2],
     [Skill.slash1, Skill.agi10, Skill.slash2],
     []],
    ["00121", "Humpty Dumpty", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.orbs, Attribute.light,
     565, 542, 554, 531, 541, 529,
     [Skill.physical1, Skill.atk10, Skill.physical2],
     [Skill.physical1, Skill.atk10, Skill.physical2],
     []],
    ["00122", "Nephilim", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.giant, Attribute.darkness,
     634, 532, 565, 591, 538, 523,
     [Skill.physical1, Skill.def10, Skill.physical2],
     [Skill.physical1, Skill.def10, Skill.physical2],
     []],
    ["00123", "Thoth", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.bird, Attribute.light,
     559, 590, 542, 544, 533, 534,
     [Skill.light1, Skill.wis10, Skill.def10],
     [Skill.light1, Skill.wis10, Skill.def10],
     []],
    ["00124", "Calydonian Boar", "", 
     Event.none, Border.none, 1, Place.desert_night, 0, null, Shape.wolf, Attribute.earth,
     594, 543, 560, 571, 538, 542,
     [Skill.physical1, Skill.agi10, Skill.physical2],
     [Skill.physical1, Skill.agi10, Skill.physical2],
     []],
    ["00125", "Kijimuna", "Often found hunting fish at sea, this tiny forest spirit eats only a single eyeball of its catch and leaves the rest to rot.", 
     Event.none, Border.none, 1, Place.ocean_night, 0, null, Shape.orbs, Attribute.fire,
     562, 552, 501, 570, 555, 609,
     [Skill.fire1],
     [],
     []],
    ["00126", "Dapeng", "This massive fish of the north sea made itself into a bird, and flies on storm winds for a celestial lake in the far east.", 
     Event.none, Border.none, 1, Place.ocean_night, 0, null, Shape.serpent, Attribute.wind,
     652, 499, 593, 592, 531, 489,
     [Skill.physical1],
     [],
     []],
    ["00127", "Sobek", "For gathering the corpses of fallen gods, this crocodile deity of a sacred river came to be called He Who Unites.", 
     Event.none, Border.none, 1, Place.ocean_night, 0, null, Shape.merman, Attribute.lightning,
     590, 623, 487, 560, 540, 600,
     [Skill.lightning1],
     [],
     []],
    ["00128", "Dou Shen", "This guardian in the skies descends as the plaguebringer's servant upon earth, bringing death by heavenly decree.", 
     Event.none, Border.none, 1, Place.ocean_night, 0, null, Shape.orbs, Attribute.poison,
     652, 483, 601, 540, 562, 521,
     [Skill.slash1],
     [],
     []]
]);

Card.addNotes({
    "00056": "Skillset not confirmed", // Amethyst Serpent
    "00057": "Skillset not confirmed", // Topaz Serpent
    "00067": "Skillset not confirmed", // Visita Gun
    "00068": "Skillset not confirmed", // Interiora Claw
    "00075": "Skillset not confirmed", // Argus
    "00076": "Skillset not confirmed", // Gamigin
    "00078": "Skillset not confirmed", // Redcap
    "00080": "Skillset not confirmed", // Al-mi'raj
    "00081": "Skillset not confirmed", // Sessho-seki
    "00086": "Skillset not confirmed",
    "00087": "Skillset not confirmed",
    "00088": "Skillset not confirmed",
    "00089": "Skillset not confirmed",
    "00090": "Skillset not confirmed",
    "00091": "Skillset not confirmed",
    "00092": "Skillset not confirmed",
    "00093": "Skillset not confirmed",
    "00094": "Skillset not confirmed",
    "00095": "Skillset not confirmed",  // Amber Jelly
    "00096": "Skills from Japanese version",
    "00097": "Skills from Japanese version",
    "00098": "Skills from Japanese version",
    "00099": "Skills from Japanese version",
    "00100": "Skills from Japanese version",
    "00101": "Skills from Japanese version",
    "00102": "Skills from Japanese version",
    "00103": "Skills from Japanese version",
    "00105": "All data from Japanese version",
    "00106": "All data from Japanese version",
    "00107": "All data from Japanese version",
    "00108": "All data from Japanese version",
    "00109": "All data from Japanese version",
    "00110": "All data from Japanese version",
    "00111": "All data from Japanese version",
    "00112": "All data from Japanese version",
    "00113": "All data from Japanese version",
    "00125": "Skills missing",
    "00126": "Skills missing",
    "00127": "Skills missing",
    "00128": "Skills missing"
});
