/*
 * Card:
 *   ID Name Description Event Border Stars Place Place2 Prototype Shape Attribute HP MP ATK DEF AGI WIS 
 *   Skills Recommends RecommendsRB
 */
Card.addAll([
    ["10001", "Cerberus", "This ferocious three-headed hound guards the gates hell, tearing apart any who attempt escape.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.wolf, Attribute.fire,
     600, 568, 637, 617, 568, 606,
     [Skill.fire1, Skill.darkness1, Skill.physical1, Skill.fire2],
     [Skill.darkness1, Skill.physical1, Skill.fire2],
     []],
    ["10002", "Minotaur", "This beast has a bull's head atop a man's body, and rends foes with its immense strength and greataxe.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.giant, Attribute.fire,
     665, 570, 680, 670, 632, 510,
     [Skill.slash1, Skill.physical2, Skill.slash2, Skill.ddef20],
     [Skill.physical2, Skill.slash2, Skill.ddef20],
     []],
    ["10003", "Kelpie", "This water faerie resembles a horse and allows mortals to mount it, yet it is nigh impossible to control.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.wolf, Attribute.water,
     584, 564, 618, 598, 571, 638,
     [Skill.physical1, Skill.water1, Skill.agi10, Skill.physical2],
     [Skill.water1, Skill.agi10, Skill.physical2],
     []],
    ["10004", "Scylla", "Though its torso appears human, this sea creature has six vicious serpentine beasts in place of legs.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.humanoid, Attribute.water,
     621, 530, 648, 628, 591, 626,
     [Skill.physical1, Skill.atk10, Skill.water2, Skill.physical2],
     [Skill.atk10, Skill.water2, Skill.physical2],
     []],
    ["10005", "Pegasus", "Sired by the sea god, this celestial horse bears large, feathered wings which grant it the gift of flight.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.wolf, Attribute.water,
     613, 659, 643, 550, 615, 620,
     [Skill.agi10, Skill.physical1, Skill.agi20, Skill.physical2],
     [Skill.agi10, Skill.agi20, Skill.physical2],
     []],
    ["10006", "Ogre", "What this cruel, man-eating monster lacks in intellect it makes up for with sheer mass and brute strength.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.giant, Attribute.earth,
     638, 621, 672, 652, 560, 512,
     [Skill.slash1, Skill.atk10, Skill.slash2, Skill.dagi20],
     [Skill.atk10, Skill.slash2, Skill.dagi20],
     []],
    ["10007", "Centaur", "Despite their warlike ways, some among these half-man half-horse beings are moral and devout souls.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.wolf, Attribute.earth,
     605, 570, 633, 595, 622, 634,
     [Skill.earth1, Skill.agi10, Skill.agi20, Skill.slash2],
     [Skill.agi10, Skill.agi20, Skill.slash2],
     []],
    ["10008", "Sandworm", "This monstrous worm burrows through the vast desert sands, surfacing only to swallow its prey.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.wolf, Attribute.earth,
     653, 618, 657, 637, 548, 554,
     [Skill.ddef20, Skill.atk10, Skill.physical2, Skill.dagi20],
     [Skill.ddef20, Skill.atk10, Skill.physical2],
     []],
    ["10009", "Thunderbird", "This lightning elemental hurls thunderbolts at will and is worshipped by some as a protector deity.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.bird, Attribute.lightning,
     652, 670, 660, 640, 640, 515,
     [Skill.agi10, Skill.lightning1, Skill.agi20, Skill.lightning2],
     [Skill.agi10, Skill.agi20, Skill.lightning2],
     []],
    ["10010", "Yurlungur", "This colossal snake appears as a rainbow binding heaven and earth, and its hiss sounds as thunder.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.dragon, Attribute.lightning,
     650, 597, 607, 587, 670, 559,
     [Skill.agi10, Skill.lightning1, Skill.lightning2, Skill.dagi20],
     [Skill.agi10, Skill.lightning2, Skill.dagi20],
     []],
    ["10011", "Griffin", "A fearsome beast that guards the gold of the gods by tooth and claw against any who attempt to steal it.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.wolf, Attribute.wind,
     662, 643, 677, 615, 655, 540,
     [Skill.slash1, Skill.atk10, Skill.atk20, Skill.slash2],
     [Skill.atk10, Skill.atk20, Skill.slash2],
     []],
    ["10012", "Harpy", "This creature of greed, whose name means \"she who snatches,\" attacks earthbound prey from above.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.bird, Attribute.wind,
     590, 512, 620, 615, 595, 645,
     [Skill.agi10, Skill.slash1, Skill.slash2, Skill.wind2],
     [Skill.agi10, Skill.slash2, Skill.wind2],
     []],
    ["10013", "Cockatrice", "The body of this monstrous creature is saturated with a poison which it spits to turn its victims to stone.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.dragon, Attribute.poison,
     610, 615, 563, 580, 590, 612,
     [Skill.poison1, Skill.datk20, Skill.poison2, Skill.slash2],
     [Skill.datk20, Skill.poison2, Skill.slash2],
     []],
    ["10014", "Banshee", "A spirit that appears beside the dying and sounds a blood-curdling cry to herald the coming of death.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.humanoid, Attribute.death,
     550, 636, 578, 582, 595, 615, 
     [Skill.darkness1, Skill.ddef20, Skill.darkness2, Skill.life],
     [Skill.darkness1, Skill.ddef20, Skill.darkness2],
     []],
    ["10015", "Wraith", "An evil, wandering spirit that seeks only to deprive mortals of life to make them its companions in death.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.orbs, Attribute.death,
     540, 664, 598, 552, 580, 628,
     [Skill.datk20, Skill.life, Skill.darkness2, Skill.mana],
     [Skill.datk20, Skill.life, Skill.darkness2],
     []],
    ["10016", "Spriggan", "A creation of antiquity, this mechanical faerie attacks any who draw near the treasures it guards.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.orbs, Attribute.mecha,
     580, 575, 565, 524, 510, 660,
     [Skill.atk10, Skill.agi10, Skill.physical2, Skill.def10],
     [Skill.atk10, Skill.agi10, Skill.physical2],
     []],
    ["10017", "Verethragna", "This avatar of the war god grants victory to worshippers and destroys all obstacles that lay before him.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.wolf, Attribute.light,
     558, 540, 610, 605, 558, 544,
     [Skill.light1, Skill.physical1, Skill.physical2, Skill.atk20],
     [Skill.physical1, Skill.physical2, Skill.atk20],
     []],
    ["10018", "Einherjar", "These spirits of slain heroes gather in the hall of the fallen, awaiting the final battle at the end of days.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.humanoid, Attribute.light,
     611, 522, 642, 622, 615, 541,
     [Skill.atk10, Skill.light1, Skill.physical2, Skill.def10],
     [Skill.atk10, Skill.physical2, Skill.def10],
     []],
    ["10019", "Dark Elf", "Choosing a life shrouded in darkness, these elves loathe other elvenkind and frequently war with them.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.humanoid, Attribute.darkness,
     519, 550, 606, 556, 568, 619,
     [Skill.darkness1, Skill.agi10, Skill.dagi20, Skill.darkness2],
     [Skill.agi10, Skill.dagi20, Skill.darkness2],
     []],
    ["10020", "Werewolf", "The lycanthrope appears a normal man, but his lupine form takes hold of him when the full moon rises.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.humanoid, Attribute.darkness,
     617, 556, 627, 607, 591, 569,
     [Skill.slash1, Skill.atk10, Skill.slash2, Skill.atk20],
     [Skill.atk10, Skill.slash2, Skill.atk20],
     []],
    ["10021", "Red Slime", "Magically imbued with fire, this mutated slime envelops its prey in a deadly wave of great heat.", 
     Event.none, Border.none, 2, Place.grounds, 0, null, Shape.slime, Attribute.fire,
     577, 570, 525, 610, 569, 554,
     [Skill.fire1, Skill.atk10, Skill.def10, Skill.fire2],
     [Skill.atk10, Skill.def10, Skill.fire2],
     []],
    ["10022", "Emerald Dragonling", "One of the six dragonlings, this creature's skill with a bow makes it loved by allies and feared by foes.", 
     Event.dragon, Border.none, 2, Place.plains, 0, null, Shape.dragon, Attribute.poison,
     611, 610, 639, 611, 613, 619,
     [Skill.poison1, Skill.atk10, Skill.atk20, Skill.poison2],
     [Skill.atk10, Skill.atk20, Skill.poison2],
     []],
    ["10023", "Sepia Dragonling", "One of the six dragonlings, this creature is nearly unstoppable when chargin with spear and shield.", 
     Event.dragon, Border.none, 2, Place.plains, 0, null, Shape.dragon, Attribute.fire,
     601, 597, 655, 679, 579, 590,
     [Skill.def10, Skill.fire1, Skill.atk10, Skill.fire2],
     [Skill.def10, Skill.atk10, Skill.fire2],
     []],
    ["10024", "Mighty Emerald Dragonling", "?", 
     Event.dragon, Border.none, 2, Place.volcano, 0, null, Shape.dragon, Attribute.poison,
     641, 630, 670, 641, 643, 649,
     [Skill.poison1, Skill.atk10, Skill.atk20, Skill.poison2],
     [Skill.atk10, Skill.atk20, Skill.poison2],
     []],
    ["10025", "Mighty Sepia Dragonling", "?", 
     Event.dragon, Border.none, 2, Place.volcano, 0, null, Shape.dragon, Attribute.fire,
     631, 630, 687, 712, 607, 619,
     [Skill.def10, Skill.fire1, Skill.atk10, Skill.fire2],
     [Skill.def10, Skill.atk10, Skill.fire2],
     []],
    ["10026", "Scarab", "Servant to the god of the dawn, this diving creature symbolizes the sun cycle, rebirth, and regeneration.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.bird, Attribute.light,
     552, 560, 546, 635, 646, 568,
     [Skill.light1, Skill.light2, Skill.slash2, Skill.revival],
     [Skill.light2, Skill.slash2, Skill.revival],
     []],
    ["10027", "Ammit", "This grotesque beast consumes the souls of those hell deems evil, that they shall never again be reborn.", 
     Event.none, Border.none, 2, Place.plains, 0, null, Shape.wolf, Attribute.darkness,
     666, 552, 690, 678, 570, 568,
     [Skill.darkness1, Skill.physical1, Skill.darkness2, Skill.darkness3],
     [Skill.physical1, Skill.darkness2, Skill.darkness3],
     []],
    ["10028", "Snow Maiden", "Formed of snow and given the breath of life, the ice in this maiden's heart can be melted only by love.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.humanoid, Attribute.water,
     610, 685, 570, 610, 677, 692,
     [Skill.wis10, Skill.datk20, Skill.water1, Skill.water2],
     [Skill.wis10, Skill.datk20, Skill.water2],
     []],
    ["10029", "Frost Slime", "This slime inhabits cold regions, camouflaging itself amid ice and snow to tkae its quarry unawares.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.slime, Attribute.water,
     678, 564, 624, 585, 550, 546,
     [Skill.water1, Skill.dagi20, Skill.ddef20, Skill.life],
     [Skill.water1, Skill.dagi20, Skill.ddef20],
     []],
    ["10030", "Illuyanka", "The might of this evil dragon brought it victory over the storm god in a battle for dominion over the seas.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.dragon, Attribute.water,
     696, 618, 648, 630, 548, 564,
     [Skill.water1, Skill.slash1, Skill.water2, Skill.slash2],
     [Skill.slash1, Skill.water2, Skill.slash2],
     []],
    ["10031", "Satyr", "Servant of the god of wine, this half-man half-goat loves drink, dance, music, trickery, and ecstasy.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.orbs, Attribute.earth,
     575, 585, 554, 548, 594, 650,
     [Skill.atk10, Skill.def10, Skill.wis10, Skill.agi10],
     [Skill.atk10, Skill.wis10, Skill.agi10],
     []],
    ["10032", "Amphisbaena", "This venomous dragon has a head at both ends, which grasp one another to form a perfect circle.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.dragon, Attribute.poison,
     696, 612, 630, 546, 654, 549,
     [Skill.poison1, Skill.slash1, Skill.slash2, Skill.poison2],
     [Skill.slash1, Skill.slash2, Skill.poison2],
     []],
    ["10033", "Wild Hunters", "This undead army rises on stormy nights, bringing with it war, plague, and myriad other calamities.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.wolf, Attribute.death,
     624, 642, 630, 552, 582, 618,
     [Skill.darkness1, Skill.datk20, Skill.ddef20, Skill.dagi20],
     [Skill.datk20, Skill.ddef20, Skill.dagi20],
     []],
    ["10034", "Garm", "Ward of the netherworld, this massive hound's howl will sound the onset of war at the end of days.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.wolf, Attribute.death,
     648, 558, 636, 582, 642, 558,
     [Skill.physical1, Skill.ddef20, Skill.datk20, Skill.physical2],
     [Skill.ddef20, Skill.datk20, Skill.physical2],
     []],
    ["10035", "Metal Predator", "Forged in ancient times, the metal fangs and claws of this war machine are far sharper than any beast's.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.wolf, Attribute.mecha,
     654, 552, 660, 624, 666, 547,
     [Skill.physical1, Skill.def10, Skill.agi10, Skill.physical2],
     [Skill.def10, Skill.agi10, Skill.physical2],
     []],
    ["10036", "Astwihad", "Unmatched as a minion of death, this demon ropes the necks of its victims before dragging them to hell.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.humanoid, Attribute.death,
     579, 556, 618, 616, 562, 548,
     [Skill.darkness1, Skill.darkness2, Skill.physical1, Skill.physical2],
     [Skill.darkness2, Skill.physical1, Skill.physical2],
     []],
    ["10037", "Yellow Pixie", "One of the seven pixies of good fortune. The enchanting smile it wears brings happiness to all around it.", 
     Event.pixie, Border.none, 2, Place.plains, 0, null, Shape.orbs, Attribute.light,
     663, 631, 603, 616, 589, 619, 
     [Skill.heal, Skill.light1, Skill.def10, Skill.light2],
     [Skill.light1, Skill.def10, Skill.light2],
     []],
    ["10038", "Red Pixie", "One of the seven pixies of good fortune. It is very loyal to its friends and has a strong sense of justice.", 
     Event.pixie, Border.none, 2, Place.volcano, 0, null, Shape.orbs, Attribute.fire,
     611, 610, 675, 611, 629, 595, 
     [Skill.fire1, Skill.physical1, Skill.slash1, Skill.fire2],
     [Skill.fire1, Skill.slash1, Skill.fire2],
     []],
    ["10039", "Purple Pixie", "One of the seven pixies of good fortune. Timid and craven, it rarely shows itself out in the open.", 
     Event.pixie, Border.none, 2, Place.snowfield, 0, null, Shape.orbs, Attribute.darkness,
     559, 590, 603, 690, 681, 619, 
     [Skill.poison1, Skill.physical2, Skill.agi10, Skill.poison2],
     [Skill.physical2, Skill.agi10, Skill.poison2],
     []],
    ["10040", "Aspidochelone", "The shell of this terror of sailors' tales looks as an island, beckoning to port vessels which the beast then destroys.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.wolf, Attribute.water,
     717, 557, 632, 705, 548, 587,
     [Skill.water1, Skill.water2, Skill.physical2, Skill.def20],
     [Skill.water2, Skill.physical2, Skill.def20],
     []],
    ["10041", "Ipiria", "This prismatic being awakes from its slumber in the swamp depths to bring the rains, and its very cry is the thunder.", 
     Event.none, Border.none, 2, Place.volcano, 0, null, Shape.wolf, Attribute.lightning,
     565, 613, 548, 615, 637, 613,
     [Skill.lightning1, Skill.dagi20, Skill.lightning2, Skill.water2],
     [Skill.dagi20, Skill.lightning2, Skill.water2],
     []],
    ["10042", "Scitalis", "With its mesmerizing colors, this serpent first hypnotizes its prey before striking and devouring it whole.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.dragon, Attribute.earth,
     603, 585, 569, 581, 631, 648,
     [Skill.dagi20, Skill.slash2, Skill.earth2, Skill.agi10],
     [Skill.dagi20, Skill.earth2, Skill.agi10],
     []],
    ["10043", "Taotie", "Sheer gluttony fuels this savage demon's voracious appetite, driving it to consume all it comes across.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.beast, Attribute.earth,
     649, 569, 681, 645, 611, 577,
     [Skill.earth1, Skill.earth2, Skill.atk10, Skill.physical2],
     [Skill.earth2, Skill.atk10, Skill.physical2],
     []],
    ["10044", "Adramelek", "Attendant to the Lord of Hell, the curses and hexes woven by this demon rival even those of his master.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.humanoid, Attribute.lightning,
     573, 674, 598, 586, 624, 666,
     [Skill.datk20, Skill.lightning2, Skill.dagi20, Skill.wis20],
     [Skill.lightning2, Skill.dagi20, Skill.wis20],
     []],
    ["10045", "Namarrgon", "Come seasons of rain, this elemental brings lightning by striking the clouds with its mighty stone axes.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.dragon, Attribute.lightning,
     671, 591, 671, 610, 629, 651,
     [Skill.lightning1, Skill.slash2, Skill.lightning2, Skill.qs],
     [Skill.slash2, Skill.lightning2, Skill.qs],
     []],
    ["10046", "Dust Devil", "This elemental travels upon great whirlwinds, uprooting anything in his path and claiming it for his own.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.humanoid, Attribute.wind,
     615, 598, 645, 569, 663, 569,
     [Skill.wind1, Skill.agi10, Skill.slash2, Skill.wind2],
     [Skill.agi10, Skill.slash2, Skill.wind2],
     []],
    ["10047", "Simurgh", "This divine lord of all birds speaks the speech of all mortals and possesses an untold, timeless wisdom.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.bird, Attribute.wind,
     605, 623, 622, 595, 649, 653,
     [Skill.wind1, Skill.slash2, Skill.wis20, Skill.wind2],
     [Skill.slash2, Skill.wis20, Skill.wind2],
     []],
    ["10048", "Serket", "This goddess of all desert life bearing poison is also healer to those stricken by her children's venoms.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.wolf, Attribute.poison,
     681, 565, 599, 671, 605, 595,
     [Skill.poison1, Skill.def10, Skill.poison2, Skill.slash2],
     [Skill.def10, Skill.poison2, Skill.slash2],
     []],
    ["10049", "Sandman", "The spirit of sleep holds in his bag sands that lure even the most steadfast of souls into deep slumber.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.humanoid, Attribute.darkness,
     595, 661, 586, 580, 567, 621,
     [Skill.dagi20, Skill.datk20, Skill.dwis20, Skill.darkness2],
     [Skill.dagi20, Skill.dwis20, Skill.darkness2],
     []],
    ["10050", "Garula", "The Queen of Hell sends these minions to capture mortal men and drag them back to her underworld.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.orbs, Attribute.death,
     615, 615, 651, 611, 595, 575,
     [Skill.death1, Skill.life, Skill.poison2, Skill.death2],
     [Skill.death1, Skill.poison2, Skill.death2],
     []],
    ["10051", "Peryton", "Outcast by the gods and its soul malformed, this beast preys on man as it seeks to reclaim its shadow.", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.bird, Attribute.death,
     619, 604, 623, 603, 650, 611,
     [Skill.darkness1, Skill.slash2, Skill.death2, Skill.sd],
     [Skill.slash2, Skill.death2, Skill.sd],
     []],
    ["10052", "Haggis", "It is said this highland beast of legend can be seen only by the light of a full moon, and only by the pure of heart.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.wolf, Attribute.earth,
     606, 640, 585, 580, 658, 600,
     [Skill.earth1, Skill.agi10, Skill.earth2, Skill.light2],
     [Skill.agi10, Skill.earth2, Skill.light2],
     []],
    ["10053", "Zairic", "This demon's sole purpose is to destroy those plants for which mortals have use and spread the seeds of the poisonous.", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.female, Attribute.poison,
     585, 665, 592, 612, 593, 669,
     [Skill.poison1, Skill.ddef20, Skill.dagi20, Skill.poison2],
     [Skill.ddef20, Skill.dagi20, Skill.poison2],
     []],
    ["10054", "Pearl Serpent", "This divine serpent of lustrous white commands the power to ward off calamity in all its myriad forms.", 
     Event.serpents, Border.none, 2, Place.plains, 0, null, Shape.dragon, Attribute.light,
     680, 590, 563, 690, 607, 624,
     [Skill.light1, Skill.slash1, Skill.heal, Skill.light2],
     [Skill.light1, Skill.slash1, Skill.light2],
     []],
    ["10055", "Blood Serpent", "This keeper of the sanguine stone best ows the lust for life, protects those in war, and staunches the flow of blood.", 
     Event.serpents, Border.none, 2, Place.desert, 0, null, Shape.dragon, Attribute.darkness,
     559, 690, 603, 633, 660, 619,
     [Skill.darkness1, Skill.datk20, Skill.slash2, Skill.darkness2],
     [Skill.datk20, Skill.slash2, Skill.darkness2],
     []],
    ["10056", "Bennu", "?", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.bird, Attribute.light,
     588, 648, 592, 584, 648, 612,
     [Skill.revival, Skill.light1, Skill.ddef20, Skill.heal],
     [Skill.revival, Skill.light1, Skill.ddef20],
     []],
    ["10057", "Taranushi", "?", 
     Event.none, Border.none, 2, Place.desert, 0, null, Shape.giant, Attribute.wind,
     671, 610, 622, 603, 699, 600,
     [Skill.wind1, Skill.physical1, Skill.wind2, Skill.dwis20],
     [Skill.wind1, Skill.wind2, Skill.dwis20],
     []],
    ["10058", "Antaeus", "So long as he remains upon the earth which bore him, this giant is endowed with a strength that knows no bounds.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.orbs, Attribute.earth,
     683, 583, 679, 634, 582, 597,
     [Skill.earth1, Skill.earth2, Skill.atk10, Skill.physical2],
     [Skill.earth2, Skill.atk10, Skill.physical2],
     []],
    ["10059", "Oannes", "Risen from the sea, in seven day's time this piscine sage bestowed unto man the wisdom needed to build civilization.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.mermaid, Attribute.water,
     604, 653, 608, 592, 643, 665,
     [Skill.water1, Skill.wis10, Skill.water2, Skill.dagi20],
     [Skill.wis10, Skill.water2, Skill.dagi20],
     []],
    ["10060", "Sea Serpent", "Feared by all who navigate the seas, this ferocious beast boasts size and strength enough to sink any vessel.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.serpent, Attribute.lightning,
     694, 578, 668, 639, 588, 567,
     [Skill.physical1, Skill.lightning1, Skill.physical2, Skill.lightning2],
     [Skill.physical1, Skill.physical2, Skill.lightning2],
     []],
    ["10061", "Nehebkau", "This warden of the underworld binds together aspects of departed souls to create undying spirits for the afterlife.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.shark, Attribute.death,
     619, 646, 599, 589, 633, 653,
     [Skill.physical1, Skill.death1, Skill.agi10, Skill.dagi20],
     [Skill.death1, Skill.agi10, Skill.dagi20],
     []],
    ["10062", "Buer", "As supreme ruler over all the firmament holds, this god is the fount of logic and philosophy, and can heal any infirmity.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.orbs, Attribute.wind,
     689, 587, 674, 629, 584, 586,
     [Skill.physical1, Skill.wind1, Skill.physical2, Skill.atk10],
     [Skill.wind1, Skill.physical2, Skill.atk10],
     []],
    ["10063", "Perun", "From his seat in the heavens, this god rains down claps of thunder and bolts of lightning to punish the sinful.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.merman, Attribute.lightning,
     649, 606, 651, 607, 598, 646,
     [Skill.lightning1, Skill.physical1, Skill.lightning2, Skill.ddef20],
     [Skill.physical1, Skill.lightning2, Skill.ddef20],
     []],
    ["10064", "Pele", "The enchanting visage of this goddess hides a fury that melts the earth and moves mountains to erupt in flame.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.orbs, Attribute.fire,
     593, 683, 594, 587, 637, 683,
     [Skill.fire1, Skill.wis10, Skill.fire2, Skill.dwis20],
     [Skill.wis10, Skill.fire2, Skill.dwis20],
     []],
    ["10065", "Botis", "Heralded as hell's wisest minion, this demon tells all things past and future, and mediates between friend and foe.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.merman, Attribute.poison,
     657, 596, 674, 686, 587, 593,
     [Skill.slash1, Skill.poison1, Skill.def10, Skill.slash2],
     [Skill.poison1, Skill.def10, Skill.slash2],
     []],
    ["10066", "Remora", "Once this fish's suckers find the hull of a ship, no amount of wind in her sails nor arms at her oars will move her.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.shark, Attribute.water,
     587, 658, 588, 585, 609, 651,
     [Skill.water1, Skill.datk20, Skill.dagi20, Skill.water2],
     [Skill.datk20, Skill.dagi20, Skill.water2],
     []],
    ["10067", "Terra Flail", "The gods smote the giant whoe once weilded this mace for his villaines, yet its bloodlust lives on beyond its master.", 
     Event.weapons, Border.none, 2, Place.snowfield, 0, null, Shape.orbs, Attribute.none,
     647, 689, 655, 558, 623, 587,
     [Skill.sd, Skill.physical1, Skill.atk10, Skill.physical2],
     [Skill.sd, Skill.atk10, Skill.physical2],
     []],
    ["10068", "Rectificando Axe", "This executioner's axe drinks malice from the blood of the guilty, imbuing it with a hate for all life that yet lives.", 
     Event.weapons, Border.none, 2, Place.desert, 0, null, Shape.orbs, Attribute.none,
     568, 670, 691, 568, 617, 579,
     [Skill.atk10, Skill.ddef20, Skill.atk20, Skill.slash2],
     [Skill.ddef20, Skill.atk20, Skill.slash2],
     []],
    ["10069", "Invenies Shield", "Any whose attacks fall upon this shield are damned by curses cast forth by a demon sealed within at its creation.", 
     Event.weapons, Border.none, 2, Place.ocean, 0, null, Shape.orbs, Attribute.none,
     680, 642, 587, 689, 555, 619,
     [Skill.earth1, Skill.def10, Skill.physical1, Skill.ls],
     [Skill.earth1, Skill.def10, Skill.ls],
     []],
    ["10072", "Gilded Scarab", "Servant to the god of the dawn, this diving creature symbolizes the sun cycle, rebirth, and regeneration.", 
     Event.none, Border.none, 2, Place.quests, 0, null, Shape.orbs, Attribute.light,
     552, 560, 546, 635, 646, 568,
     [Skill.light1, Skill.light2, Skill.slash2, Skill.revival],
     [Skill.light2, Skill.slash2, Skill.revival],
     []],
    ["10073", "Sea Sibyl", "In the ocean depths, beyond the sun's reach, this witch sacrifices live merfolk to procure new reagents for her magic.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.mermaid, Attribute.darkness,
     622, 691, 612, 591, 600, 610,
     [Skill.mana, Skill.darkness1, Skill.life, Skill.darkness2],
     [Skill.darkness1, Skill.life, Skill.darkness2],
     []],
    ["10074", "Sea Bishop", "Though this aquatic sentient keeps the same gods as man, he is nonetheless his sworn and perennial enemy.", 
     Event.none, Border.none, 2, Place.ocean, 0, null, Shape.merman, Attribute.light,
     644, 653, 607, 634, 643, 665,
     [Skill.heal, Skill.light1, Skill.light2, Skill.majorheal],
     [Skill.light1, Skill.light2, Skill.majorheal],
     []],
    ["10075", "Evolved Predator", "", 
     Event.none, Border.none, 2, Place.snowfield, 0, null, Shape.wolf, Attribute.mecha,
     654, 496, 660, 686, 666, 547,
     [Skill.physical1],
     [Skill.physical1],
     []],
    ["10076", "Hraesvelgr", "This iron eagle soars the far northern reaches of the heavenly realm and will descend only at the end of days.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.bird, Attribute.mecha,
     588, 592, 658, 704, 690, 599,
     [Skill.slash1, Skill.agi10, Skill.slash2, Skill.def20],
     [Skill.agi10, Skill.slash2, Skill.def20],
     []],
    ["10077", "Vine", "Powerful enough to destroy any wall, this lion-headed demoon is also smart enough to build an impenetrable one.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.giant, Attribute.fire,
     675, 601, 691, 630, 580, 622,
     [Skill.physical1, Skill.def10, Skill.atk20, Skill.physical2],
     [Skill.def10, Skill.atk20, Skill.physical2],
     []],
    ["10078", "Wight", "Possessing the corpse of a fallen ruler, this wicked spirit preys upon those who dare profane its royal tomb.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.humanoid, Attribute.death,
     674, 680, 603, 621, 596, 677,
     [Skill.physical1, Skill.ddef20, Skill.ep, Skill.darkness2],
     [Skill.ddef20, Skill.ep, Skill.darkness2],
     []],
    ["10079", "Yale", "Forged after a heraldic beast of myth, this caprine monster charges with its massive horns spinning wildly.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.wolf, Attribute.mecha,
     644, 606, 624, 687, 610, 601,
     [Skill.def10, Skill.def20, Skill.atkdef10, Skill.physical1],
     [Skill.def20, Skill.atkdef10, Skill.physical1],
     [Skill.def20, Skill.atkdef10, Skill.physical1]],
    ["10080", "Incubus", "Creeping into the dreams of women, this lesser demon spreads lies to win vicious and vindictive allies to his side.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.orbs, Attribute.darkness,
     624, 696, 630, 640, 621, 637,
     [Skill.darkness1, Skill.dwis20, Skill.darkness2, Skill.dagi20],
     [Skill.dwis20, Skill.darkness2, Skill.dagi20],
     []],
    ["10081", "Gllylus", "Man, Shape.bird, and tiger, the disfigured heads of this beast are at constant odds, preventing it from taking flight.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.bird, Attribute.lightning,
     652, 630, 642, 651, 622, 621,
     [Skill.physical1, Skill.lightning1, Skill.lightning2, Skill.physical2],
     [Skill.physical1, Skill.lightning2, Skill.physical2],
     []],
    ["10082", "Boreas", "Father to the goddess of snow, this shaggy-haired master of the cold north winds brings the biting winter frosts.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.giant, Attribute.wind,
     678, 603, 672, 660, 625, 634,
     [Skill.wis10, Skill.wind1, Skill.physical2, Skill.atk20],
     [Skill.wis10, Skill.physical2, Skill.atk20],
     []],
    ["10083", "Krsnik", "Taking on bestial form, this shaman stalks by night, hunting down the vampires that threaten his domain.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.humanoid, Attribute.light,
     634, 648, 604, 597, 604, 614,
     [Skill.light1],
     [],
     []],
    ["10084", "Necromancer", "Endlessly seeking corpses for her nefarious rites, this sorcereress uses the dark arts to reanimate the dead.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.female, Attribute.death,
     633, 689, 622, 644, 620, 698,
     [Skill.darkness1, Skill.dwis20, Skill.datk20, Skill.death1],
     [Skill.dwis20, Skill.datk20, Skill.death1],
     []],
    ["10085", "Orange Rook", "With its true strength unleashed by the freedom to range, this stalwart soldier shines in the final stages of war.", 
     Event.chess, Border.none, 2, Place.ocean, 0, null, Shape.merman, Attribute.earth,
     698, 614, 689, 691, 508, 560,
     [Skill.physical1],
     [Skill.physical1],
     []],
    ["10086", "Green Knight", "Bounding over enemy entrenchments, this cavalryman dominates the frontlines of battle from atop his steed.", 
     Event.chess, Border.none, 2, Place.volcano, 0, null, Shape.humanoid, Attribute.wind,
     542, 601, 620, 570, 674, 603,
     [Skill.slash1, Skill.agi10, Skill.qs, Skill.ds],
     [Skill.slash1, Skill.qs, Skill.ds],
     []],
    ["10087", "Blue Bishop", "Even after heavy losses, this warrior priest, empowered by faith, halts his enemy's advance with fiery sermons.", 
     Event.chess, Border.none, 2, Place.snowfield, 0, null, Shape.humanoid, Attribute.water,
     621, 633, 596, 610, 592, 698,
     [Skill.water1, Skill.wis10, Skill.defwis10, Skill.water2],
     [Skill.wis10, Skill.defwis10, Skill.water2],
     []],
    /*
      ["10088", "Sanguine Serket", "", 
      Event.none, Border.none, 2, ?, 0, null, , Attribute.poison,
      
      [],
      [],
      []],
      ["10089", "Frost Slime", "", 
      Event.none, Border.none, 2, ?, 0, null, , Attribute.water,
      
      [],
      [],
      []],
    */
    ["10090", "Takuhi", "With a fearsome human visage, this demonic fowl's plumage is said to be a warding amulet against lightning.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.bird, Attribute.lightning,
     643, 645, 621, 638, 683, 620,
     [Skill.agi20, Skill.physical1, Skill.lightning2, Skill.dagi20],
     [Skill.agi20, Skill.lightning2, Skill.dagi20],
     []],
    ["10091", "Ovinnik", "Hurled from heaven for rebelling against the gods, this ghostly feline delights in setting granaries ablaze.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.wolf, Attribute.fire,
     610, 648, 610, 649, 710, 669,
     [Skill.atk20, Skill.physical1, Skill.physical2, Skill.fire2],
     [Skill.atk20, Skill.physical2, Skill.fire2],
     []],
    ["10092", "Mafdet", "The insignia of ancient kings, crumbling murals of this arcane beast in chains signified the fall of empires.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.wolf, Attribute.earth,
     612, 630, 707, 631, 635, 611,
     [Skill.qs, Skill.physical1, Skill.physical2, Skill.atk20],
     [Skill.qs, Skill.physical2, Skill.atk20],
     []],
    ["10093", "Kusarikku", "Once defender of hearth and home, this demonic bovine was drawn to the ocean and defeated by the sea deity.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.beast, Attribute.wind,
     738, 637, 636, 654, 636, 618,
     [Skill.wind1, Skill.def20, Skill.wind2, Skill.atkwis10],
     [Skill.def20, Skill.wind2, Skill.atkwis10],
     []],
    ["10094", "Galatea", "The love borne this ivory beauty by the madman who carved her was such that it imbued her with the breath of life.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.orbs, Attribute.mecha,
     628, 640, 639, 672, 629, 622,
     [Skill.physical1, Skill.physical2, Skill.atkwis10, Skill.defagi10],
     [Skill.physical2, Skill.atkwis10, Skill.defagi10],
     []],
    ["10095", "Xiezhi", "This just creature appears at the heart of disputes, and gestures unerringly to those with whom the guilt lies.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.wolf, Attribute.light,
     660, 710, 672, 630, 650, 649,
     [Skill.ep, Skill.atk10, Skill.light2, Skill.physical2],
     [Skill.ep, Skill.atk10, Skill.physical2],
     []],
    ["10096", "Kapre", "Confounding man's sense of direction, this puckish ogre can make a person feel hopelessly lost in his own garden.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.giant, Attribute.fire,
     721, 620, 730, 681, 600, 622,
     [Skill.ls, Skill.physical1, Skill.atk10, Skill.physical2],
     [Skill.ls, Skill.atk10, Skill.physical2],
     []],
    ["10097", "Orang Minyak", "His pores forever oozing oil, this cursed man slips from house to house, wreaking his evil wreathed in darkness.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.humanoid, Attribute.darkness,
     638, 621, 666, 655, 631, 660,
     [Skill.datk20, Skill.dwis20, Skill.darkness2, Skill.dagi20],
     [Skill.dwis20, Skill.darkness2, Skill.dagi20],
     []],
    ["10098", "Huay Chivo", "This necromancer transfigures himself into the ghostly form of a buck to slake his thirst for the blood of livestock.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.wolf, Attribute.darkness,
     650, 649, 651, 638, 640, 681,
     [Skill.darkness1, Skill.dwis20, Skill.dagi20, Skill.darkness2],
     [Skill.dwis20, Skill.dagi20, Skill.darkness2],
     []],
    ["10099", "Rampaging Yale", "Forged after a heraldic beast of myth, this caprine monster charges with its massive horns spinning wildly.", 
     Event.none, Border.none, 2, Place.plains_night, 0, null, Shape.wolf, Attribute.mecha,
     644, 606, 624, 687, 610, 601,
     [Skill.def10, Skill.def20, Skill.atkdef10, Skill.physical1],
     [Skill.def20, Skill.atkdef10, Skill.physical1],
     [Skill.def20, Skill.atkdef10, Skill.physical1]],
    ["10100", "Turquoise Jelly", "", 
     Event.stinging, Border.none, 2, Place.ocean, 0, null, Shape.jellyfish, Attribute.poison,
     661, 580, 643, 580, 575, 588,
     [Skill.dagi20, Skill.ddef20, Skill.poison2, Skill.datk20],
     [Skill.dagi20, Skill.poison2, Skill.datk20],
     []],
    /*
      ["10101", "Illusionist Adramelek", "", 
      Event.none, Border.none, 2, Place.quests, 0, null, Shape.humanoid, Attribute.lightning,
      0, 0, 0, 0, 0, 0,
      [],
      [],
      []],
    */
    ["10102", "Melancholy Pele", "The enchanting visage of this goddess hides a fury that melts the earth and moves mountains to erupt in flame.", 
     Event.none, Border.none, 2, Place.quests, 0, null, Shape.orbs, Attribute.fire,
     593, 683, 594, 587, 637, 683,
     [Skill.fire1, Skill.wis10, Skill.fire2, Skill.dwis20],
     [Skill.wis10, Skill.fire2, Skill.dwis20],
     []],
    ["10103", "Leshy", "This guardian spirit of woodlands is known to seal pacts with humanity, watching over their livestock at pasture.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.beast, Attribute.earth,
     673, 682, 659, 668, 648, 666,
     [Skill.physical1, Skill.ddef20, Skill.dwis20, Skill.earth2],
     [Skill.ddef20, Skill.dwis20, Skill.earth2],
     []],
    ["10104", "Shutu", "Symbolic of southern winds, this vexing god inflicts malady upon those who refuse to stand in awe of his power.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.wind,
     633, 660, 638, 640, 702, 678,
     [Skill.wind1, Skill.slash1, Skill.wind2, Skill.slash2],
     [Skill.wind1, Skill.wind2, Skill.slash2],
     []],
    ["10105", "Chiron", "This wisest of centaurs mentored youthful heroes in the divine techniques gifted him by the gods.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.wolf, Attribute.earth,
     662, 672, 684, 640, 661, 688,
     [Skill.heal, Skill.slash2, Skill.majorheal, Skill.earth2],
     [Skill.slash2, Skill.majorheal, Skill.earth2],
     []],
    ["10106", "Kudlak", "This vampire's nightly attacks on its birthplace are repelled by hunters, and the war reges on without victor.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.death,
     642, 670, 640, 654, 648, 670,
     [Skill.curse, Skill.life, Skill.mana, Skill.poison2],
     [Skill.curse, Skill.life, Skill.poison2],
     []],
    ["10107", "Vidofnir", "Ward of the World Tree, this golden chanticleer shines bright as lightning to summon the dawn with its crow.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.bird, Attribute.light,
     662, 641, 650, 718, 639, 649,
     [Skill.def10, Skill.slash1, Skill.slash2, Skill.def20],
     [Skill.def10, Skill.slash2, Skill.def20],
     []],
    ["10108", "Naglfar", "Built from the finger and toenails of the dead, this ship bears an army of giants and undead to storm heaven's shores.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.orbs, Attribute.mecha,
     735, 649, 701, 707, 588, 600,
     [Skill.slash1, Skill.def10, Skill.slash2, Skill.atk10],
     [Skill.def10, Skill.slash2, Skill.atk10],
     []],
    ["10109", "Kveldulf", "Once standing defiant against a king, this shapeshifting warrior's lupine blood awakes as twilight draws near.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.beast, Attribute.darkness,
     698, 632, 680, 672, 580, 611,
     [Skill.physical1, Skill.physical2, Skill.atkdef10, Skill.ls],
     [Skill.physical2, Skill.atkdef10, Skill.ls],
     []],
    ["10110", "Scathach", "Eager pupils surround this renowned warrior's fortress of shadows, begging her tutelage in the ways of war.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.female, Attribute.darkness,
     660, 651, 647, 650, 662, 650,
     [Skill.darkness1, Skill.physical1, Skill.atk20, Skill.wis20],
     [Skill.darkness1, Skill.atk20, Skill.wis20],
     []],
    ["10111", "Rubezahl", "This chieftain of the mountain sprites strums his storm harp to conjure fog, Attribute.lightning, rain, and snow.", 
     Event.none, Border.none, 2, Place.snowfield_night, 0, null, Shape.female, Attribute.earth,
     658, 694, 653, 668, 649, 708,
     [Skill.earth1, Skill.wis10, Skill.wind2, Skill.earth2],
     [Skill.wis10, Skill.wind2, Skill.earth2],
     []],
    ["10113", "Howlin' Prowlin Lollipop", "Concocted by a deranged artisan, this candy satiates the greatest craving for sweets, but causes teeth to rot.", 
     Event.sweet_nightmare, Border.none, 2, Place.plains_night, 0, null, Shape.pumpkin, Attribute.darkness,
     554, 632, 568, 577, 612, 623,
     [Skill.darkness1, Skill.dwis20, Skill.dagi20, Skill.curse],
     [Skill.dwis20, Skill.dagi20, Skill.curse],
     []],
    ["10114", "Creepy Crawly Cookie", "While crispy to perfection, this pastry handcrafted by a wicked hag causes even the thinnest man to grow obese.", 
     Event.sweet_nightmare, Border.none, 2, Place.plains_night, 0, null, Shape.pumpkin, Attribute.darkness,
     630, 598, 618, 642, 576, 572,
     [Skill.physical1, Skill.ddef20, Skill.datk20, Skill.dagi20],
     [Skill.ddef20, Skill.datk20, Skill.dagi20],
     []],
    ["10115", "Moko Kakariki", "This mountain demon's call sounds as an evil laughter, and is feared for the ill fortune it visits upon those who hear it.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.wolf, Attribute.poison,
     648, 675, 638, 656, 727, 652,
     [Skill.physical1, Skill.poison1, Skill.qs, Skill.physical2],
     [Skill.poison1, Skill.qs, Skill.physical2],
     []],
    ["10116", "Mapinguari", "The talons of this beast can fell the stoutest trees, and no projectile of man can penetrate its thick, bristly hide.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.wolf, Attribute.earth,
     696, 655, 693, 704, 646, 662,
     [Skill.slash1, Skill.slash2, Skill.atk20, Skill.ls],
     [Skill.slash2, Skill.atk20, Skill.ls],
     []],
    ["10117", "Tamamo no Mae", "In the form of a lovely courtesan, this nine-tailed fox caused the fall of many empires before fleeing to a distant isle.", 
     Event.none, Border.none, 2, Place.volcano_night, 0, null, Shape.female, Attribute.poison,
     664, 685, 662, 665, 663, 687,
     [Skill.datk20, Skill.poison1, Skill.poison2, Skill.dagi20],
     [Skill.datk20, Skill.poison2, Skill.dagi20],
     []],
    ["10118", "Mushnahhu", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zdragon, Attribute.poison,
     650, 699, 666, 659, 697, 651,
     [Skill.physical1, Skill.datk20, Skill.ddef20, Skill.poison2],
     [Skill.datk20, Skill.ddef20, Skill.poison2],
     []],
    ["10119", "Myrmidon", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zhumanoid, Attribute.earth,
     713, 666, 691, 727, 662, 655,
     [Skill.atk10, Skill.slash1, Skill.def20, Skill.slash2],
     [Skill.atk10, Skill.def20, Skill.slash2],
     []],
    ["10120", "Mammon", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zhumanoid, Attribute.poison,
     682, 702, 677, 676, 677, 688,
     [Skill.mana, Skill.ddef20, Skill.life, Skill.dagi20],
     [Skill.ddef20, Skill.life, Skill.dagi20],
     []],
    ["10121", "Turul", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zorbs, Attribute.fire,
     655, 651, 662, 660, 752, 653,
     [Skill.slash1, Skill.fire2, Skill.agi10, Skill.slash2],
     [Skill.fire2, Skill.agi10, Skill.slash2],
     []],
    ["10122", "Supay", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zhumanoid, Attribute.death,
     628, 789, 655, 640, 700, 731,
     [Skill.physical1, Skill.sd, Skill.death1, Skill.darkness2],
     [Skill.sd, Skill.death1, Skill.darkness2],
     []],
    ["10123", "Beast of Terror", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zorbs, Attribute.death,
     630, 661, 713, 679, 710, 670,
     [Skill.agi10, Skill.slash1, Skill.slash2, Skill.atkagi10],
     [Skill.agi10, Skill.slash2, Skill.atkagi10],
     []],
    ["10124", "Coiste Bodhar", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.pegasus, Attribute.death,
     717, 638, 672, 682, 731, 653,
     [Skill.darkness1, Skill.curse, Skill.physical2, Skill.darkness2],
     [Skill.curse, Skill.physical2, Skill.darkness2],
     []],
    ["10125", "Cecrops", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zhumanoid, Attribute.earth,
     682, 722, 639, 640, 729, 761,
     [Skill.earth1, Skill.earth2, Skill.wis10, Skill.wis20],
     [Skill.earth2, Skill.wis10, Skill.wis20],
     []],
    ["10126", "Kadaklan", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zhumanoid, Attribute.lightning,
     665, 709, 656, 657, 652, 715,
     [Skill.slash1, Skill.ls, Skill.lightning1, Skill.lightning2],
     [Skill.slash1, Skill.ls, Skill.lightning2],
     []],
    ["10127", "Indrajit", "", 
     Event.none, Border.none, 2, Place.zeus, 0, null, Shape.zorbs, Attribute.lightning,
     722, 644, 709, 661, 694, 693,
     [Skill.lightning1, Skill.slash1, Skill.lightning2, Skill.slash2],
     [Skill.slash1, Skill.lightning2, Skill.slash2],
     []],
    ["10130", "Chi You", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.wolf, Attribute.fire,
     685, 670, 705, 705, 730, 675,
     [Skill.fire1, Skill.atkwis10, Skill.slash1, Skill.fire2],
     [Skill.atkwis10, Skill.slash1, Skill.fire2],
     []],
    ["10131", "Baku", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.wolf, Attribute.darkness,
     690, 650, 679, 688, 685, 659,
     [Skill.physical1, Skill.ddef20, Skill.physical2, Skill.datk20],
     [Skill.ddef20, Skill.physical2, Skill.datk20],
     []],
    ["10132", "Wag-by-the-Way", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.wolf, Attribute.wind,
     685, 710, 651, 654, 706, 732,
     [Skill.wind1, Skill.wis20, Skill.wind2, Skill.atkwis10],
     [Skill.wis20, Skill.wind2, Skill.atkwis10],
     []],
    ["10133", "Foras", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.humanoid, Attribute.poison,
     727, 663, 722, 720, 671, 690,
     [Skill.slash1, Skill.atk10, Skill.ddef20, Skill.slash2],
     [Skill.atk10, Skill.ddef20, Skill.slash2],
     []],
    ["10134", "Haagenti", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.wolf, Attribute.mecha,
     751, 672, 732, 723, 690, 653,
     [Skill.physical1, Skill.atk10, Skill.physical2, Skill.atkagi10],
     [Skill.atk10, Skill.physical2, Skill.atkagi10],
     []],
    ["10135", "Nergal", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.giant, Attribute.death,
     671, 671, 742, 715, 670, 687,
     [Skill.death1, Skill.slash1, Skill.ddef20, Skill.slash2],
     [Skill.death1, Skill.ddef20, Skill.slash2],
     []],
    ["10136", "Namtar", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.humanoid, Attribute.darkness,
     691, 685, 701, 673, 702, 659,
     [Skill.def10, Skill.def20, Skill.atkdef10, Skill.physical1],
     [Skill.def20, Skill.atkdef10, Skill.physical1],
     []],
    ["10137", "Naamah", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.female, Attribute.darkness,
     653, 700, 653, 673, 678, 743,
     [Skill.darkness1, Skill.dwis20, Skill.ep, Skill.darkness2],
     [Skill.dwis20, Skill.ep, Skill.darkness2],
     []],
    ["10138", "Tangata Manu", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.bird, Attribute.wind,
     725, 650, 731, 680, 672, 653,
     [Skill.physical1, Skill.def10, Skill.atk20, Skill.physical2],
     [Skill.def10, Skill.atk20, Skill.physical2],
     []],
    ["10139", "Shax", "", 
     Event.none, Border.none, 2, Place.desert_night, 0, null, Shape.bird, Attribute.wind,
     651, 642, 703, 659, 740, 754,
     [Skill.wind1, Skill.agi10, Skill.wind2, Skill.agi20],
     [Skill.agi10, Skill.wind2, Skill.agi20],
     []],
    ["10140", "Eishou", "Gold, pearls, cinnabar, and more of alchemy's treasures are created by this bestial keeper of the celestial garden.", 
     Event.none, Border.none, 2, Place.ocean_night, 0, null, Shape.orbs, Attribute.wind,
     700, 688, 681, 709, 700, 695,
     [Skill.wind1],
     [],
     []],
    ["10141", "Sahagin", "These aquatic monsters live in water both above and below the earth, and are perennial enemies of man.", 
     Event.none, Border.none, 2, Place.ocean_night, 0, null, Shape.shark, Attribute.water,
     712, 677, 712, 672, 701, 690,
     [Skill.atk10],
     [],
     []],
    ["10142", "Ayakashi", "An ominous flame burns within this mystical serpent of the western seas, and excretions of foul oil coat its scales.", 
     Event.none, Border.none, 2, Place.ocean_night, 0, null, Shape.serpent, Attribute.fire,
     701, 699, 704, 689, 690, 692,
     [Skill.water1],
     [],
     []],
    ["10143", "Ogani", "Together with Hydra, this demon crab and spawn of the Mother of All Monsters stands guard at the netherworld's gates.", 
     Event.none, Border.none, 2, Place.ocean_night, 0, null, Shape.shark, Attribute.earth,
     741, 682, 722, 722, 666, 645,
     [Skill.slash1],
     [],
     []],
    ["10144", "Andrealphus", "Answering summons in peacock form, this great marquis of hell turns mortals to birds in exchange for proper sacrifice.", 
     Event.none, Border.none, 2, Place.ocean_night, 0, null, Shape.mermaid, Attribute.lightning,
     707, 732, 689, 671, 699, 722,
     [Skill.lightning1],
     [],
     []],
    ["10145", "Chrysaor", "This young king of the far west was born with gold sword in hand from seawater tainted by a drop of Gorgon blood.", 
     Event.none, Border.none, 2, Place.ocean_night, 0, null, Shape.merman, Attribute.water,
     703, 693, 732, 685, 699, 670,
     [Skill.slash1],
     [],
     []]
]);

Card.addNotes({
    "10054": "Skillset not confirmed", // Pearl Serpent
    "10055": "Skillset not confirmed", // Blood Serpent
    "10067": "Skillset not confirmed", // Terra Flail
    "10068": "Skillset not confirmed", // Rectificando Axe
    "10069": "Skillset not confirmed", // Invenies Shield
    "10074": "Skillset not confirmed",
    "10075": "All from Jap version. Profile missing",        // Enhanced Predator
    "10076": "Skills from Japanese version",        // Hraesvelgr
    "10077": "Skills from Japanese version",        // Vine
    "10078": "Skillset not conformed",  // Wight
    "10079": "Skills from Japanese version",        // Yale
    "10080": "Skills from Japanese version",        // Incubus
    "10081": "Skills from Japanese version",        // Gllylus
    "10082": "Skills from Japanese version",        // Boreas
    "10083": "Skillset missing",        // Krsnik
    "10084": "Skills from Japanese version",        // Necromancer
    "10085": "Skillset not confirmed",  // Orange Rook
    "10086": "Skillset not confirmed",  // Green Knight
    "10087": "All from Jap version",    // Blue Bishop
    "10090": "Skillset not confirmed",
    "10091": "Skillset not confirmed",
    "10092": "Skillset not confirmed",
    "10093": "Skillset not confirmed",
    "10094": "Skillset not confirmed",
    "10095": "Skillset not confirmed",
    "10096": "Skillset not confirmed",
    "10097": "Skillset not confirmed",
    "10098": "Skillset not confirmed",
    "10099": "Skills from Japanese version",        // Rampaging Yale
    "10100": "Skillset not confirmed",   // Turquoise Jelly
    "10103": "Skills from Japanese version",   // Leshy
    "10104": "Skills from Japanese version",
    "10105": "Skills from Japanese version",   // Chiron
    "10106": "Skills from Japanese version",
    "10107": "Skills from Japanese version",   // Vidofnir
    "10108": "Skills from Japanese version",   // Naglfar
    "10109": "Skills from Japanese version",
    "10110": "Skills from Japanese version",
    "10111": "Skills from Japanese version",   // Rubezahl
    "10113": "Skills from Japanese version", // Howlin' Prowlin Lollipop
    "10114": "Skills from Japanese version",  // Creepy Crawly Cookie
    "10115": "Skills from Japanese version",
    "10116": "Skills from Japanese version",
    "10117": "Skills from Japanese version",
    "10118": "All data from Japanese version",
    "10119": "All data from Japanese version",
    "10120": "All data from Japanese version",
    "10121": "All data from Japanese version",
    "10122": "All data from Japanese version",
    "10123": "All data from Japanese version",
    "10124": "All data from Japanese version",
    "10125": "All data from Japanese version",
    "10126": "All data from Japanese version",
    "10127": "All data from Japanese version",
    "10130": "All data from Japanese version",
    "10131": "All data from Japanese version",
    "10132": "All data from Japanese version",
    "10133": "All data from Japanese version",
    "10134": "All data from Japanese version",
    "10135": "All data from Japanese version",
    "10136": "All data from Japanese version",
    "10137": "All data from Japanese version",
    "10138": "All data from Japanese version",
    "10139": "All data from Japanese version",
    "10140": "Skills missing",
    "10141": "Skills missing",
    "10142": "Skills missing",
    "10143": "Skills missing",
    "10144": "Skills missing",
    "10145": "Skills missing"
});
