/*
 * Card:
 *   ID Name Description Event Border Stars Place Place2 Prototype Shape Attribute HP MP ATK DEF AGI WIS 
 *   Skills Recommends RecommendsRB
 */
Card.addAll([
    ["20001", "Vrtra", "This evil serpent born of fire brings drought by damming the celestial river with its massive body.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.dragon, Attribute.fire,
     751, 703, 711, 660, 727, 719, 
     [Skill.physical1, Skill.datk20, Skill.physical2, Skill.ddef20, Skill.physical3],
     [Skill.datk20, Skill.ddef20, Skill.physical3],
     []],
    ["20002", "Chimera", "A horrific fusion of varied bestial parts, this fire-breathing abomination rains terror upon the world of man.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.wolf, Attribute.fire,
     790, 808, 790, 795, 620, 712,
     [Skill.fire1, Skill.physical2, Skill.fire2, Skill.dagi20, Skill.fire3],
     [Skill.physical2, Skill.dagi20, Skill.fire3],
     []],
    ["20003", "Lindworm", "A flightless dragon that in place of wings has a body of such mass it sends tremors through the earth.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.wolf, Attribute.fire,
     756, 676, 679, 715, 790, 682, 
     [Skill.atk10, Skill.fire2, Skill.atk20, Skill.def20, Skill.physical3],
     [Skill.atk10, Skill.atk20, Skill.physical3],
     []],
    ["20004", "Naga", "A serpent spirit of immortality and rebirth that possesses a great vitality and the power to bring rain.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.dragon, Attribute.water,
     810, 756, 704, 719, 678, 739,
     [Skill.water1, Skill.heal, Skill.def10, Skill.water2, Skill.revival],
     [Skill.def10, Skill.water2, Skill.revival],
     []],
    ["20005", "Hydra", "A water serpent with nine heads that regenerate when severed, the central of which is deathless.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.dragon, Attribute.water,
     748, 708, 744, 754, 721, 728,
     [Skill.physical1, Skill.def10, Skill.def20, Skill.physical2, Skill.revival],
     [Skill.def20, Skill.physical2, Skill.revival],
     []],
    ["20007", "Cernunnos", "Known as the lord of all beasts, this primeval being is ever attended by a retinue of myriad creatures.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.wolf, Attribute.earth,
     682, 760, 730, 767, 628, 745, 
     [Skill.atk20, Skill.physical1, Skill.physical2, Skill.dwis20, Skill.physical3],
     [Skill.atk20, Skill.dwis20, Skill.physical3],
     []],
    ["20008", "Humbaba", "This spirit warden holds vigil over the sacred forest with a booming roar and breath of fire and poison.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.giant, Attribute.earth,
     632, 732, 682, 683, 688, 691, 
     [Skill.water1, Skill.fire1, Skill.water2, Skill.poison1, Skill.water3],
     [Skill.water2, Skill.poison1, Skill.water3],
     []],
    ["20009", "Cyclops", "Known for its single eye and smithery skills, this giant demigod fought in the war of the old and new gods.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.giant, Attribute.lightning,
     708, 645, 705, 715, 675, 672,
     [Skill.physical1, Skill.def20, Skill.physical2, Skill.atk20, Skill.physical3],
     [Skill.def20, Skill.atk20, Skill.physical3],
     []],
    ["20010", "Nue", "Gifted with a great power over thunder, this beast is said to bring a curse upon the land where it is slain.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.wolf, Attribute.lightning,
     696, 736, 708, 702, 745, 710,
     [Skill.lightning1, Skill.dagi20, Skill.dwis20, Skill.ddef20, Skill.lightning2],
     [Skill.dagi20, Skill.dwis20, Skill.ddef20],
     []],
    ["20011", "Furfur", "This great earl of hell and bringer of storms tries to deceive those mortals fool enough to summon him.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.wolf, Attribute.lightning,
     728, 760, 754, 705, 718, 742,
     [Skill.lightning1, Skill.wind1, Skill.agi10, Skill.lightning2, Skill.mana],
     [Skill.wind1, Skill.agi10, Skill.lightning2],
     []],
    ["20012", "Wendigo", "Hailing from frigid forests and mountains, this ice spirit rides the winds to attack with blinding speed.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.giant, Attribute.wind,
     740, 628, 758, 745, 800, 675,
     [Skill.wind1, Skill.agi10, Skill.wind2, Skill.agi20, Skill.wind3],
     [Skill.agi10, Skill.agi20, Skill.wind3],
     []],
    ["20013", "Jinn", "This evil spirit is fettered by no corporeal form, and has the power to change its size and shape at will.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.humanoid, Attribute.wind,
     678, 725, 684, 715, 721, 723,
     [Skill.wind1, Skill.agi20, Skill.wind2, Skill.datk20, Skill.wind3],
     [Skill.agi20, Skill.datk20, Skill.wind3],
     []],
    ["20014", "Hanuman", "This shapeshifting incarnation of the wind god possesses both great wisdom and prowess as a warrior. ", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.giant, Attribute.wind,
     695, 653, 678, 675, 785, 633,
     [Skill.wind1, Skill.def20, Skill.atk20, Skill.physical2, Skill.wind2],
     [Skill.def20, Skill.atk20, Skill.physical2],
     []],
    ["20015", "Cait Sith", "A capricious faerie that shrewdly observes the world in the guise of a common cat.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.humanoid, Attribute.poison,
     665, 692, 688, 733, 783, 714, 
     [Skill.poison1, Skill.dagi20, Skill.slash1, Skill.poison2, Skill.slash2],
     [Skill.dagi20, Skill.poison2, Skill.slash2],
     []],
    ["20016", "Basilisk", "Called the king of serpents, the basilisk has a body steeped in venom and a gaze that brings death.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.dragon, Attribute.poison,
     628, 665, 782, 670, 700, 672,
     [Skill.poison1, Skill.dwis20, Skill.poison2, Skill.dagi20, Skill.poison3],
     [Skill.dwis20, Skill.dagi20, Skill.poison3],
     []],
    ["20018", "Berserker", "Created by man, this mechanical dread destroys all in its path, discriminating not between friend or foe.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.giant, Attribute.mecha,
     808, 790, 808, 782, 728, 612, 
     [Skill.slash1, Skill.slash2, Skill.slash3, Skill.atk10, Skill.def10],
     [Skill.slash3, Skill.atk10, Skill.def10],
     []],
    ["20019", "Kirin", "A kind and gentle beast of divinity said to appear only during an age of benevolent and gracious rule.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.wolf, Attribute.light,
     700, 732, 694, 772, 772, 732,
     [Skill.heal, Skill.lightning1, Skill.majorheal, Skill.light2, Skill.light3],
     [Skill.lightning1, Skill.light2, Skill.light3],
     []],
    ["20020", "Sphinx", "A man's head and lion's body grant this beast the wisdom and strength to guard all royal and sacred.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.wolf, Attribute.light,
     708, 740, 787, 672, 674, 800, 
     [Skill.light1, Skill.atk20, Skill.dwis20, Skill.physical1, Skill.physical2],
     [Skill.atk20, Skill.dwis20, Skill.physical2],
     []],
    ["20021", "Unicorn", "Only the purest of maidens can tame this divine beast, which has a horn with the power to cures all ails.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.wolf, Attribute.light,
     650, 719, 710, 668, 720, 653,
     [Skill.physical1, Skill.heal, Skill.atk20, Skill.slash3, Skill.majorheal],
     [Skill.physical1, Skill.atk20, Skill.slash3],
     []],
    ["20022", "Succubus", "This demoness appears in the dreams of her prey, corrupting them with unbound lust and temptation.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.humanoid, Attribute.darkness,
     672, 760, 693, 688, 676, 763,
     [Skill.dwis20, Skill.darkness2, Skill.slash2, Skill.mana, Skill.life],
     [Skill.dwis20, Skill.darkness2, Skill.slash2],
     []],
    ["20023", "Diabolos", "A fallen angel and enemy of the gods who has now turned his divine powers upon the mortal world.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.humanoid, Attribute.darkness,
     688, 728, 753, 708, 727, 772,
     [Skill.darkness1, Skill.slash1, Skill.slash2, Skill.atk20, Skill.def20],
     [Skill.slash2, Skill.atk20, Skill.def20],
     []],
    ["20024", "Silver Slime", "This mutated slime is ill-suited to battle, though it is known to serve as an excellent combining material.", 
     Event.none, Border.none, 3, Place.grounds, 0, null, Shape.slime, Attribute.poison,
     10, 10, 1, 1, 1, 1,
     [Skill.heal],
     [Skill.heal],
     []],
    ["20028", "Mandragora", "Seen across Vana'diel, these bipedal plants have a society all their own. - FINAL FANTASY XI", 
     Event.none, Border.none, 3, Place.invitation, 1, null, Shape.orbs, Attribute.light,
     705, 742, 727, 707, 739, 759,
     [Skill.light1, Skill.wis10, Skill.agi20, Skill.wis20, Skill.light2],
     [Skill.wis10, Skill.wis20, Skill.light2],
     []],
    ["20030", "Good King Moggle Mog XII", "Long believed to be a myth, this moogle king has now descended to Eorzea. - FINAL FANTASY XIV", 
     Event.none, Border.none, 3, Place.invitation, 1, null, Shape.humanoid, Attribute.darkness,
     715, 741, 727, 757, 699, 739,
     [Skill.def10, Skill.darkness1, Skill.wis20, Skill.darkness2, Skill.def20],
     [Skill.wis20, Skill.darkness2, Skill.def20],
     []],
    ["20031", "Spriggan", "A soot-colored beast ever seen bearing a burden of precious stones. - FINAL FANTASY XIV", 
     Event.none, Border.none, 3, Place.invitation, 1, null, Shape.orbs, Attribute.earth,
     745, 734, 725, 712, 707, 752, 
     [Skill.earth1, Skill.wis10, Skill.earth2, Skill.agi20, Skill.earth3],
     [Skill.wis10, Skill.agi20, Skill.earth3],
     []],
    ["20035", "Surtr", "This fire giant will appear at the end of days with his flaming sword and minions to set creation ablaze.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.giant, Attribute.fire,
     835, 663, 806, 784, 656, 692,
     [Skill.fire1, Skill.physical1, Skill.fire2, Skill.physical2, Skill.fire3],
     [Skill.fire2, Skill.physical2, Skill.fire3],
     []],
    ["20036", "Grim Reaper", "Death itself, this being reaps the souls of the living with its scythe and sees them to the underworld.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.orbs, Attribute.death,
     696, 807, 862, 752, 657, 846,
     [Skill.darkness1, Skill.darkness2, Skill.dagi20, Skill.dwis20, Skill.darkness3],
     [Skill.dagi20, Skill.dwis20, Skill.darkness3],
     []],
    ["20037", "Dragoon", "This ancient war machine is mounted with massive, swiveling cannons capable of firing in any direction.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.wolf, Attribute.mecha,
     820, 684, 799, 784, 699, 655, 
     [Skill.fire1, Skill.physical1, Skill.physical2, Skill.atk20, Skill.physical3],
     [Skill.physical2, Skill.atk20, Skill.physical3],
     []],
    ["20038", "Ripper", "Crafted in antiquity, this mechanical humanoid tears through metal and flesh with its many steel blades.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.orbs, Attribute.mecha,
     656, 725, 738, 672, 745, 660,
     [Skill.physical1, Skill.atk10, Skill.physical2, Skill.ddef20, Skill.physical3],
     [Skill.atk10, Skill.ddef20, Skill.physical3],
     []],
    ["20039", "Avnas", "This evil deity commands all fire, and within the flames that burn about him the future can be seen.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.humanoid, Attribute.fire,
     672, 757, 657, 657, 705, 745, 
     [Skill.fire1, Skill.physical2, Skill.fire2, Skill.wis10, Skill.fire3],
     [Skill.fire2, Skill.wis10, Skill.fire3],
     []],
    ["20040", "Yeti", "Found in snowbound mountains, this wise and peaceful humanoid is unrelenting and ferocious in battle.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.giant, Attribute.water,
     777, 656, 763, 770, 684, 740, 
     [Skill.water1, Skill.slash1, Skill.water2, Skill.slash2, Skill.water3],
     [Skill.water2, Skill.slash2, Skill.water3],
     []],
    ["20041", "Arigan", "The wings of this avian elemental take on the luster of the gold and silver upon which it feasts.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.bird, Attribute.earth,
     706, 756, 706, 684, 799, 684,
     [Skill.atk10, Skill.def10, Skill.physical1, Skill.physical2, Skill.physical3],
     [Skill.atk10, Skill.def10, Skill.physical3],
     []],
    ["20042", "Taranis", "Warrior maiden and goddess of thunder, this being is worshipped for her powers over death and battle.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.humanoid, Attribute.lightning,
     663, 777, 741, 692, 734, 763, 
     [Skill.lightning1, Skill.darkness1, Skill.lightning2, Skill.darkness2, Skill.lightning3],
     [Skill.lightning2, Skill.darkness2, Skill.lightning3],
     []],
    ["20043", "Umu Dabrutu", "Spawned by an ancient wyrm to battle the gods, this magical master of storms commands the winds.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.bird, Attribute.wind,
     784, 677, 727, 699, 777, 677, 
     [Skill.wind1, Skill.slash1, Skill.wind2, Skill.slash2, Skill.wind3],
     [Skill.wind2, Skill.slash2, Skill.wind3],
     []],
    ["20045", "Sleipnir", "This eight-legged warhorse of the gods gallops freely through the realms of heaven, Attribute.earth, and hell.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.wolf, Attribute.darkness,
     751, 725, 796, 768, 846, 727, 
     [Skill.darkness1, Skill.agi10, Skill.darkness2, Skill.physical2, Skill.agi20],
     [Skill.agi10, Skill.physical2, Skill.agi20],
     []],
    ["20046", "Rangda", "Versed in the black arts and ever attended by her familiars, this vile witch visits disaster upon mortals.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.humanoid, Attribute.darkness,
     658, 849, 670, 677, 663, 842,
     [Skill.darkness1, Skill.datk20, Skill.ddef20, Skill.dagi20, Skill.dwis20],
     [Skill.ddef20, Skill.dagi20, Skill.dwis20],
     []],
    ["20047", "Indigo Pixie", "One of the seven pixies of good fortune. Though short-tempered and sadistic, deep down it truly cares. ", 
     Event.pixie, Border.none, 3, Place.snowfield, 0, null, Shape.orbs, Attribute.darkness,
     808, 698, 788, 679, 780, 715,
     [Skill.agi10, Skill.darkness2, Skill.atk10, Skill.physical2, Skill.darkness3],
     [Skill.agi10, Skill.atk10, Skill.physical2],
     []],
    ["20048", "Bicorn", "This two-horned demonic creature derives its strength from devouring the flesh of the good, virtuous, and loyal.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.wolf, Attribute.darkness,
     759, 659, 821, 737, 781, 669,
     [Skill.darkness1, Skill.physical1, Skill.atk20, Skill.mana, Skill.darkness2],
     [Skill.physical1, Skill.atk20, Skill.darkness2],
     []],
    ["20049", "Pih Fang", "Spawned forth from a tree, this sinister bird visits great fire and conflagration upon the lands over which it flies.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.bird, Attribute.fire,
     759, 659, 821, 737, 781, 669,
     [Skill.fire1, Skill.agi10, Skill.fire2, Skill.slash2, Skill.fire3],
     [Skill.agi10, Skill.slash2, Skill.fire3],
     []],
    ["20050", "Svarog", "This fire god of the firmament is praised by smiths, and wields as its weapons the tools of their trade.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.dragon, Attribute.fire,
     735, 745, 781, 724, 735, 721,
     [Skill.fire2, Skill.physical2, Skill.atk10, Skill.fire3, Skill.atk20],
     [Skill.physical2, Skill.atk10, Skill.atk20],
     []],
    ["20051", "Agares", "This demon is able to cause calamitous quakes, and commands change and flux to steer the course of the future.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.beast, Attribute.earth,
     800, 731, 723, 733, 699, 740, 
     [Skill.earth1, Skill.slash2, Skill.ls, Skill.atk20, Skill.earth2],
     [Skill.slash2, Skill.ls, Skill.atk20],
     []],
    ["20052", "Set", "Even among other immortals, this god of darkness and chaos commands fear as great as his powers.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.humanoid, Attribute.wind,
     722, 710, 792, 699, 720, 767, 
     [Skill.wind2, Skill.atk10, Skill.qs, Skill.atk20, Skill.wind3],
     [Skill.atk10, Skill.qs, Skill.atk20],
     []],
    ["20053", "Druj Nasu", "This vile demoness emerges from the mouth of hell to enter the bodies of the dead and spread her taint.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.female, Attribute.poison,
     699, 734, 711, 751, 749, 750,
     [Skill.poison1, Skill.datk20, Skill.dwis20, Skill.poison2, Skill.sd],
     [Skill.dwis20, Skill.poison2, Skill.sd],
     []],
    ["20054", "Basmu", "Once savage and tameless, this horned serpent spawn of the Great Mother now serves the lords of hell.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.dragon, Attribute.poison,
     755, 705, 821, 761, 709, 700,
     [Skill.poison1, Skill.poison2, Skill.slash2, Skill.slash3, Skill.poison3],
     [Skill.slash2, Skill.slash3, Skill.poison3],
     []],
    ["20055", "Ganesha", "This benevolent deity is worshipped as the Remover of Obstacles, and is tutelary of both trade and study.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.beast, Attribute.wind,
     811, 715, 761, 793, 686, 803, 
     [Skill.physical2, Skill.def20, Skill.wind2, Skill.wis20, Skill.physical3],
     [Skill.def20, Skill.wind2, Skill.wis20],
     []],
    ["20056", "Mummy", "These corpses are free of death´s grip, and the ancient among them possess powers from far beyond the grave.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.humanoid, Attribute.death,
     733, 774, 739, 770, 699, 709, 
     [Skill.slash2, Skill.poison2, Skill.death2, Skill.wis20, Skill.revival],
     [Skill.death2, Skill.wis20, Skill.revival],
     []],
    ["20057", "Bastet", "This feline goddess of the hearth and fertility is also revered for her aspects as a divinity of both war and music.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.female, Attribute.light,
     788, 767, 710, 733, 721, 771, 
     [Skill.light2, Skill.slash2, Skill.wis10, Skill.light3, Skill.majorheal],
     [Skill.slash2, Skill.wis10, Skill.light3],
     []],
    ["20058", "Grigori", "Cast from heaven for loving a human, this fallen angel bears forbidden knowledge and evil to the mortal world.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.humanoid, Attribute.darkness,
     743, 800, 774, 754, 739, 811,
     [Skill.agi10, Skill.wis10, Skill.darkness2, Skill.wis20, Skill.darkness3],
     [Skill.wis10, Skill.wis20, Skill.darkness3],
     []],
    ["20059", "Chaos", "This ageless demon has existed since creation, spreading vice and depravity to corrupt the good.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.wolf, Attribute.darkness,
     794, 687, 732, 686, 743, 715,
     [Skill.dagi20, Skill.darkness2, Skill.dwis20, Skill.sd, Skill.darkness3],
     [Skill.dagi20, Skill.dwis20, Skill.darkness3],
     []],
    ["20060", "Tengu", "Known as keepers of the mountains they inhabit, these ghastly spirits weave fell sorceries to cause the fall of men.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.bird, Attribute.wind,
     730, 752, 735, 727, 767, 767, 
     [Skill.wind1, Skill.wind2, Skill.dwis20, Skill.agi10, Skill.wind3],
     [Skill.dwis20, Skill.agi10, Skill.wind3],
     []],
    ["20061", "Bifrons", "This mighty demon uses necromancy to command the dead, nefariously moving their corpses from grave to grave.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.orbs, Attribute.death,
     755, 749, 700, 700, 695, 755, 
     [Skill.darkness2, Skill.wis10, Skill.darkness3, Skill.death2, Skill.death3],
     [Skill.wis10, Skill.darkness3, Skill.death3],
     []],
    ["20063", "Ruby Serpent", "This twin jewels of vibrant red crowning this viper house burning stars which endow the beast with its dominance.", 
     Event.serpents, Border.none, 3, Place.volcano, 0, null, Shape.dragon, Attribute.fire,
     786, 717, 790, 733, 775, 752,
     [Skill.fire1, Skill.fire2, Skill.slash2, Skill.atk20, Skill.fire3],
     [Skill.slash2, Skill.atk20, Skill.fire3],
     []],
    ["20064", "Sapphire Serpent", "As the embodiment of purity, this spirit of truest blue grants the power to calm emotions and see through treacheries.", 
     Event.serpents, Border.none, 3, Place.snowfield, 0, null, Shape.dragon, Attribute.water,
     743, 775, 687, 740, 775, 765,
     [Skill.water1, Skill.water2, Skill.wis10, Skill.majorheal, Skill.water3],
     [Skill.water2, Skill.wis10, Skill.water3],
     []],
    ["20065", "Emerald Serpent", "The untainted beauty of this lethargic green beast wins hearts of gods and demons much to the confusion of man.", 
     Event.serpents, Border.none, 3, Place.plains, 0, null, Shape.dragon, Attribute.wind,
     820, 695, 808, 780, 690, 650,
     [Skill.wind1, Skill.slash2, Skill.wind2, Skill.slash3, Skill.ls],
     [Skill.slash2, Skill.slash3, Skill.ls],
     []],
    ["20066", "Hakutaku", "This sacred beast's wisdom pervades all creation, and its image is a warding talisman against illness and plague.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.wolf, Attribute.light,
     780, 741, 725, 760, 704, 705,
     [Skill.physical1, Skill.heal, Skill.physical2, Skill.light3, Skill.majorheal],
     [Skill.physical2, Skill.light3, Skill.majorheal],
     []],
    ["20067", "Fae Sorceress", "The power of these mages is so feared among faeriekind that they must swear a strict code to practice their arcana.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.female, Attribute.light,
     780, 741, 725, 760, 704, 705,
     [Skill.dwis20, Skill.light2, Skill.dagi20, Skill.datk20, Skill.sd],
     [Skill.dwis20, Skill.light2, Skill.sd],
     []],
    ["20068", "Vepar", "With the oceans at her command, this duchess of hell is able to conjure raging storms and guide vast fleets to war.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.mermaid, Attribute.water,
     744, 832, 708, 689, 750, 715,
     [Skill.agi10, Skill.datk20, Skill.water2, Skill.wis20, Skill.water3],
     [Skill.agi10, Skill.wis20, Skill.water3],
     []],
    ["20069", "Apophis", "Born of chaos, this evil serpent is locked in eternal battle with the sun god to stay the dawn of each new day.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.serpent, Attribute.darkness,
     781, 811, 767, 760, 698, 780,
     [Skill.darkness1, Skill.datk20, Skill.dwis20, Skill.ep, Skill.darkness2],
     [Skill.dwis20, Skill.ep, Skill.darkness2],
     []],
    ["20070", "Amphitrite", "The world's seas and all they contain are ruled by this benevolent goddess queen and symbol of tranquil waters.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.mermaid, Attribute.light,
     738, 800, 727, 712, 765, 854,
     [Skill.ep, Skill.light2, Skill.agi10, Skill.agi20, Skill.light3],
     [Skill.ep, Skill.agi20, Skill.light3],
     []],
    ["20071", "Empusa", "A servant of the dark, this specter stalks in the night on the command of her master, seeking out warm blood.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.mermaid, Attribute.mecha,
     830, 798, 800, 699, 699, 771,
     [Skill.slash1, Skill.poison2, Skill.slash2, Skill.atkwis10, Skill.poison3],
     [Skill.slash2, Skill.atkwis10, Skill.poison3],
     []],
    ["20072", "Zahhak", "Each day of his thousand-year rule, this tyrant made a sacrifice of two souls to the serpents that grow forth from him.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.orbs, Attribute.poison,
     830, 705, 830, 790, 670, 702,
     [Skill.physical2, Skill.slash2, Skill.ddef20, Skill.atk20, Skill.physical3],
     [Skill.ddef20, Skill.atk20, Skill.physical3],
     []],
    ["20073", "Tiamat", "Felled by those same deities she first birthed, this creatress became the heavens and earth, but now returns.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.orbs, Attribute.water,
     700, 732, 703, 700, 818, 804,
     [Skill.water1, Skill.water2, Skill.wis10, Skill.agi20, Skill.water3],
     [Skill.wis10, Skill.agi20, Skill.water3],
     []],
    ["20074", "Forcalor", "Bending wind and water to his will, this duke of hell can consign the mightiest vessel to oblivion beneath the waves.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.merman, Attribute.water,
     744, 810, 734, 720, 755, 788,
     [Skill.water2, Skill.ds, Skill.wind2, Skill.agi20, Skill.water3],
     [Skill.ds, Skill.agi20, Skill.water3],
     []],
    ["20075", "Merman", "Unmatched in combat in open waters, clans of these fishmen claim dominion over vast stretches of the sea.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.merman, Attribute.water,
     809, 765, 749, 717, 735, 749,
     [Skill.ep, Skill.water2, Skill.wis10, Skill.dagi20, Skill.water3],
     [Skill.ep, Skill.wis10, Skill.water3],
     []],
    ["20076", "Rusalka", "Draped in mist, this sensual nymph dances to mesmerize passersby, then leads them to die in her riverbed.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.mermaid, Attribute.darkness,
     699, 811, 732, 721, 762, 804,
     [Skill.darkness2, Skill.water2, Skill.wis10, Skill.agiwis10, Skill.darkness3],
     [Skill.wis10, Skill.agiwis10, Skill.darkness3],
     []],
    ["20077", "Umibozu", "Appearing abruptly on nights when the seas are still, this giant destroys ships by churning rough waters and waves.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.merman, Attribute.darkness,
     811, 677, 860, 800, 662, 716,
     [Skill.physical1, Skill.def10, Skill.physical2, Skill.ls, Skill.physical3],
     [Skill.def10, Skill.ls, Skill.physical3],
     []],
    ["20078", "Occultum Katana", "Control over this sword's powers died with its master, and it now seeks only to cleave any and all things in two.", 
     Event.weapons, Border.none, 3, Place.desert, 0, null, Shape.orbs, Attribute.none,
     670, 670, 819, 705, 790, 650,
     [Skill.darkness1, Skill.life, Skill.slash3, Skill.death1, Skill.ds],
     [Skill.slash3, Skill.death1, Skill.ds],
     []],
    ["20079", "Lapidem Sword", "Passed down through many noble lines, this cursed sword longs to spill blood and fan the the flames of strife.", 
     Event.weapons, Border.none, 3, Place.ocean, 0, null, Shape.orbs, Attribute.none,
     790, 750, 805, 750, 750, 705,
     [Skill.agi10, Skill.slash1, Skill.slash2, Skill.slash3, Skill.qs],
     [Skill.agi10, Skill.slash3, Skill.qs],
     []],
    ["20083", "Shen", "Men who breathe the noxious fumes of this sea dragon are plagued by visions of terror and mirages of false hope.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.serpent, Attribute.poison,
     771, 801, 770, 749, 737, 770,
     [Skill.dagi20, Skill.life, Skill.ddef20, Skill.poison2, Skill.datk20],
     [Skill.ddef20, Skill.poison2, Skill.datk20],
     []],
    ["20084", "Makara", "Mount of the gods and scourge of the deep, this scaled leviathan spews forth lightning from its cavernous maw.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.shark, Attribute.lightning,
     849, 732, 841, 808, 664, 742,
     [Skill.physical1, Skill.atk10, Skill.physical2, Skill.physical3, Skill.def20],
     [Skill.atk10, Skill.physical3, Skill.def20],
     []],
    ["20085", "Kurozuka", "Damned to demonhood for the murder of her child, this miserable hag can now feed only on the flesh of the living.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.female, Attribute.darkness,
     742, 844, 746, 721, 740, 812,
     [Skill.darkness1, Skill.dwis20, Skill.death1, Skill.darkness2, Skill.darkness3],
     [Skill.dwis20, Skill.death1, Skill.darkness3],
     []],
    ["20086", "Murmur", "Entering the mortal world atop a griffin mount, this ducal demon bears a name meaning the blare of a trumpet.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.bird, Attribute.death,
     810, 675, 811, 801, 750, 727,
     [Skill.slash1, Skill.slash2, Skill.ddef20, Skill.ds, Skill.slash3],
     [Skill.ddef20, Skill.ds, Skill.slash3],
     []],
    ["20087", "Orthrus", "Whelped in the bowels of the earth, this hound guards the way to hell with its two heads and serpent tails.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.wolf, Attribute.poison,
     781, 770, 794, 752, 849, 713,
     [Skill.datk20, Skill.slash2, Skill.qs, Skill.dagi20, Skill.slash3],
     [Skill.qs, Skill.dagi20, Skill.slash3],
     []],
    ["20088", "Doppleganger", "Free of its fleshly prison, this sinister form of the self from which it splintered is feared as a harbinger of death.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.orbs, Attribute.death,
     752, 800, 760, 744, 812, 832,
     [Skill.life, Skill.dwis20, Skill.death1, Skill.mana, Skill.darkness2],
     [Skill.dwis20, Skill.death1, Skill.darkness2],
     []],
    ["20089", "Orobas", "Loyal to those who summon him, this great prince of hell answers true of things past, present, and future.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.humanoid, Attribute.fire,
     781, 748, 749, 812, 759, 797,
     [Skill.def10, Skill.physical2, Skill.fb, Skill.fire3, Skill.def20],
     [Skill.fb, Skill.fire3, Skill.def20],
     []],
    ["20090", "Quetzalcoatl", "This feathered serpent god of life ushers in the dawn that marks the daily return from the death that is night.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.dragon, Attribute.wind,
     702, 788, 814, 754, 814, 748,
     [Skill.slash1, Skill.wind2, Skill.slash2, Skill.atk20, Skill.slash3],
     [Skill.slash2, Skill.atk20, Skill.slash3],
     []],
    ["20092", "Hel", "Massing an army to rival the gods, this goddess receives to her stygian realm those who die dishonorable deaths.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.female, Attribute.death,
     799, 869, 718, 715, 709, 720,
     [Skill.poison2, Skill.majorheal, Skill.wis20, Skill.poison3, Skill.revival],
     [Skill.wis20, Skill.poison3, Skill.revival],
     []],
    ["20093", "Tlaloc", "Beyond bringing the rains of life, this god also receives the souls or those who drown or are struck by lightning.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.humanoid, Attribute.lightning,
     750, 777, 789, 743, 731, 870,
     [Skill.water1, Skill.lightning2, Skill.water2, Skill.lightning3, Skill.water3],
     [Skill.water2, Skill.lightning3, Skill.water3],
     []],
    ["20094", "Oberon", "This proud faerie king reads the hearts of man and casts spells to control him, acting on behalf of troubled lovers.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.orbs, Attribute.light,
     798, 789, 738, 741, 730, 854,
     [Skill.wis10, Skill.light2, Skill.dwis20, Skill.light3, Skill.fb],
     [Skill.dwis20, Skill.light3, Skill.fb],
     []],
    ["20095", "Shantak", "This beast plucks up those who roam its dreamland and drops them before the throne of an ancient and evil god.", 
     Event.none, Border.none, 3, Place.plains_night, 0, null, Shape.bird, Attribute.wind,
     834, 720, 735, 779, 749, 739,
     [Skill.agi10, Skill.wind2, Skill.slash2, Skill.agi20, Skill.wind3],
     [Skill.agi10, Skill.agi20, Skill.wind3],
     []],
    ["20096", "Pink Queen", "Unmatched in the ways and waging of war, this royal matron forces any who stand before her into quick submission.", 
     Event.chess, Border.none, 3, Place.desert, 0, null, Shape.humanoid, Attribute.poison,
     770, 768, 752, 741, 770, 760,
     [Skill.poison2, Skill.dwis20, Skill.datk20, Skill.poison3, Skill.ep],
     [Skill.dwis20, Skill.poison3, Skill.ep],
     []],
    ["20097", "Gold King", "The heart of his army's position, this wise regent stays enemy attacks as he gathers power and times his counters.", 
     Event.chess, Border.none, 3, Place.ocean, 0, null, Shape.merman, Attribute.light,
     810, 665, 721, 831, 691, 762,
     [Skill.def10, Skill.ls, Skill.majorheal, Skill.def20, Skill.light3],
     [Skill.ls, Skill.def20, Skill.light3],
     []],
    ["20098", "Typhon", "The very heavens shake as this behemoth, the hideous son of the earth mother, lumbers across hill and dale.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.giant, Attribute.earth,
     849, 779, 844, 798, 764, 766,
     [Skill.physical1, Skill.physical2, Skill.atk20, Skill.physical3, Skill.ls],
     [Skill.atk20, Skill.physical3, Skill.ls],
     []],
    ["20099", "Tarasque", "This fell wyrm once facilely decimated the myriad men and machines of war a king sent to claim its blood.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.dragon, Attribute.poison,
     799, 820, 781, 779, 756, 778,
     [Skill.datk20, Skill.poison2, Skill.dagi20, Skill.dwis20, Skill.poison3],
     [Skill.dagi20, Skill.dwis20, Skill.poison3],
     []],
    ["20100", "Beast Glatisant", "Its coming thought an omen of the fall of kings, this curious beast is sought by those struggling against their own fate.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.beast, Attribute.earth,
     754, 796, 799, 801, 828, 790,
     [Skill.agi20, Skill.physical2, Skill.earth2, Skill.defagi10, Skill.physical3],
     [Skill.agi20, Skill.defagi10, Skill.physical3],
     []],
    ["20101", "Jiangshi", "Reanimated to return the fallen to their homeland, this benevolent zombie obeys only the will of righteous men.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.female, Attribute.death,
     825, 808, 812, 749, 823, 699,
     [Skill.physical1, Skill.physical2, Skill.death1, Skill.ddef20, Skill.physical3],
     [Skill.death1, Skill.ddef20, Skill.physical3],
     []],
    ["20102", "Vayu", "This god of wind is himself the very void between light and dark where neither good nor evil holds sway.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.humanoid, Attribute.wind,
     777, 684, 801, 777, 812, 756,
     [Skill.agi10, Skill.slash2, Skill.wind2, Skill.slash3, Skill.ds],
     [Skill.agi10, Skill.slash3, Skill.ds],
     []],
    ["20103", "Lamassu", "Stone effigies of this regal beast are placed in front of palace gates to summon its aegis against calamity.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.female, Attribute.light,
     730, 854, 721, 733, 750, 866,
     [Skill.physical1, Skill.light2, Skill.fb, Skill.light3, Skill.defwis10],
     [Skill.fb, Skill.light3, Skill.defwis10],
     []],
    ["20104", "Amon", "A mighty contender vying for control of hell, this demon warlord also pens poetry rivaling that of the ancient kings.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.humanoid, Attribute.death,
     725, 747, 785, 754, 844, 780,
     [Skill.physical1, Skill.atk10, Skill.physical2, Skill.wis10, Skill.darkness3],
     [Skill.atk10, Skill.wis10, Skill.darkness3],
     []],
    ["20105", "Cacus", "This son of the flame god boasts of tearing the heads from human sacrifices to satisfy his terrible hunger.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.giant, Attribute.fire,
     841, 810, 769, 750, 742, 810,
     [Skill.wis10, Skill.fire1, Skill.fire2, Skill.wis20, Skill.fire3],
     [Skill.wis10, Skill.wis20, Skill.fire3],
     []],
    ["20106", "Nezha", "Born of a god in mortal form, this benevolent soul exorcises evil spirits seeking to throw the world into chaos.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.orbs, Attribute.mecha,
     790, 778, 800, 808, 784, 769,
     [Skill.slash1, Skill.slash2, Skill.atk20, Skill.slash3, Skill.defagi10],
     [Skill.atk20, Skill.slash3, Skill.defagi10],
     []],
    ["20107", "Airavata", "This holy steed of a thunder god soars through the heavens calling down lightning upon the earth.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.beast, Attribute.lightning,
     851, 743, 831, 801, 711, 759,
     [Skill.physical1, Skill.agi20, Skill.physical2, Skill.def20, Skill.physical3],
     [Skill.agi20, Skill.def20, Skill.physical3],
     []],
    ["20110", "Garnet Jelly", "This empress of a hallowed oasis relinquishes her duties for one day every summer to frolic in the sun.", 
     Event.stinging, Border.none, 3, Place.ocean, 0, null, Shape.jellyfish, Attribute.poison,
     742, 666, 770, 670, 682, 680,
     [Skill.dagi20, Skill.datk20, Skill.poison2, Skill.dwis20, Skill.poison3],
     [Skill.dagi20, Skill.dwis20, Skill.poison3],
     []],
    ["20111", "Sphinx (Android)", "A man's head and lion's body grant this beast the wisdom and strength to guard all royal and sacred.", 
     Event.none, Border.none, 3, Place.coliseum, 0, "20020", Shape.none, Attribute.light,
     832, 870, 915, 812, 804, 941,
     [Skill.qs, Skill.light2, Skill.fb, Skill.light3, Skill.physical3],
     [Skill.qs, Skill.fb, Skill.light3],
     []],
    ["20112", "Enyo", "Bearing a name meaning war, this daughter to a god and goddess of the sea was born with hair white as surf.", 
     Event.graeae, Border.none, 3, Place.volcano, 0, null, Shape.orbs, Attribute.darkness,
     824, 805, 736, 749, 756, 844,
     [Skill.dagi20, Skill.darkness2, Skill.dwis20, Skill.darkness3, Skill.datk20],
     [Skill.dwis20, Skill.darkness3, Skill.datk20],
     []],
    ["20113", "Deino", "Her name symbolic of terror, this sorceress dwells deep in the darkness of an island grotto with her sisters.", 
     Event.graeae, Border.none, 3, Place.volcano, 0, null, Shape.orbs, Attribute.darkness,
     784, 762, 801, 784, 818, 745,
     [Skill.darkness1, Skill.physical2, Skill.atk10, Skill.atkagi10, Skill.physical3],
     [Skill.atk10, Skill.atkagi10, Skill.physical3],
     []],
    ["20114", "Caladrius", "Appearing to bedridden monarchs, this snowy white fowl draws malady from the body to seal away in its satchel.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.bird, Attribute.poison,
     809, 811, 777, 782, 780, 830,
     [Skill.heal, Skill.poison1, Skill.ep, Skill.majorheal, Skill.poison2],
     [Skill.poison1, Skill.ep, Skill.poison2],
     []],
    ["20115", "Leraje", "This brazen demon appears among men in the guise of an archer loosing poisoned arrows that putrefy the flesh.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.poison,
     754, 809, 850, 789, 855, 788,
     [Skill.ddef20, Skill.poison1, Skill.atk10, Skill.slash2, Skill.slash3],
     [Skill.ddef20, Skill.atk10, Skill.slash3],
     []],
    ["20116", "Cat-o'-Nine-Tails", "With the whips he wields, this agent of torture coaxes guarded secrets and screams from his prisoners' lips.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.wolf, Attribute.darkness,
     762, 798, 801, 743, 835, 748,
     [Skill.slash2, Skill.atk20, Skill.agi20, Skill.darkness2, Skill.slash3],
     [Skill.atk20, Skill.agi20, Skill.slash3],
     []],
    ["20117", "Minokawa", "Legend tells of this fearsome bird's talons of steel, pinions made of sabers, and girth enough to swallow the moon.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.bird, Attribute.mecha,
     764, 788, 799, 820, 818, 779,
     [Skill.slash1, Skill.slash2, Skill.def20, Skill.slash3, Skill.qs],
     [Skill.def20, Skill.slash3, Skill.qs],
     []],
    ["20118", "Black Shuck", "All who gaze into the malevolent eye of this devilish hound come to meet a grisly fate in its fiercely fanged maw.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.wolf, Attribute.death,
     758, 801, 779, 752, 840, 789,
     [Skill.qs, Skill.atk20, Skill.slash1, Skill.slash2, Skill.slash3],
     [Skill.qs, Skill.atk20, Skill.slash3],
     []],
    ["20119", "Anemoi Thuellai", "Serving the lord of storms, these gods of the four winds send forth their gusts and gales from an island in the sky.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.orbs, Attribute.wind,
     812, 781, 801, 803, 789, 812,
     [Skill.wind1, Skill.physical2, Skill.atkagi10, Skill.wind2, Skill.defwis10],
     [Skill.atkagi10, Skill.wind2, Skill.defwis10],
     []],
    ["20120", "Python", "This great serpent spread divine prophecy among men till its death was foretold and it turned upon the gods.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.dragon, Attribute.poison,
     790, 788, 814, 790, 820, 810,
     [Skill.datk20, Skill.poison2, Skill.ddef20, Skill.physical3, Skill.dwis20],
     [Skill.ddef20, Skill.physical3, Skill.dwis20],
     []],
    ["20121", "Zorya", "The apocalypse would begin should this goddess of the aurora ever release the shackled hound she watches over.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.female, Attribute.light,
     777, 868, 754, 742, 770, 830,
     [Skill.light1, Skill.light2, Skill.darkness2, Skill.fb, Skill.light3],
     [Skill.darkness2, Skill.fb, Skill.light3],
     []],
    ["20122", "Humsa", "Nesting in a lake among sacred peaks, this great swan rules the breath of the cosmos and the wisdom of the gods.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.bird, Attribute.water,
     780, 761, 834, 841, 819, 801,
     [Skill.physical1, Skill.ep, Skill.water2, Skill.water3, Skill.ds],
     [Skill.ep, Skill.water3, Skill.ds],
     []],
    ["20123", "Lachesis", "One of the three Fates, this deity measures the thread of life, deciding the fate of man and god alike.", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.female, Attribute.mecha,
     799, 888, 788, 790, 780, 840,
     [Skill.lightning1, Skill.death1, Skill.sd, Skill.lightning2, Skill.lightning3],
     [Skill.death1, Skill.sd, Skill.lightning3],
     []],
    ["20124", "Torte-o'-Lantern", "One bite of this demonic pastry births addiction to its smooth, rich taste perfected in ovens heated by hellfire.", 
     Event.sweet_nightmare, Border.none, 3, Place.plains_night, 0, null, Shape.pumpkinhead, Attribute.darkness,
     666, 703, 690, 681, 662, 702,
     [Skill.qs, Skill.darkness2, Skill.dwis20, Skill.curse, Skill.physical3],
     [Skill.qs, Skill.dwis20, Skill.curse],
     []],
    ["20125", "Pink Slime", "The rosy radiance emitted by this most adorable of slimes pulses with the form and fervor of a lovestruck heart.", 
     Event.pink_slime, Border.none, 3, Place.grounds, 0, null, Shape.slime, Attribute.light,
     460, 453, 456, 500, 453, 422,
     [Skill.physical1, Skill.light1, Skill.light2, Skill.light3, Skill.light4],
     [Skill.light2, Skill.light3, Skill.light4],
     []],
    ["20126", "Roc", "", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.bird, Attribute.wind,
     852, 812, 855, 795, 838, 760,
     [Skill.atk10, Skill.physical1, Skill.atkagi10, Skill.physical2, Skill.physical3],
     [Skill.atk10, Skill.atkagi10, Skill.physical3],
     []],
    ["20127", "Kinkabyo", "With powers granted by the light of the moon, this menacing feline seeks only to haunt humans into an early grave.", 
     Event.none, Border.none, 3, Place.volcano_night, 0, null, Shape.humanoid, Attribute.poison,
     795, 826, 819, 797, 805, 790,
     [Skill.dwis20, Skill.physical1, Skill.physical2, Skill.ddef20, Skill.ep],
     [Skill.physical2, Skill.ddef20, Skill.ep],
     []],
    ["20128", "Cactuar", "Like the luck it is said to bring, this playful prankster of a plant is easy come, easy go.", 
     Event.none, Border.none, 3, Place.desert, 0, null, Shape.cactuar, Attribute.earth,
     720, 520, 520, 500, 1000, 500,
     [Skill.agi10, Skill.physical1, Skill.agi20, Skill.physical2, Skill.ds],
     [Skill.agi20, Skill.physical2, Skill.ds],
     []],
    ["20129", "Cactuar", "Like the luck it is said to bring, this playful prankster of a plant is easy come, easy go.", 
     Event.none, Border.none, 3, Place.volcano, 0, null, Shape.cactuar, Attribute.earth,
     720, 520, 520, 500, 1000, 500,
     [Skill.agi10, Skill.physical1, Skill.agi20, Skill.physical2, Skill.ds],
     [Skill.agi20, Skill.physical2, Skill.ds],
     []],
    ["20130", "Cactuar", "Like the luck it is said to bring, this playful prankster of a plant is easy come, easy go.", 
     Event.none, Border.none, 3, Place.snowfield, 0, null, Shape.cactuar, Attribute.earth,
     720, 520, 520, 500, 1000, 500,
     [Skill.agi10, Skill.physical1, Skill.agi20, Skill.physical2, Skill.ds],
     [Skill.agi20, Skill.physical2, Skill.ds],
     []],
    ["20131", "Cactuar", "Like the luck it is said to bring, this playful prankster of a plant is easy come, easy go.", 
     Event.none, Border.none, 3, Place.ocean, 0, null, Shape.cactuar, Attribute.earth,
     720, 520, 520, 500, 1000, 500,
     [Skill.agi10, Skill.physical1, Skill.agi20, Skill.physical2, Skill.ds],
     [Skill.agi20, Skill.physical2, Skill.ds],
     []],
    ["20132", "Cactuar", "Like the luck it is said to bring, this playful prankster of a plant is easy come, easy go.", 
     Event.none, Border.none, 3, Place.plains, 0, null, Shape.cactuar, Attribute.earth,
     720, 520, 520, 500, 1000, 500,
     [Skill.agi10, Skill.physical1, Skill.agi20, Skill.physical2, Skill.ds],
     [Skill.agi20, Skill.physical2, Skill.ds],
     []],
    ["20133", "Chocobo Eater", "Many a swan song is sung by the insatiable growling of this fowl-feasting beast's stomach.", 
     Event.chocobo_eater, Border.none, 3, Place.volcano, 0, null, Shape.beast, Attribute.earth,
     850, 625, 830, 810, 650, 775,
     [Skill.earth2, Skill.slash2, Skill.earth3, Skill.slash3, Skill.ls],
     [Skill.earth3, Skill.slash3, Skill.ls],
     [Skill.earth3, Skill.slash3, Skill.ls]],
    ["20134", "Enlil", "", 
     Event.none, Border.none, 3, Place.zeus, 0, null, Shape.zhumanoid, Attribute.wind,
     825, 789, 839, 831, 799, 788,
     [Skill.slash1, Skill.wind2, Skill.atk20, Skill.slash2, Skill.slash3],
     [Skill.wind2, Skill.atk20, Skill.slash3],
     []],
    ["20135", "Sharur", "", 
     Event.none, Border.none, 3, Place.zeus, 0, null, Shape.pegasus, Attribute.mecha,
     823, 870, 848, 876, 780, 768,
     [Skill.def10, Skill.physical1, Skill.sd, Skill.atkdef10, Skill.physical2],
     [Skill.sd, Skill.atkdef10, Skill.physical2],
     []],
    ["20136", "Agrat bat Mahlat", "", 
     Event.none, Border.none, 3, Place.zeus, 0, null, Shape.zfemale, Attribute.poison,
     806, 856, 801, 792, 864, 884,
     [Skill.poison1, Skill.datk20, Skill.dwis20, Skill.poison2, Skill.dagi20],
     [Skill.datk20, Skill.dwis20, Skill.poison2],
     []],
    ["20137", "Hippelaphe", "", 
     Event.none, Border.none, 3, Place.zeus, 0, null, Shape.pegasus, Attribute.lightning,
     833, 846, 798, 807, 855, 804,
     [Skill.lightning1, Skill.agi10, Skill.agiwis10, Skill.lightning2, Skill.physical3],
     [Skill.agi10, Skill.agiwis10, Skill.physical3],
     []],
    ["20138", "Arianrhod", "", 
     Event.none, Border.none, 3, Place.zeus, 0, null, Shape.zfemale, Attribute.light,
     790, 859, 792, 801, 835, 825,
     [Skill.ep, Skill.light1, Skill.light2, Skill.light3, Skill.fb],
     [Skill.ep, Skill.light3, Skill.fb],
     []],
    ["20139", "Ahura Mazda", "", 
     Event.none, Border.none, 3, Place.zeus, 0, null, Shape.zhumanoid, Attribute.light,
     825, 813, 838, 828, 872, 870,
     [Skill.heal, Skill.slash1, Skill.light2, Skill.wis20, Skill.light3],
     [Skill.light2, Skill.wis20, Skill.light3],
     []],
    ["20140", "Asha Vahishta", "", 
     Event.none, Border.none, 3, Place.zeus, 0, null, Shape.pegasus, Attribute.fire,
     857, 844, 856, 874, 762, 769,
     [Skill.physical1, Skill.physical2, Skill.def20, Skill.atk20, Skill.sd],
     [Skill.physical2, Skill.atk20, Skill.sd],
     []],
    ["20144", "Chocolate Slime", "With its decadent depth and subtle perfections both bitter and sweet, this slime is the ultimate guilty pleasure.", 
     Event.valentine, Border.none, 3, Place.grounds, 0, "00020", Shape.valentine, Attribute.none,
     10, 10, 1, 1, 1, 1,
     [Skill.heal],
     [Skill.heal],
     []],
    ["20146", "Fire Jotnar", "", 
     Event.none, Border.none, 3, Place.desert_night, 0, null, Shape.giant, Attribute.fire,
     878, 830, 817, 811, 837, 782,
     [Skill.atk10, Skill.heal, Skill.slash1, Skill.atk20, Skill.physical2],
     [Skill.atk10, Skill.atk20, Skill.physical2],
     []],
    ["20147", "Purson", "", 
     Event.none, Border.none, 3, Place.desert_night, 0, null, Shape.humanoid, Attribute.darkness,
     858, 855, 826, 831, 822, 836,
     [Skill.wis10, Skill.darkness2, Skill.dwis20, Skill.darkness3, Skill.defwis10],
     [Skill.dwis20, Skill.darkness3, Skill.defwis10],
     []],
    ["20148", "Flauros", "", 
     Event.none, Border.none, 3, Place.desert_night, 0, null, Shape.wolf, Attribute.fire,
     861, 848, 844, 847, 838, 844,
     [Skill.def10, Skill.slash2, Skill.fire2, Skill.slash3, Skill.def20],
     [Skill.def10, Skill.slash3, Skill.def20],
     []],
    ["20149", "Huitzilopochtli", "", 
     Event.none, Border.none, 3, Place.desert_night, 0, null, Shape.orbs, Attribute.light,
     868, 816, 853, 837, 841, 819,
     [Skill.atk10, Skill.slash2, Skill.light1, Skill.atk20, Skill.slash3],
     [Skill.atk10, Skill.atk20, Skill.slash3],
     []],
    ["20150", "Dhampir", "", 
     Event.none, Border.none, 3, Place.desert_night, 0, null, Shape.female, Attribute.death,
     828, 820, 821, 838, 822, 827,
     [Skill.datk20, Skill.physical2, Skill.qs, Skill.atkwis10, Skill.physical3],
     [Skill.qs, Skill.atkwis10, Skill.physical3],
     []],
    ["20151", "Samodiva", "", 
     Event.none, Border.none, 3, Place.desert_night, 0, null, Shape.female, Attribute.fire,
     820, 850, 818, 826, 835, 857,
     [Skill.fire1, Skill.agi10, Skill.fire2, Skill.ds, Skill.fire3],
     [Skill.agi10, Skill.ds, Skill.fire3],
     []],
    ["20152", "Coatlicue", "", 
     Event.none, Border.none, 3, Place.desert_night, 0, null, Shape.dragon, Attribute.earth,
     818, 841, 812, 812, 859, 867,
     [Skill.earth1, Skill.dwis20, Skill.wis20, Skill.earth2, Skill.earth3],
     [Skill.dwis20, Skill.wis20, Skill.earth3],
     []],
    ["20153", "Buckriders", "", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.darkness,
     854, 841, 877, 813, 881, 840,
     [Skill.slash2, Skill.agi20, Skill.atk10, Skill.slash3, Skill.atk20],
     [Skill.atk10, Skill.slash3, Skill.atk20],
     []],
    ["20154", "Susano-o", "", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.giant, Attribute.wind,
     860, 853, 850, 845, 868, 851,
     [Skill.wind1, Skill.slash2, Skill.wind2, Skill.atkwis10, Skill.wind3],
     [Skill.slash2, Skill.atkwis10, Skill.wind3],
     []],
    ["20155", "Ushi-oni", "", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.beast, Attribute.poison,
     938, 821, 850, 859, 790, 843,
     [Skill.physical1, Skill.poison2, Skill.physical2, Skill.dwis20, Skill.poison3],
     [Skill.physical2, Skill.dwis20, Skill.poison3],
     []],
    ["20156", "Ded Moroz", "", 
     Event.none, Border.none, 3, Place.snowfield_night, 0, null, Shape.orbs, Attribute.water,
     836, 858, 822, 841, 863, 870,
     [Skill.water2, Skill.dwis20, Skill.physical2, Skill.water3, Skill.defwis10],
     [Skill.dwis20, Skill.water3, Skill.defwis10],
     []],
    ["20157", "Rahab", "This fallen angel was charged with the task of returning to heaven a lost book containing the mysteries of the cosmos.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.shark, Attribute.water,
     872, 851, 855, 855, 845, 866,
     [Skill.water2],
     [],
     []],
    ["20158", "Dantalion", "This demonic duke inspires false love in mortal hearts and sways all things to the advantage of those who summon him.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.merman, Attribute.mecha,
     877, 862, 855, 855, 869, 890,
     [Skill.slash1],
     [],
     []],
    ["20159", "Hippocampus", "With the speed of a horse on land, this steed bears the ocean nymphs and gods between and beneath the waves.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.shark, Attribute.water,
     873, 855, 835, 824, 877, 880,
     [Skill.water2],
     [],
     []],
    ["20160", "Tcaridyi", "Born to the good faerie queen and evil demon king, this venomous worm-woman brings great fever and malady.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.mermaid, Attribute.poison,
     832, 888, 819, 834, 880, 896,
     [Skill.poison1],
     [],
     []],
    ["20161", "Oceanus", "Embodiment of the great river encircling the world, this deity foresaw the fall of the old gods and ushered in the new.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.merman, Attribute.water,
     888, 866, 855, 855, 865, 833,
     [Skill.physical1],
     [],
     []],
    ["20162", "Tishtrya", "", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.orbs, Attribute.light,
     0, 0, 0, 0, 0, 0,
     [],
     [],
     []],
    ["20163", "Moby Dick", "Many hunters become the hunted of this terror of the seas, which breaches only in the most treacherous of waters,", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.shark, Attribute.water,
     900, 835, 902, 865, 860, 800,
     [Skill.physical2],
     [],
     []],
    ["20164", "Pscipolnitsa", "Known as Lady Midday, this evil spirit keeps a watchful eye over tilled fields, visiting her wrath upon restful hands.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.mermaid, Attribute.light,
     845, 855, 820, 860, 880, 900,
     [Skill.wis10],
     [],
     []],
    ["20165", "Glasya Labolas", "This familiar of hell's legates draws power from the act of slaughter, about which it teaches those who summon it.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.orbs, Attribute.wind,
     855, 856, 833, 855, 866, 892,
     [Skill.wind2],
     [],
     []],
    ["20166", "Gusion", "Released from an ancient seal, this great duke of hell is charged with all acts of negotiation with other realms.", 
     Event.none, Border.none, 3, Place.ocean_night, 0, null, Shape.merman, Attribute.darkness,
     859, 851, 880, 825, 865, 880,
     [Skill.darkness2],
     [],
     []]
]);

Card.addLimitedTypes({
    "20111": [Type.cool] // Sphinx
});

Card.addNotes({
    "20063": "Skillset not confirmed", // Ruby Serpent
    "20064": "Skillset not confirmed", // Sapphire Serpent
    "20065": "Skillset not confirmed", // Emerald Serpent
    "20066": "Skillset not confirmed", // Hakutaku
    "20067": "Skillset not confirmed", // Fae Sorceress
    "20068": "Skillset not confirmed", // Vepar
    "20069": "Skillset not confirmed", // Apophis
    "20070": "Skillset not confirmed", // Amphitrite
    "20071": "Skillset not confirmed", // Empusa
    "20072": "Skillset not confirmed", // Zahhak
    "20073": "Skillset not confirmed", // Tiamat
    "20074": "Skillset not confirmed", // Forcalor
    "20075": "Skillset not confirmed", // Merman
    "20076": "Skillset not confirmed", // Rusalka
    "20078": "Skillset not confirmed", // Occultum Katana
    "20079": "Skillset not confirmed", // Lapidem Sword
    "20083": "Skillset not confirmed.",  // Shen
    "20087": "Skillset not confirmed",    // Orthrus
    "20089": "Skillset not confirmed",    // Orobas
    "20090": "Skillset not confirmed",    // Quetzalcoatl
    "20092": "Skillset not confirmed",    // Hel
    "20093": "Skillset not confirmed", // Tlaloc
    "20095": "Skillset not confirmed",    // Shantak
    "20096": "Skillset not confirmed",    // Pink Queen
    "20097": "Skillset not confirmed",    // Gold King
    "20098": "Skillset not confirmed", 
    "20099": "Skillset not confirmed", 
    "20100": "Skillset not confirmed", 
    "20101": "Skillset not confirmed", 
    "20102": "Skills from Jap version", 
    "20103": "Skillset not confirmed", 
    "20104": "Skillset not confirmed", 
    "20105": "Skillset not confirmed", 
    "20106": "Skillset not confirmed", 
    "20107": "Skillset not confirmed", 
    "20110": "Skillset not confirmed",   // Garnet Jelly
    "20112": "Skills not confirmed",
    "20113": "Skills not confirmed",
    "20114": "Skills from Japanese version",
    "20115": "Skills from Japanese version",
    "20116": "Skills from Japanese version",
    "20117": "Skills from Japanese version",
    "20118": "Skills from Japanese version",
    "20119": "Skills from Japanese version",
    "20120": "Skills from Japanese version",
    "20121": "Skills from Japanese version",
    "20122": "Skills from Japanese version",
    "20123": "Skills from Japanese version",
    "20124": "Skills from Japanese version",    // Torte-o'-Lantern
    "20125": "Skills from Japanese version",    // Pink Slime
    "20126": "All data from Japanese version",  // Roc
    "20127": "Skills from Japanese version",    // Kinkabyo
    "20128": "All data from Japanese version", 
    "20129": "All data from Japanese version", 
    "20130": "All data from Japanese version", 
    "20131": "All data from Japanese version", 
    "20132": "All data from Japanese version", 
    "20133": "Skills from Japanese version", 
    "20134": "All data from Japanese version", 
    "20135": "All data from Japanese version", 
    "20136": "All data from Japanese version", 
    "20137": "All data from Japanese version", 
    "20138": "All data from Japanese version", 
    "20139": "All data from Japanese version", 
    "20140": "All data from Japanese version",
    "20146": "All data from Japanese version",
    "20147": "All data from Japanese version",
    "20148": "All data from Japanese version",
    "20149": "All data from Japanese version",
    "20150": "All data from Japanese version",
    "20151": "All data from Japanese version",
    "20152": "All data from Japanese version",
    "20153": "All data from Japanese version",
    "20154": "All data from Japanese version",
    "20155": "All data from Japanese version",
    "20156": "All data from Japanese version",
    "20157": "Skills missing",
    "20158": "Skills missing",
    "20159": "Skills missing",
    "20160": "Skills missing",
    "20161": "Skills missing",
    "20162": "All data missing",
    "20163": "Skills missing",
    "20164": "Skills missing",
    "20165": "Skills missing",
    "20166": "Skills missing"
});

ExCard.addAll([
    ["25001", "Nyai Roro Kidul", "From her throne in the south seas, this goddess keeps watch over an island kingdom and controls the water's rage.",
     Event.pink_slime, ExType.red, 3, Place.quests, 0, Shape.none, Attribute.water,
     [ExSkill.hp1, ExSkill.hp2, ExSkill.hp3]],
    ["25002", "Ikenga", "Worshippers of this god of endeavor and success are granted sacred power in their right hand and guided to victory.",
     Event.pink_slime, ExType.red, 3, Place.quests, 0, Shape.none, Attribute.earth,
     [ExSkill.atk2, ExSkill.atk4, ExSkill.atk6]],
    ["25003", "Yatagarasu", "",
     Event.pink_slime, ExType.blue, 3, Place.quests, 0, Shape.none, Attribute.light,
     [ExSkill.pow_qs1, ExSkill.pow_qs2, ExSkill.pow_qs3]],
    ["25004", "Zephyrus", "",
     Event.none, ExType.red, 3, Place.zeus, 0, Shape.zorbs, Attribute.wind,
     [ExSkill.wind1, ExSkill.wind2, ExSkill.wind3]],
    ["25005", "Atropos", "",
     Event.none, ExType.blue, 3, Place.zeus, 0, Shape.zfemale, Attribute.mecha,
     [ExSkill.suc_ds1, ExSkill.suc_ds2, ExSkill.suc_ds3]],
    ["25006", "Nanna", "",
     Event.none, ExType.red, 3, Place.zeus, 0, Shape.zdragon, Attribute.light,
     [ExSkill.def2, ExSkill.def4, ExSkill.def6]],
    ["25007", "Indra", "",
     Event.none, ExType.blue, 3, Place.desert_night, 0, Shape.humanoid, Attribute.lightning,
     [ExSkill.suc_gs1, ExSkill.suc_gs2, ExSkill.suc_gs3]],
    ["25008", "Tilottama", "",
     Event.none, ExType.red, 3, Place.desert_night, 0, Shape.female, Attribute.water,
     [ExSkill.mp2, ExSkill.mp3, ExSkill.mp5]]
]); 