/*
 * Card:
 *   ID Name Description Event Border Stars Place Place2 Prototype Shape Attribute HP MP ATK DEF AGI WIS 
 *   Skills Recommends RecommendsRB
 */
Card.addAll([
    ["30001", "Suzaku", "The spirit bird that defends the southern heavens, purging calamity by fire and bringing good luck.",
     Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lbird, Attribute.fire,
     794, 898, 830, 866, 912, 892,
     [Skill.fire2, Skill.physical2, Skill.physical3, Skill.fire3, Skill.atk20, Skill.wis20],
     [Skill.physical3, Skill.fire3, Skill.atk20],
     [Skill.fire3, Skill.atk20, Skill.wis20]],
    ["30003", "Kraken", "A colossal monster that lurks in the depths of sea, surfacing to attack ships with its gigantic tentacles.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.dragon, Attribute.water, 
     830, 720, 915, 800, 760, 780, 
     [Skill.water2, Skill.atk20, Skill.physical2, Skill.def20, Skill.physical3, Skill.atkdef10],
     [Skill.atk20, Skill.def20, Skill.physical3],
     [Skill.atk20, Skill.physical3, Skill.atkdef10]],
    ["30004", "Genbu", "The spirit tortoise that defends the northern heavens, guarding against calamity and bringing prosperity.", 
     Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lwolf, Attribute.water,
     868, 902, 810, 940, 830, 880,
     [Skill.physical2, Skill.def20, Skill.wis20, Skill.physical3, Skill.atk20, Skill.water3],
     [Skill.wis20, Skill.physical3, Skill.atk20],
     [Skill.wis20, Skill.atk20, Skill.water3]],
    ["30005", "Golem", "A figure crafted of clay and imbued with the breath of life to faithfully carry out its maker's wishes.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.earth,
     966, 820, 966, 966, 800, 760, 
     [Skill.physical2, Skill.atk10, Skill.physical3, Skill.def20, Skill.atk20, Skill.ls],
     [Skill.atk10, Skill.physical3, Skill.atk20],
     [Skill.physical3, Skill.atk20, Skill.ls]],
    ["30006", "Jormungandr", "This colossal serpent encircles the world, and is fated to battle the gods come the end of days.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.dragon, Attribute.earth,
     924, 896, 820, 850, 790, 829,
     [Skill.earth2, Skill.atk20, Skill.earth3, Skill.def20, Skill.physical3, Skill.atkdef10],
     [Skill.atk20, Skill.def20, Skill.physical3],
     [Skill.atk20, Skill.physical3, Skill.atkdef10]],
    ["30007", "Seiryu", "The spirit dragon that defends the eastern heavens, bringing good fortune to the lands below it.", 
     Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lorbs, Attribute.lightning,
     868, 794, 889, 900, 903, 862, 
     [Skill.physical2, Skill.def20, Skill.lightning2, Skill.majorheal, Skill.physical3, Skill.defagi10],
     [Skill.def20, Skill.lightning2, Skill.physical3],
     [Skill.def20, Skill.physical3, Skill.defagi10]],
    ["30008", "Hecatoncheir", "This grotesque giant bears immense power in its one hundred arms, for which even the gods fear it.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.giant, Attribute.lightning,
     822, 835, 899, 850, 830, 851,
     [Skill.atk10, Skill.slash2, Skill.atk20, Skill.slash3, Skill.def20, Skill.atkwis10],
     [Skill.atk10, Skill.atk20, Skill.slash3],
     [Skill.atk20, Skill.slash3, Skill.atkwis10]],
    ["30009", "Ramiel", "This angel, whose name means \"thunder of the gods\", conveys the divine word through visions.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.humanoid, Attribute.lightning,
     800, 802, 816, 773, 816, 803,
     [Skill.lightning2, Skill.wis20, Skill.lightning3, Skill.mana, Skill.majorheal, Skill.defwis10],
     [Skill.lightning2, Skill.wis20, Skill.lightning3],
     [Skill.wis20, Skill.lightning3, Skill.defwis10]],
    ["30010", "Garuda", "Glowing bright as if ablaze, this avian spirit brought an end to many gods in the battle for the elixir of life.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.bird, Attribute.wind,
     848, 872, 848, 796, 886, 848,
     [Skill.wind2, Skill.physical2, Skill.agi20, Skill.physical3, Skill.dwis20, Skill.wind3],
     [Skill.agi20, Skill.physical3, Skill.dwis20],
     [Skill.agi20, Skill.dwis20, Skill.wind3]],
    ["30011", "Wyvern", "Smaller than its dragon kin, the wyvern is more gifted in flight and bears a poisonous barb on its tail.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.dragon, Attribute.wind,
     774, 798, 866, 850, 890, 842,
     [Skill.wind2, Skill.poison2, Skill.physical2, Skill.wind3, Skill.agi20, Skill.defagi10],
     [Skill.physical2, Skill.wind3, Skill.agi20],
     [Skill.physical2, Skill.wind3, Skill.defagi10]],
    ["30012", "Medusa", "Even in death, the eyes of this foul, serpent-haired temptress turn all who gaze upon them to stone.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.humanoid, Attribute.poison,
     819, 882, 824, 820, 844, 823, 
     [Skill.poison2, Skill.physical2, Skill.dagi20, Skill.poison3, Skill.physical3, Skill.wis25],
     [Skill.dagi20, Skill.poison3, Skill.physical3],
     [Skill.poison3, Skill.physical3, Skill.wis25]],
    ["30013", "Vampire", "The bastard offspring of a lamia that hunts the living, unable to resist its instinctive thirst for blood.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.humanoid, Attribute.death,
     835, 914, 906, 835, 882, 910, 
     [Skill.life, Skill.atk20, Skill.mana, Skill.agi20, Skill.slash3, Skill.revival],
     [Skill.atk20, Skill.agi20, Skill.slash3],
     [Skill.atk20, Skill.slash3, Skill.revival]],
    ["30014", "Lich", "A sorcerer so gifted as to grant himself immortality, the lich is even more powerful in death than in life.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.death,
     784, 997, 782, 795, 768, 1019,
     [Skill.poison2, Skill.datk20, Skill.darkness3, Skill.mana, Skill.revival, Skill.wis20],
     [Skill.datk20, Skill.darkness3, Skill.revival],
     [Skill.darkness3, Skill.revival, Skill.wis20]],
    ["30015", "Byakko", "The spirit tiger that defends the western heavens, using its powers to maintain peace and tranquility.", 
     Event.bahamut, Border.none, 4, Place.volcano, 0, null, Shape.lwolf, Attribute.mecha,
     869, 822, 895, 902, 840, 893,
     [Skill.def20, Skill.physical2, Skill.physical3, Skill.atk20, Skill.agi20, Skill.atkdef10],
     [Skill.physical3, Skill.atk20, Skill.agi20],
     [Skill.physical3, Skill.atk20, Skill.atkdef10]],
    ["30017", "Angel", "A celestial envoy that visits man on behalf of the gods, and fights to defend him from the minions of hell.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.humanoid, Attribute.light,
     764, 873, 860, 751, 866, 924,
     [Skill.light2, Skill.heal, Skill.light3, Skill.majorheal, Skill.def20, Skill.wis20],
     [Skill.light2, Skill.light3, Skill.def20],
     [Skill.light3, Skill.def20, Skill.wis20]],
    ["30018", "Fenrir", "So feared is this great wolf that it was once bound captive by the gods. Now free, it thirsts for revenge.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.wolf, Attribute.darkness,
     792, 754, 852, 792, 848, 760,
     [Skill.physical2, Skill.agi20, Skill.physical3, Skill.atk20, Skill.ddef20, Skill.atkagi10],
     [Skill.physical3, Skill.atk20, Skill.ddef20],
     [Skill.physical3, Skill.atk20, Skill.ddef20]],
    ["30019", "Gold Slime", "This mutated slime is ill-suited to battle, though it is known to serve as an excellent combining material.", 
     Event.none, Border.none, 4, Place.grounds, 0, null, Shape.slime, Attribute.none,
     50, 50, 5, 5, 5, 5,
     [Skill.heal],
     [Skill.heal],
     [Skill.heal]],
    ["30021", "Cerberus (FFXI)", "A terror in the Near East, this fire-breathing canine is the bane of trolls. - FINAL FANTASY XI", 
     Event.none, Border.none, 4, Place.invitation, 1, null, Shape.wolf, Attribute.fire,
     856, 808, 877, 857, 851, 846,
     [Skill.fire2, Skill.def10, Skill.fire3, Skill.def20, Skill.agi20, Skill.wis20],
     [Skill.fire3, Skill.def20, Skill.agi20],
     [Skill.fire3, Skill.def20, Skill.wis20]],
    ["30025", "Giant", "Spawned by an ancient goddess, these huge beings are feared by the new gods for their great strength.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.earth,
     892, 760, 872, 774, 766, 764,
     [Skill.physical2, Skill.atk20, Skill.ddef20, Skill.def20, Skill.physical3, Skill.atkagi10],
     [Skill.atk20, Skill.ddef20, Skill.physical3],
     [Skill.atk20, Skill.ddef20, Skill.physical3]],
    ["30026", "Dullahan", "A headless knight drawn by the scent of coming death. His great blade reaps the souls of those it fells.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.giant, Attribute.death,
     828, 877, 864, 886, 812, 841,
     [Skill.slash2, Skill.def20, Skill.agi20, Skill.atk20, Skill.slash3, Skill.qs],
     [Skill.agi20, Skill.atk20, Skill.slash3],
     [Skill.atk20, Skill.slash3, Skill.qs]],
    ["30027", "Pazuzu", "This dread demon of storms and drought controls searing winds that visit feverish maladies upon man.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.wolf, Attribute.wind,
     742, 815, 860, 804, 802, 789,
     [Skill.wind2, Skill.fire3, Skill.physical3, Skill.datk20, Skill.wind3, Skill.atk25],
     [Skill.physical3, Skill.datk20, Skill.wind3],
     [Skill.physical3, Skill.datk20, Skill.atk25]],
    ["30028", "Pabilsag", "This fierce guardian wards the mountain gateway between the celestial realm and the netherworld.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.wolf, Attribute.poison,
     751, 960, 830, 860, 800, 890, 
     [Skill.poison2, Skill.wis20, Skill.slash2, Skill.def20, Skill.slash3, Skill.poison4],
     [Skill.wis20, Skill.def20, Skill.slash3],
     [Skill.wis20, Skill.def20, Skill.poison4]],
    ["30030", "Qiong-Ji", "This bring controls the winds, summon forth freezing gales, and is ever on the side of evil.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.giant, Attribute.wind,
     890, 784, 982, 778, 932, 882,
     [Skill.wind1, Skill.agi10, Skill.wind2, Skill.dagi20, Skill.agi20, Skill.wind3],
     [Skill.wind2, Skill.dagi20, Skill.agi20],
     [Skill.dagi20, Skill.agi20, Skill.wind3]],
    ["30031", "Revenant", "Reanimated by supernatural powers, this warrior retains in death the intellect and will it had in life.", 
     Event.none, Border.none, 4, Place.plains, 0, null, Shape.orbs, Attribute.death,
     999, 777, 957, 798, 782, 807,
     [Skill.darkness1, Skill.physical1, Skill.darkness2, Skill.physical2, Skill.darkness3, Skill.atk20],
     [Skill.darkness2, Skill.physical2, Skill.darkness3],
     [Skill.physical2, Skill.darkness3, Skill.atk20]],
    ["30033", "Fafnir", "It is said to bathe in the blood of this dragon, which guards a cursed treasure, is to become immortal.", 
     Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.dragon, Attribute.fire,
     858, 764, 878, 861, 768, 767, 
     [Skill.slash2, Skill.ddef20, Skill.def10, Skill.datk20, Skill.slash3, Skill.atkdef10],
     [Skill.ddef20, Skill.datk20, Skill.slash3],
     [Skill.ddef20, Skill.slash3, Skill.atkdef10]],
    ["30034", "Jotunn", "Despite their savage and barbaric ways, the strength of these frost giants rivals the gods themselves.", 
     Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.giant, Attribute.water, 
     940, 770, 932, 882, 765, 856, 
     [Skill.water2, Skill.physical2, Skill.dagi20, Skill.water3, Skill.slash3, Skill.atkwis10],
     [Skill.dagi20, Skill.water3, Skill.slash3],
     [Skill.water3, Skill.slash3, Skill.atkwis10]],
    ["30035", "Specter", "This evil spirit emits a deathly chill, and the soul of any who gazes upon it freezes over with terror.", 
     Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.orbs, Attribute.death,
     790, 957, 815, 815, 798, 907, 
     [Skill.darkness2, Skill.water2, Skill.mana, Skill.darkness3, Skill.water3, Skill.sd],
     [Skill.darkness2, Skill.darkness3, Skill.water3],
     [Skill.darkness3, Skill.water3, Skill.sd]],
    ["30037", "Talos", "Imbued with the power of fire, this bronze titan guards an island where an ancient kingdom once stood.", 
     Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.giant, Attribute.mecha,
     949, 767, 957, 940, 771, 798,
     [Skill.slash2, Skill.fire2, Skill.def20, Skill.slash3, Skill.fire3, Skill.atkdef10],
     [Skill.def20, Skill.slash3, Skill.fire3],
     [Skill.def20, Skill.slash3, Skill.atkdef10]],
    ["30038", "Power", "These angels stand on the frontlines of battle against evil, and are therefore most easily corrupted by it.", 
     Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.humanoid, Attribute.light,
     896, 913, 1010, 830, 858, 876,
     [Skill.light2, Skill.slash2, Skill.light3, Skill.darkness3, Skill.slash3, Skill.atkwis10],
     [Skill.light3, Skill.darkness3, Skill.slash3],
     [Skill.darkness3, Skill.physical3, Skill.atkwis10]],
    ["30039", "Thunder God Dongo", "", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.lightning,
     961, 990, 962, 843, 934, 906,
     [Skill.atk10, Skill.lightning3, Skill.agi20, Skill.atk20, Skill.lightning4, Skill.agiwis10],
     [Skill.agi20, Skill.atk20, Skill.lightning4],
     [Skill.agi20, Skill.lightning4, Skill.agiwis10]],
    ["30040", "Anahita", "This maiden deity of bounty rules over the fount of life, keeping vigil over health and child, crop and livestock.", 
     Event.none, Border.none, 4, Place.invitation, 2, null, Shape.humanoid, Attribute.water,
     929, 846, 779, 885, 843, 871,
     [Skill.water2, Skill.wis10, Skill.heal, Skill.water3, Skill.def20, Skill.wis20],
     [Skill.wis10, Skill.water3, Skill.def20],
     [Skill.wis10, Skill.water3, Skill.wis20]],
    ["30041", "Peri", "This fiery and ephemeral faerie, born forth from flame itself, lives by consuming fragrances alone.", 
     Event.none, Border.none, 4, Place.invitation, 2, null, Shape.bird, Attribute.fire,
     861, 894, 795, 825, 851, 920,
     [Skill.fire2, Skill.dwis20, Skill.mana, Skill.fire3, Skill.wis20, Skill.defwis10],
     [Skill.dwis20, Skill.fire3, Skill.wis20],
     [Skill.dwis20, Skill.fire3, Skill.wis20]],
    ["30042", "Virtus", "This embodiment of purest virtue works miracles and grants the favor of the gods to champions of good.", 
     Event.none, Border.none, 4, Place.invitation, 2, null, Shape.humanoid, Attribute.light,
     859, 847, 881, 929, 786, 843,
     [Skill.light2, Skill.agi20, Skill.light3, Skill.wis20, Skill.atk20, Skill.dwis20],
     [Skill.agi20, Skill.light3, Skill.wis20],
     [Skill.light3, Skill.wis20, Skill.dwis20]],
    ["30043", "Caim", "Versed in all languages, this devilish god sways the minds of mortals with words both clever and cunning.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.humanoid, Attribute.fire,
     845, 905, 815, 863, 844, 943,
     [Skill.slash2, Skill.wis20, Skill.fire2, Skill.life, Skill.dwis20, Skill.agiwis10],
     [Skill.wis20, Skill.fire2, Skill.dwis20],
     [Skill.wis20, Skill.fire2, Skill.dwis20]],
    ["30044", "Brigid", "This noble fire goddess expels winter fiends with flames from her magic brazier, ushering in the start of spring.", 
     Event.none, Border.none, 4, Place.volcano, 0, null, Shape.humanoid, Attribute.fire,
     825, 929, 789, 887, 833, 929,
     [Skill.fire2, Skill.heal, Skill.fire3, Skill.majorheal, Skill.wis20, Skill.defwis10],
     [Skill.fire2, Skill.fire3, Skill.wis20],
     [Skill.fire3, Skill.wis20, Skill.defwis10]],
    ["30045", "Aym", "Armed with his undying torch, this fire demon and duke of hell sets the proud cities of man ablaze.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.orbs, Attribute.fire,
     815, 865, 935, 822, 857, 850,
     [Skill.fire2, Skill.physical2, Skill.atk10, Skill.atk20, Skill.sd, Skill.atkwis10],
     [Skill.physical2, Skill.atk10, Skill.atk20],
     [Skill.physical2, Skill.atk20, Skill.atkwis10]],
    ["30046", "Atar", "Lesser deity and son of a benevolent god, this warrior of good and spirit of holy fire protects the world from evil.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.humanoid, Attribute.fire,
     873, 817, 871, 919, 865, 875,
     [Skill.fire2, Skill.heal, Skill.atk20, Skill.qs, Skill.fire3, Skill.wis20],
     [Skill.fire3, Skill.atk20, Skill.qs],
     [Skill.fire3, Skill.qs, Skill.wis20]],
    ["30047", "Rudra", "Mortals fear this malevolent god of wind and storm, yet praise him as the lord of bounty who sends the nurturing rains.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.female, Attribute.wind,
     845, 901, 905, 816, 891, 985, 
     [Skill.wind2, Skill.agi10, Skill.heal, Skill.wind3, Skill.agi20, Skill.agiwis10],
     [Skill.agi10, Skill.wind3, Skill.agi20],
     [Skill.wind3, Skill.agi20, Skill.agiwis10]],
    ["30048", "Taowu", "This wicked demon plots all mayhem that transpires, and is too arrogant and stubborn to ever concede defeat.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.wolf, Attribute.poison,
     911, 781, 919, 901, 793, 839,
     [Skill.poison1, Skill.def10, Skill.def20, Skill.poison2, Skill.ls, Skill.atk20],
     [Skill.def20, Skill.poison2, Skill.ls],
     [Skill.poison2, Skill.ls, Skill.atk20]],
    ["30049", "Narasimha", "This avatar of a higher god is both man and lion, with a strength and ferocity to tear apart even the most deathless evil.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.orbs, Attribute.lightning,
     843, 815, 999, 835, 903, 795,
     [Skill.atk10, Skill.lightning2, Skill.slash3, Skill.atk20, Skill.lightning3, Skill.agi20],
     [Skill.atk10, Skill.slash3, Skill.atk20],
     [Skill.atk10, Skill.slash3, Skill.atk20]],
    ["30050", "Barong", "The manifestation of good itself, this holy beast is fated to battle evil and protect mortals from coming to harm.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.wolf, Attribute.light,
     879, 833, 891, 901, 839, 819,
     [Skill.light2, Skill.physical2, Skill.def20, Skill.wis20, Skill.light3, Skill.atk20],
     [Skill.def20, Skill.wis20, Skill.light3],
     [Skill.wis20, Skill.light3, Skill.atk20]],
    ["30051", "Horus", "This divinity of the skies is the symbol of royalty. Its eyes hold power over the sun and moon and see the truth of all things.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.bird, Attribute.light,
     794, 835, 799, 889, 849, 909, 
     [Skill.slash2, Skill.qs, Skill.light2, Skill.wis20, Skill.light3, Skill.defwis10],
     [Skill.qs, Skill.wis20, Skill.light3],
     [Skill.qs, Skill.wis20, Skill.light3]],
    ["30052", "Echidna", "Half woman, half snake, this unaging goddess is known and feared for the host of vile progeny she has spawned.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.dragon, Attribute.earth,
     938, 923, 886, 956, 939, 987,
     [Skill.earth2, Skill.wis10, Skill.slash2, Skill.wis20, Skill.earth3, Skill.dwis20],
     [Skill.wis10, Skill.wis20, Skill.earth3],
     [Skill.wis20, Skill.earth3, Skill.dwis20]],
    ["30053", "Bugbear", "Strong and thickly furred, these beasts appear at twilight to snatch up children who play past the calls of their mothers.", 
     Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.lgiant, Attribute.earth,
     943, 830, 871, 893, 851, 810,
     [Skill.earth2, Skill.physical2, Skill.ddef20, Skill.physical3, Skill.earth3, Skill.revival],
     [Skill.ddef20, Skill.physical3, Skill.earth3],
     [Skill.ddef20, Skill.physical3, Skill.revival]],
    ["30054", "Bune", "With necromancy, this Great Duke of Hell commands the dead and summons demons to the world's graveyards.", 
     Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.lgiant, Attribute.death,
     862, 890, 834, 864, 790, 830,
     [Skill.def20, Skill.death2, Skill.wis20, Skill.darkness2, Skill.revival, Skill.agi20],
     [Skill.death2, Skill.wis20, Skill.revival],
     [Skill.death2, Skill.wis20, Skill.revival]],
    ["30055", "Dwarf Gear", "This armored terror boasts engines and crystals of Dwarvish making, and can be ridden only by the heroic of heart.", 
     Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.lgiant, Attribute.mecha,
     919, 835, 955, 895, 881, 861, 
     [Skill.slash3, Skill.atk10, Skill.agi20, Skill.wis20, Skill.atk20, Skill.ddef20],
     [Skill.slash3, Skill.atk10, Skill.atk20],
     [Skill.slash3, Skill.atk20, Skill.ddef20]],
    ["30056", "Balor", "Known as Balor of the Evil Eye, this ancient demon king's gaze consigns all who look upon it to oblivion.", 
     Event.gilgamesh, Border.none, 4, Place.volcano, 0, null, Shape.lgiant, Attribute.darkness,
     928, 881, 837, 907, 835, 850, 
     [Skill.darkness2, Skill.dagi20, Skill.ddef20, Skill.wis10, Skill.darkness3, Skill.wis20],
     [Skill.dagi20, Skill.wis10, Skill.darkness3],
     [Skill.wis10, Skill.darkness3, Skill.wis20]],
    ["30057", "Skadi", "Born of giants, this vengeful goddess and huntress of the north wields a bow and fears no enemy or quarry.", 
     Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.female, Attribute.water, 
     925, 828, 925, 852, 925, 872, 
     [Skill.physical2, Skill.water2, Skill.physical3, Skill.agi10, Skill.water3, Skill.agi20],
     [Skill.physical3, Skill.agi10, Skill.water3],
     [Skill.physical3, Skill.water3, Skill.agi20]],
    ["30058", "Forneus", "As the keeper of language, this sea monster and marquis of Hell can turn even the most dire animosity to love.", 
     Event.none, Border.none, 4, Place.snowfield, 0, null, Shape.dragon, Attribute.water,
     885, 907, 825, 847, 825, 930,
     [Skill.water1, Skill.water2, Skill.datk20, Skill.dwis20, Skill.water3, Skill.wis20],
     [Skill.datk20, Skill.dwis20, Skill.water3],
     [Skill.dwis20, Skill.water3, Skill.wis20]],
    ["30061", "Isis", "This devoted thronemother and symbol od pharaonic power weaves high magic capable of resurrecting the dead.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.female, Attribute.earth,
     836, 982, 860, 820, 888, 900,
     [Skill.earth2, Skill.physical2, Skill.datk20, Skill.earth3, Skill.dwis20, Skill.wis10],
     [Skill.datk20, Skill.earth3, Skill.dwis20],
     [Skill.earth3, Skill.dwis20, Skill.wis10]],
    ["30062", "Kala", "In its true form, this beast's size rivals the very stars, and its many eyes keep constant vigil lest evil's taint spread.", 
     Event.none, Border.none, 4, Place.desert, 0, null, Shape.beast, Attribute.earth,
     934, 802, 901, 1094, 794, 789, 
     [Skill.physical2, Skill.def10, Skill.physical3, Skill.atkdef10, Skill.ls, Skill.def20],
     [Skill.physical3, Skill.atkdef10, Skill.ls],
     [Skill.physical3, Skill.atkdef10, Skill.ls]],
    ["30063", "Nidhogg", "This dragon dwells in the deep beneath the world tree, restlessly gnawing at its roots in a bid to bring about its fall.", 
     Event.none, Border.none, 4, Place.ocean, 0, null, Shape.shark, Attribute.water,
     799, 860, 900, 833, 842, 830,
     [Skill.water1, Skill.water2, Skill.slash3, Skill.ls, Skill.water3, Skill.atk20],
     [Skill.slash3, Skill.ls, Skill.water3],
     [Skill.slash3, Skill.ls, Skill.atk20]],
    ["30064", "Colossus", "By sending forty thousand ships to the ocean floor, this mighty titan spared his island home from a vast enemy siege.", 
     Event.none, Border.none, 4, Place.ocean, 0, null, Shape.orbs, Attribute.mecha,
     999, 794, 1001, 963, 777, 843,
     [Skill.ep, Skill.physical2, Skill.light2, Skill.def20, Skill.physical3, Skill.defwis10],
     [Skill.ep, Skill.def20, Skill.physical3],
     [Skill.ep, Skill.def20, Skill.physical3]],
    ["30065", "Marbas", "This pestilent high lord of hell causes the decay of all life and leads thirty and six demon legions forth to battle.", 
     Event.none, Border.none, 4, Place.ocean, 0, null, Shape.merman, Attribute.poison,
     801, 931, 800, 832, 811, 978,
     [Skill.dwis20, Skill.poison2, Skill.datk20, Skill.ddef20, Skill.sap, Skill.poison3],
     [Skill.dwis20, Skill.poison2, Skill.sap],
     [Skill.dwis20, Skill.sap, Skill.poison3]],
    ["30066", "Vodianoi", "Denied the proper offerings, this vindictive ranine spirit will drown any so brazen as to enter his watery domain.", 
     Event.none, Border.none, 4, Place.ocean, 0, null, Shape.orbs, Attribute.water,
     879, 800, 816, 848, 860, 875,
     [Skill.water1, Skill.water2, Skill.slash3, Skill.ds, Skill.agi20, Skill.water3],
     [Skill.slash3, Skill.ds, Skill.agi20],
     [Skill.ds, Skill.agi20, Skill.water3]],
    ["30067", "Yamata no Orochi", "From its eight heads to its eight tails, this serpent spans eight mountains and valleys, grown fat by feasting on gods.", 
     Event.none, Border.none, 4, Place.ocean, 0, null, Shape.serpent, Attribute.water,
     980, 835, 923, 860, 840, 844,
     [Skill.water2, Skill.physical2, Skill.atk20, Skill.physical3, Skill.dagi20, Skill.atkwis10],
     [Skill.atk20, Skill.physical3, Skill.dagi20],
     [Skill.atk20, Skill.physical3, Skill.atkwis10]],
    ["30071", "Gremory", "This cunning duke of hell appears as a seductive temptress, instructing men in the ways to win women's hearts.", 
     Event.none, Border.none, 4, Place.invitation, 3, null, Shape.none, Attribute.darkness,
     886, 892, 900, 795, 855, 895,
     [Skill.darkness1, Skill.darkness2, Skill.wis10, Skill.darkness3, Skill.darkness4, Skill.atkwis10],
     [Skill.wis10, Skill.darkness3, Skill.darkness4],
     [Skill.wis10, Skill.darkness4, Skill.atkwis10]],
    ["30075", "Nanave", "Forged and loosed in the north seas, this steely horror guards those cities of old claimed by the sea's encroach.", 
     Event.none, Border.none, 4, Place.ocean, 0, null, Shape.shark, Attribute.mecha,
     887, 805, 992, 880, 856, 816,
     [Skill.slash2, Skill.atk20, Skill.def20, Skill.slash3, Skill.atkdef10, Skill.atkagi10],
     [Skill.atk20, Skill.slash3, Skill.atkdef10],
     [Skill.atk20, Skill.slash3, Skill.atkdef10]],
    ["30076", "Umbral Mermaid", "With powers drawn from all that is dire and dark of the seas, this mistress puts down those who profane her waters.", 
     Event.none, Border.none, 4, Place.ocean, 0, null, Shape.mermaid, Attribute.darkness,
     842, 942, 832, 851, 844, 1008,
     [Skill.darkness1, Skill.darkness2, Skill.wis10, Skill.ep, Skill.darkness3, Skill.defwis10],
     [Skill.wis10, Skill.ep, Skill.darkness3],
     [Skill.ep, Skill.darkness3, Skill.defwis10]],
    ["30077", "Guede", "Tending the path to the realm of the dead, this keeper of graves guides the souls of the deceased on their journey.", 
     Event.none, Border.none, 4, Place.plains_night, 0, null, Shape.humanoid, Attribute.death,
     801, 1000, 824, 818, 799, 980,
     [Skill.death1, Skill.darkness2, Skill.fb, Skill.dagi20, Skill.death2, Skill.dwis20],
     [Skill.darkness2, Skill.fb, Skill.death2],
     [Skill.fb, Skill.death2, Skill.dwis20]],
    ["30078", "Delphyne", "Sired by the king of all monstrosities, this dragoness was charged by her father to guard the gaol of the gods.", 
     Event.none, Border.none, 4, Place.plains_night, 0, null, Shape.dragon, Attribute.poison,
     872, 890, 877, 844, 999, 850,
     [Skill.ddef20, Skill.slash2, Skill.poison2, Skill.slash3, Skill.dagi20, Skill.poison3],
     [Skill.ddef20, Skill.poison2, Skill.dagi20],
     [Skill.ddef20, Skill.slash3, Skill.dagi20]],
    ["30079", "Andras", "Sowing seeds of discord among man, this strigine demonn teaches those he favors how to end their enemies.", 
     Event.none, Border.none, 4, Place.plains_night, 0, null, Shape.wolf, Attribute.fire,
     912, 841, 924, 859, 881, 835,
     [Skill.slash2, Skill.fire2, Skill.dr, Skill.slash3, Skill.fire3, Skill.atk20],
     [Skill.dr, Skill.slash3, Skill.fire3],
     [Skill.dr, Skill.slash3, Skill.atk20]],
    ["30080", "Vucub Caquix", "Shining silver and gold, this metal menace and false god poses as both sun and moon of the twilight world.", 
     Event.none, Border.none, 4, Place.plains_night, 0, null, Shape.bird, Attribute.mecha,
     803, 900, 918, 900, 853, 918,
     [Skill.atk10, Skill.slash2, Skill.wis10, Skill.light3, Skill.slash3, Skill.atkwis10],
     [Skill.atk10, Skill.wis10, Skill.slash3],
     [Skill.atk10, Skill.slash3, Skill.atkwis10]],
    ["30081", "Marduk", "From his storm chariot, this sun god of fifty names decimates foes with the seven mighty winds at his command.", 
     Event.none, Border.none, 4, Place.plains_night, 0, null, Shape.beast, Attribute.wind,
     941, 818, 840, 992, 948, 823,
     [Skill.slash2, Skill.def20, Skill.wind3, Skill.slash3, Skill.defagi10, Skill.atkagi10],
     [Skill.def20, Skill.slash3, Skill.defagi10],
     [Skill.def20, Skill.slash3, Skill.atkagi10]],
    ["30082", "War Elephant", "Wrought into the ultimate weapon, this oliphaunt crushes boulders and shakes earth underfoot. - Kingdom Conquest II", 
     Event.none, Border.none, 4, Place.quests, 0, null, Shape.beast, Attribute.earth,
     980, 822, 1050, 1090, 950, 760,
     [Skill.ls, Skill.physical2, Skill.atk10, Skill.physical3, Skill.atk20, Skill.physical4],
     [Skill.ls, Skill.physical3, Skill.atk20],
     [Skill.ls, Skill.atk20, Skill.physical4]],
    ["30083", "Sai Tai Sai", "This demon lord's unholy bell conjures clouds of flame and searing sand against the kingdoms of men.", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.giant, Attribute.fire, 
     962, 899, 880, 885, 824, 862,
     [Skill.wis10, Skill.physical2, Skill.fire2, Skill.dwis20, Skill.fire3, Skill.wis20],
     [Skill.wis10, Skill.dwis20, Skill.fire3],
     [Skill.dwis20, Skill.fire3, Skill.wis20]],
    ["30084", "Crom Cruach", "Known as the god slayer, the warlords of the underworld summoned this cryptic wyrm at armageddon.", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.dragon, Attribute.darkness, 
     920, 899, 912, 888, 871, 908,
     [Skill.life, Skill.darkness2, Skill.dwis20, Skill.wis10, Skill.darkness3, Skill.datk20],
     [Skill.dwis20, Skill.wis10, Skill.darkness3],
     [Skill.dwis20, Skill.darkness3, Skill.datk20]],
    ["30085", "Cherufe", "Virgins are offered as tribute to quell this flint giant's rage, lest its volcano erupt and the lives of all be lost.", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.beast, Attribute.fire, 
     954, 869, 901, 1000, 801, 812,
     [Skill.def10, Skill.physical2, Skill.def20, Skill.physical3, Skill.dr, Skill.def25],
     [Skill.def20, Skill.physical3, Skill.dr],
     [Skill.physical3, Skill.dr, Skill.def25]],
    ["30086", "Cybele", "Known as a symbol of order in a chaotic world, this maternal goddess guides the lives that flow from her.", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.female, Attribute.earth, 
     884, 906, 854, 910, 946, 992,
     [Skill.earth2, Skill.physical2, Skill.ep, Skill.earth3, Skill.fb, Skill.defwis10],
     [Skill.ep, Skill.earth3, Skill.fb],
     [Skill.ep, Skill.earth3, Skill.fb]],
    ["30087", "Adad", "Known as the lion of the heavens, this thunder god rides the storms to protect sovereigns who adopt his epithet.", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.orbs, Attribute.lightning, 
     954, 920, 886, 854, 880, 941,
     [Skill.lightning2, Skill.atk10, Skill.atkwis10, Skill.lightning3, Skill.defwis10, Skill.ls],
     [Skill.atkwis10, Skill.lightning3, Skill.defwis10],
     [Skill.atkwis10, Skill.lightning3, Skill.ls]],
    ["30088", "Mitra", "This divine adjudicator wars against the darkness seeking to end the covenant betwixt heaven and hell.", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.humanoid, Attribute.light, 
     916, 870, 918, 910, 866, 910,
     [Skill.slash2, Skill.wis20, Skill.atk20, Skill.slash3, Skill.light3, Skill.slash4],
     [Skill.wis20, Skill.atk20, Skill.slash3],
     [Skill.wis20, Skill.atk20, Skill.slash4]],
    ["30089", "Pemphredo", "This illuminating artifact's pupil shows vistas the heart desires, even should they lie beyond the edges of the world.", 
     Event.graeae, Border.none, 4, Place.volcano, 0, null, Shape.orbs, Attribute.darkness, 
     860, 935, 914, 866, 829, 936,
     [Skill.dwis20, Skill.darkness2, Skill.darkness3, Skill.wis10, Skill.death3, Skill.ep],
     [Skill.dwis20, Skill.wis10, Skill.death3],
     [Skill.wis10, Skill.death3, Skill.ep]],
    ["30090", "General Frost", "This titan of deepest winter has repulsed countless foes by sealing his realm in swirling snow and bitter ice.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.giant, Attribute.water, 
     901, 902, 954, 955, 863, 868,
     [Skill.dagi20, Skill.physical1, Skill.ddef20, Skill.physical2, Skill.physical3, Skill.ls],
     [Skill.dagi20, Skill.ddef20, Skill.physical3],
     [Skill.ddef20, Skill.physical3, Skill.ls]],
    ["30091", "Malthus", "This earl of hell fuels the flames of war from the shadows, drawing the truly wicked to battle for fresh bloodshed.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.bird, Attribute.wind, 
     928, 933, 920, 894, 931, 915,
     [Skill.slash2, Skill.atk10, Skill.defagi10, Skill.atkwis10, Skill.slash3, Skill.agi25],
     [Skill.defagi10, Skill.atkwis10, Skill.slash3],
     [Skill.atkwis10, Skill.slash3, Skill.agi25]],
    ["30092", "Ker", "This evil loosed by Pandora's innocent hand mercilessly punishes mortals, robbing them of their very souls.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.female, Attribute.death, 
     862, 950, 882, 889, 869, 944,
     [Skill.mana, Skill.darkness2, Skill.darkness3, Skill.life, Skill.death3, Skill.dwis40],
     [Skill.darkness2, Skill.darkness3, Skill.death3],
     [Skill.darkness3, Skill.death3, Skill.dwis40]],
    ["30093", "Hantu Raya", "Summoned from the underworld, this djinn's metamorphosis and herculean strength are venerated by shamans.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.humanoid, Attribute.death, 
     953, 912, 996, 925, 851, 896,
     [Skill.ddef20, Skill.slash2, Skill.dwis20, Skill.slash3, Skill.dagi40, Skill.qs],
     [Skill.ddef20, Skill.slash3, Skill.dagi40],
     [Skill.ddef20, Skill.dagi40, Skill.qs]],
    ["30094", "Pantera", "This beast's tantalizingly fragrant breath lures all creatures to their doom, save the dragon and unicorn.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.wolf, Attribute.wind, 
     890, 896, 892, 880, 1002, 883,
     [Skill.atk20, Skill.agi20, Skill.slash1, Skill.qs, Skill.slash2, Skill.wind3],
     [Skill.atk20, Skill.qs, Skill.slash2],
     [Skill.atk20, Skill.qs, Skill.slash2]],
    ["30095", "Sharabha", "This feral incarnation of the god of destruction is the sole entity able to stay the wrath of rampaging deities.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.beast, Attribute.light, 
     966, 915, 926, 901, 928, 910,
     [Skill.slash1, Skill.atk20, Skill.slash2, Skill.agi20, Skill.slash3, Skill.atkagi10],
     [Skill.atk20, Skill.agi20, Skill.slash3],
     [Skill.atk20, Skill.slash3, Skill.atkagi10]],
    ["30096", "Otshirvani", "Unfurling his falcon-like wings, this god of light stands against the serpent sowing animosity amongst mankind.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.bird, Attribute.light, 
     992, 841, 952, 960, 923, 918,
     [Skill.light1, Skill.slash1, Skill.light2, Skill.slash2, Skill.slash3, Skill.light3],
     [Skill.slash2, Skill.slash3, Skill.light3],
     [Skill.slash2, Skill.slash3, Skill.light3]],
    ["30097", "Amalthea", "Called the shield of lightning, this mechanized deity sheltered the infant gods from their father's terrible wrath.", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.female, Attribute.mecha, 
     851, 999, 911, 890, 899, 950,
     [Skill.lightning1, Skill.slash2, Skill.atk20, Skill.sd, Skill.lightning3, Skill.dagi20],
     [Skill.atk20, Skill.sd, Skill.lightning3],
     [Skill.atk20, Skill.sd, Skill.lightning3]],
    ["30098", "Gandaberunda", "", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.bird, Attribute.wind, 
     982, 920, 942, 963, 913, 928,
     [Skill.physical2, Skill.wind2, Skill.atk10, Skill.physical3, Skill.atkdef10],
     [Skill.atk10, Skill.physical3, Skill.atkdef10],
     [Skill.atk10, Skill.physical3, Skill.atkdef10]],
    ["30099", "Sekhmet", "", 
     Event.none, Border.none, 4, Place.volcano_night, 0, null, Shape.female, Attribute.earth, 
     915, 1008, 899, 929, 888, 909,
     [Skill.curse, Skill.physical2, Skill.earth2, Skill.earth3, Skill.physical3, Skill.dagi40],
     [Skill.curse, Skill.earth3, Skill.physical3],
     [Skill.curse, Skill.earth3, Skill.dagi40]],
    ["30100", "Mother of Abominations", "This idolatress brought the world to its knees by seducing kings, corrupting the masses, and persecuting the pious.", 
     Event.none, Border.none, 4, Place.invitation, 4, null, Shape.none, Attribute.poison, 
     895, 900, 890, 840, 930, 955,
     [Skill.poison2, Skill.wis10, Skill.poison3, Skill.dwis20, Skill.poison4, Skill.agiwis10],
     [Skill.wis10, Skill.dwis20, Skill.poison4],
     [Skill.wis10, Skill.dwis20, Skill.poison4]],
    ["30101", "Canhel", "", 
     Event.none, Border.none, 4, Place.zeus, 0, null, Shape.zhumanoid, Attribute.light,
     890, 943, 1007, 946, 980, 974,
     [Skill.slash1, Skill.slash2, Skill.light3, Skill.qs, Skill.slash3, Skill.atkdef10],
     [Skill.light3, Skill.qs, Skill.slash3],
     [Skill.qs, Skill.slash3, Skill.atkdef10]],
    ["30102", "Zhu Rong", "By heavenly decree, it falls to this red fire god of the south to lay ruin to the dynasties of man and punish the gods.", 
     Event.none, Border.none, 4, Place.zeus, 0, null, Shape.zdragon, Attribute.fire,
     1012, 960, 989, 995, 854, 890,
     [Skill.atk10, Skill.physical2, Skill.ls, Skill.atkdef10, Skill.physical3, Skill.fire4],
     [Skill.ls, Skill.atkdef10, Skill.physical3],
     [Skill.ls, Skill.atkdef10, Skill.physical3]],
    ["30103", "Heimdallr", "With unmatched seeing and hearing, this ever-vigilant being keeps watch at the foot of the burning rainbow bridge.", 
     Event.none, Border.none, 4, Place.zeus, 0, null, Shape.zorbs, Attribute.light,
     942, 971, 900, 928, 904, 1015,
     [Skill.light2, Skill.ep, Skill.ddef20, Skill.physical2, Skill.light3, Skill.dagi40],
     [Skill.ep, Skill.ddef20, Skill.light3],
     [Skill.ep, Skill.light3, Skill.dagi40]],
    ["30106", "Ose", "A figure in all warlocks' tomes, this demon steals men's sanity and makes even paupers think themselves kings.", 
     Event.none, Border.none, 4, Place.quests, 0, null, Shape.none, Attribute.darkness,
     890, 943, 1007, 945, 980, 974,
     [Skill.slash1, Skill.slash2, Skill.darkness3, Skill.ds, Skill.slash3, Skill.mr],
     [Skill.darkness3, Skill.ds, Skill.slash3],
     [Skill.darkness3, Skill.ds, Skill.mr]],
    ["30111", "Gayomart", "", 
     Event.none, Border.none, 4, Place.desert_night, 0, null, Shape.orbs, Attribute.mecha,
     962, 1013, 904, 923, 929, 1023,
     [Skill.qs, Skill.atk20, Skill.datk20, Skill.physical2, Skill.physical3, Skill.sd],
     [Skill.qs, Skill.atk20, Skill.physical3],
     [Skill.qs, Skill.atk20, Skill.sd]],
    ["30112", "Hastur", "", 
     Event.none, Border.none, 4, Place.desert_night, 0, null, Shape.giant, Attribute.darkness,
     1033, 991, 952, 950, 932, 950,
     [Skill.slash2, Skill.atkdef10, Skill.darkness2, Skill.atkwis10, Skill.slash3],
     [Skill.atkdef10, Skill.atkwis10, Skill.slash3],
     [Skill.atkdef10, Skill.atkwis10, Skill.slash3]],
    ["30113", "Zaria", "", 
     Event.none, Border.none, 4, Place.desert_night, 0, null, Shape.female, Attribute.light,
     963, 963, 935, 931, 950, 976,
     [Skill.wis10, Skill.light2, Skill.slash1, Skill.wis20, Skill.slash2, Skill.light3],
     [Skill.wis10, Skill.light2, Skill.wis20],
     [Skill.wis10, Skill.wis20, Skill.light3]],
    ["30114", "Parvati", "", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.female, Attribute.earth,
     975, 979, 961, 992, 991, 990,
     [Skill.earth1, Skill.def20, Skill.ds, Skill.earth2, Skill.ep],
     [Skill.ds, Skill.earth2, Skill.ep],
     []],
    ["30115", "Zennyo Ryuo", "", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.orbs, Attribute.water,
     981, 960, 983, 982, 980, 983,
     [Skill.water2, Skill.wis10, Skill.physical2, Skill.water3, Skill.wis20],
     [Skill.wis10, Skill.water3, Skill.wis20],
     []],
    ["30116", "Y Ddraig Goch", "", 
     Event.none, Border.none, 4, Place.snowfield_night, 0, null, Shape.dragon, Attribute.fire,
     1001, 991, 1003, 994, 975, 901,
     [],
     [],
     []],
    ["30118", "Dahut", "", 
     Event.none, Border.none, 4, Place.ocean_night, 0, null, Shape.mermaid, Attribute.darkness,
     999, 980, 992, 974, 989, 999,
     [Skill.darkness2, Skill.wis10, Skill.dagi20, Skill.dwis20, Skill.darkness3, Skill.ep],
     [Skill.wis10, Skill.dwis20, Skill.darkness3],
     [Skill.dwis20, Skill.darkness3, Skill.ep]],
    ["30119", "Saint George's Woe", "", 
     Event.none, Border.none, 4, Place.ocean_night, 0, null, Shape.serpent, Attribute.poison,
     1019, 972, 994, 986, 983, 994,
     [Skill.atk10, Skill.slash2, Skill.poison1, Skill.slash3, Skill.poison2, Skill.atkwis10],
     [Skill.atk10, Skill.slash3, Skill.poison2],
     [Skill.atk10, Skill.slash3, Skill.atkwis10]],
    ["30120", "Ullikummi", "The get of an exiled god and means of his revenge, this warrior of volcanic rock at once grew to reach the very heavens.", 
     Event.none, Border.none, 4, Place.ocean_night, 0, null, Shape.orbs, Attribute.mecha,
     1020, 992, 999, 993, 969, 960,
     [Skill.physical1, Skill.atk10, Skill.physical2, Skill.atk20, Skill.ddef20],
     [Skill.physical2, Skill.atk20, Skill.ddef20],
     []],
    ["30121", "Levin Serpent", "", 
     Event.none, Border.none, 4, Place.ocean_night, 0, null, Shape.none, Attribute.lightning,
     1001, 997, 981, 966, 1001, 992,
     [Skill.lightning2, Skill.slash1, Skill.atk20, Skill.slash2, Skill.lightning3, Skill.qs],
     [Skill.atk20, Skill.slash2, Skill.lightning3],
     [Skill.atk20, Skill.lightning3, Skill.qs]],
    ["30122", "Kiyohime", "Her love denied, this young daughter was turned into a dragon by her rage, and her fire burned he who spurned her.", 
     Event.none, Border.none, 4, Place.ocean_night, 0, null, Shape.mermaid, Attribute.fire,
     986, 1000, 972, 952, 992, 1016,
     [Skill.fire1, Skill.wis10, Skill.fire2, Skill.wis20, Skill.fire3, Skill.ds],
     [Skill.wis10, Skill.wis20, Skill.fire3],
     [Skill.wis20, Skill.fire3, Skill.ds]],
    ["30123", "Taurvi", "", 
     Event.none, Border.none, 4, Place.invitation, 5, null, Shape.none, Attribute.poison,
     996, 1003, 962, 982, 992, 996,
     [Skill.poison2, Skill.wis10, Skill.poison3, Skill.dwis20, Skill.defwis10, Skill.poison4],
     [Skill.poison3, Skill.dwis20, Skill.defwis10],
     [Skill.dwis20, Skill.defwis10, Skill.poison4]],
    ["30124", "Bonbibi", "", 
     Event.lightdarkness, Border.none, 4, Place.plains, 0, null, Shape.wolf, Attribute.light,
     1009, 800, 1001, 1001, 1004, 899,
     [Skill.physical1, Skill.light1, Skill.physical2, Skill.atk25, Skill.physical3, Skill.qs],
     [Skill.physical2, Skill.atk25, Skill.physical3],
     [Skill.atk25, Skill.physical3, Skill.qs]],
    ["30125", "Hypnos", "", 
     Event.lightdarkness, Border.none, 4, Place.plains_night, 0, null, Shape.humanoid, Attribute.darkness,
     1005, 960, 982, 953, 1002, 1018,
     [Skill.darkness2, Skill.datk20, Skill.dwis20, Skill.darkness3, Skill.ep, Skill.nervepinch],
     [Skill.dwis20, Skill.darkness3, Skill.ep],
     [Skill.darkness3, Skill.ep, Skill.nervepinch]],
    ["30126", "Gaia", "", 
     Event.none, Border.none, 4, Place.zeus, 0, null, Shape.zhumanoid, Attribute.mecha,
     0, 0, 0, 0, 0, 0,
     [],
     [],
     []],
    ["30127", "Astaroth", "", 
     Event.none, Border.none, 4, Place.zeus, 0, null, Shape.zdragon, Attribute.fire,
     0, 0, 0, 0, 0, 0,
     [],
     [],
     []]
]);

Card.addLimitedTypes({
    "30040": [Type.cool, Type.coolr], // Anahita
    "30041": [Type.cool, Type.coolr], // Peri
    "30042": [Type.cool, Type.coolr], // Virtus
    "30071": [Type.cool, Type.coolr], // Gremory
    "30100": [Type.cool, Type.coolr], // Mother of Abominations
    "30123": [Type.cool, Type.coolr]  // Taurvi
});

Card.addNotes({
    "30039": "Skills from Jap version, profile missing",       // Thunder God Dongo
    "30052": "Skills from Japanese version",    // Echidna
    "30071": "Rebirth skill not confirmed",     // Gremory
    "30077": "Rebirth skill not confirmed",     // Guede
    "30079": "Rebirth skill not confirmed",     // Andras
    "30081": "Rebirth skill not confirmed",     // Marduk
    "30084": "Rebirth skill not confirmed",
    "30085": "All data from Jap version",
    "30086": "Rebirth skill not confirmed",          // Cybele
    "30087": "Rebirth skill not confirmed",          // Adad
    "30088": "Rebirth skill not confirmed",          // Mitra
    "30089": "Skills not confirmed",                 // Pemphredo
    "30090": "Skills from Japanese version",         // General Frost
    "30091": "Skills from Japanese version",         // Malthus
    "30093": "Rebirth skill from Japanese version",  // Hantu Raya
    "30094": "Rebirth skill from Japanese version",  // Pantera
    "30095": "Rebirth skill from Japanese version",  // Sharabha
    "30097": "Skills from Japanese version",         // Amalthea
    "30098": "All data from Japanese version",       // 
    "30099": "All data from Japanese version",       // 
    "30100": "Skills from Japanese version",         // Mother of Abominations
    "30101": "All data from Japanese version",
    "30102": "Skills from Japanese version",
    "30111": "All data from Japanese version",
    "30112": "All data from Japanese version",
    "30113": "All data from Japanese version",
    "30114": "All data from Japanese version, rebirth skill missing",
    "30115": "All data from Japanese version, rebirth skill missing",
    "30116": "All data from Japanese version, skills missing",
    "30118": "All data from Japanese version",
    "30119": "All data from Japanese version",
    "30120": "Skills from Japanese version",
    "30121": "All data from Japanese version",
    "30122": "Skills from Japanese version",
    "30123": "All data from Japanese version",
    "30124": "All data from Japanese version",
    "30125": "All data from Japanese version",
    "30126": "All data missing",
    "30127": "All data missing"
});

ExCard.addAll([
    ["35001", "Grendel", "Born of a line cursed by heaven, this giant's forays on a king's mead hall ended when it lost an arm in the doing.",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.giant, Attribute.earth,
     [ExSkill.hp3, ExSkill.hp5, ExSkill.hp7]],
    ["35002", "Sandwalker", "",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.humanoid, Attribute.earth,
     [ExSkill.earth2, ExSkill.earth4, ExSkill.earth6]],
    ["35003", "Sitri", "Darker than darkness itself, this cunning demoness knows all secrets kept, and reveals them at her pleasure.",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.female, Attribute.wind,
     [ExSkill.wind2, ExSkill.wind4, ExSkill.wind6]],
    ["35004", "Phalaris", "",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.wolf, Attribute.mecha,
     [ExSkill.mecha2, ExSkill.mecha4, ExSkill.mecha6]],
    ["35005", "Cerpinus", "Foremost among all dargonkin, this heavenly being descended after the fall of civilization to bring order once more.",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.female, Attribute.light,
     [ExSkill.light2, ExSkill.light4, ExSkill.light6]],
    ["35006", "Beelzebub", "",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.humanoid, Attribute.darkness,
     [ExSkill.darkness2, ExSkill.darkness4, ExSkill.darkness6]],
    ["35007", "Brynhildr", "The ring of betrothal the dragonslayer gifted this fair shieldmaiden bore a curse that visited upon her a cruel fate.",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.female, Attribute.light,
     [ExSkill.wis2, ExSkill.wis4, ExSkill.wis6]],
    ["35008", "Zmey Gorynych", "",
     Event.none, ExType.blue, 4, Place.plains_night, 0, Shape.dragon, Attribute.fire,
     [ExSkill.suc_sd3, ExSkill.suc_sd5, ExSkill.suc_sd7]],
    ["35009", "Jenn", "Possession by this spirit rots the mind and body, and can be ended only with trances, music, and offerings of blood.",
     Event.none, ExType.red, 4, Place.plains_night, 0, Shape.bird, Attribute.wind,
     [ExSkill.def10, ExSkill.def12, ExSkill.def15]],
    ["35010", "Aeacus", "",
     Event.none, ExType.blue, 4, Place.plains_night, 0, Shape.humanoid, Attribute.death,
     [ExSkill.suc_death1, ExSkill.suc_death2, ExSkill.suc_death3]],
    ["35011", "Lucifuge Rofocale", "One of eleven who govern in hell, this demon lord controls all wealth in the mortal realm by his master's order.",
     Event.pink_slime, ExType.red, 4, Place.quests, 0, Shape.none, Attribute.darkness,
     [ExSkill.mp5, ExSkill.mp7, ExSkill.mp10]],
    ["35012", "Alcyone", "Torn by grief after her lover died upon a stormy sea, this divine daughter was turned to a bird by the pity of the gods.",
     Event.pink_slime, ExType.blue, 4, Place.quests, 0, Shape.none, Attribute.wind,
     [ExSkill.suc_ds2, ExSkill.suc_ds3, ExSkill.suc_ds5]],
    ["35013", "Enkidu", "",
     Event.pink_slime, ExType.blue, 4, Place.quests, 0, Shape.wolf, Attribute.lightning,
     [ExSkill.suc_gs2, ExSkill.suc_gs3, ExSkill.suc_gs5]],
    ["35014", "Clotho", "Before entrusting the threads of life to her sisters, this youngest of the Fates first spins them from distaff to spindle.",
     Event.none, ExType.red, 4, Place.zeus, 0, Shape.zfemale, Attribute.mecha,
     [ExSkill.atk4, ExSkill.atk6, ExSkill.atk8]],
    ["35015", "Amaterasu", "",
     Event.none, ExType.blue, 4, Place.zeus, 0, Shape.zfemale, Attribute.light,
     [ExSkill.costdec_bg200, ExSkill.costdec_bg300, ExSkill.costdec_bg500]],
    ["35016", "Engkanto", "",
     Event.none, ExType.red, 4, Place.desert_night, 0, Shape.female, Attribute.water,
     [ExSkill.water2, ExSkill.water4, ExSkill.water6]],
    ["35017", "Apollo", "",
     Event.none, ExType.blue, 4, Place.desert_night, 0, Shape.humanoid, Attribute.light,
     [ExSkill.suc_ls3, ExSkill.suc_ls5, ExSkill.suc_ls7]]
]); 
