#!/bin/bash

if [[ "${1}" != "" ]]; then
  sips -s format jpeg card${1}.png --out card${1}.jpg
  convert -resize 50% card${1}.jpg card${1}.jpg
else
  for file in `ls *.png`; do
    if [[ ! -f ${file/png/jpg} ]]; then
      sips -s format jpeg ${file} --out ${file/png/jpg}
      convert -resize 50% ${file/png/jpg} ${file/png/jpg}
    fi
  done
fi
