#!/bin/bash

#args=("$@")
#size=${#*}

#if [[ ${size} -lt 2 ]]; then
#  echo "./procimgs VER ID1 ID2 ID3 ..."
#  exit
#fi

#ver=${args[0]}

#for i in `seq 1 $((size - 1))`; do
#  id=${args[${i}]}
#  for folder in avatars battle guardians; do
#    pushd images/${ver}/${folder}
#    ./process ${id}
#    popd
#  done
#done

for ver in en jp; do
  for folder in avatars battle guardians; do
    path=images/${ver}/${folder}
    pushd ${path}
    for file in `ls *.png`; do
      if [[ ! -f ${file/.png/.jpg} ]]; then
        id=${file:(-9):5}
        ./process ${id}
      fi
    done
    popd
  done
done
