#!/bin/bash

if [[ "${1}" != "" ]]; then
  sips -s format jpeg card_thu${1}.png --out card_thu${1}.jpg
else
  for file in `ls *.png`; do
    if [[ ! -f ${file/png/jpg} ]]; then
      sips -s format jpeg ${file} --out ${file/png/jpg}
    fi
  done
fi
